import { Injectable, NotFoundException, ForbiddenException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import {
	IRequestTimesheetProjectChange,
  	ITimesheetProjectChangeRequest,
    	IUpdateTimesheetProjectChangeStatus,
      	TimesheetProjectChangeStatus
        } from '@gauzy/contracts';
        import { TimesheetProjectChangeRequest } from './timesheet-project-change-request.entity';
        import { Timesheet } from './timesheet.entity';

        @Injectable()
        export class TimesheetProjectChangeRequestService {
        	constructo
          		@InjectRepository(TimesheetProjectChangeRequest)
              		private readonly changeRequestRepository: Repository<TimesheetProjectChangeRequest>,
                  		@InjectRepository(Timesheet)
                      		private readonly timesheetRepository: Repository<Timesheet>
                          	) {}

                            	/**
                              	 * Request a project change for an existing timesheet.
                                 	 * Employee submits this request with a reason for changing the project.
                                   	 */
                                     	async requestProjectChange(
                                      		input: IRequestTimesheetProjectChange,
                                          		employeeId: string
                                              	): Promise<ITimesheetProjectChangeRequest> {
                                                		const { timesheetId, requestedProjectId, reason, organizationId } = input;

                                                    		// Verify the timesheet exists and belongs to the employee
                                                        		const timesheet = await this.timesheetRepository.findOne({
                                                            			where: { id: timesheetId, employeeId }
                                                                  		});

                                                                      		if (!timesheet) {
                                                                          			throw new NotFoundException(`Timesheet #${timesheetId} not found or access denied`);
                                                                                		}

                                                                                    		// Check if there is already a pending request
                                                                                        		const existingRequest = await this.changeRequestRepository.findOne({
                                                                                            			where: {
                                                                                                  				timesheetId,
                                                                                                          				status: TimesheetProjectChangeStatus.PENDING
                                                                                                                  			}
                                                                                                                        		});
                                                                                                                            
                                                                                                                            		if (existingRequest) {
                                                                                                                                			throw new ForbiddenException('A pending project change request already exists for this timesheet');
                                                                                                                                      		}
                                                                                                                                          
                                                                                                                                          		// Create the change request
                                                                                                                                              		const changeRequest = this.changeRequestRepository.create({
                                                                                                                                                  			timesheetId,
                                                                                                                                                        			requestedProjectId,
                                                                                                                                                              			reason,
                                                                                                                                                                    			organizationId,
                                                                                                                                                                          			tenantId: timesheet.tenantId,
                                                                                                                                                                                			status: TimesheetProjectChangeStatus.PENDING
                                                                                                                                                                                      		});
                                                                                                                                                                                          
                                                                                                                                                                                          		return this.changeRequestRepository.save(changeRequest);
                                                                                                                                                                                              	}
                                                                                                                                                                                                
                                                                                                                                                                                                	/**
                                                                                                                                                                                                  	 * Admin reviews and approves or rejects a project change request.
                                                                                                                                                                                                     	 */
                                                                                                                                                                                                       	async reviewProjectChangeRequest(
                                                                                                                                                                                                        		input: IUpdateTimesheetProjectChangeStatus,
                                                                                                                                                                                                            		reviewerId: string
                                                                                                                                                                                                                	): Promise<ITimesheetProjectChangeRequest> {
                                                                                                                                                                                                                  		const { changeRequestId, status, reviewNote, organizationId } = input;
                                                                                                                                                                                                                      
                                                                                                                                                                                                                      		const changeRequest = await this.changeRequestRepository.findOne({
                                                                                                                                                                                                                          			where: { id: changeRequestId, organizationId },
                                                                                                                                                                                                                                			relations: ['timesheet']
                                                                                                                                                                                                                                      		});
                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                          		if (!changeRequest) {
                                                                                                                                                                                                                                              			throw new NotFoundException(`Change request #${changeRequestId} not found`);
                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                        		if (changeRequest.status !== TimesheetProjectChangeStatus.PENDING) {
                                                                                                                                                                                                                                                            			throw new ForbiddenException('Only pending change requests can be reviewed');
                                                                                                                                                                                                                                                                  		}
                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                      		// Update the request status
                                                                                                                                                                                                                                                                          		changeRequest.status = status;
                                                                                                                                                                                                                                                                              		changeRequest.reviewedById = reviewerId;
                                                                                                                                                                                                                                                                                  		changeRequest.reviewedAt = new Date();
                                                                                                                                                                                                                                                                                      		changeRequest.reviewNote = reviewNote;
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                          		// If approved, update the timesheet's project in related time logs
                                                                                                                                                                                                                                                                                              		if (status === TimesheetProjectChangeStatus.APPROVED) {
                                                                                                                                                                                                                                                                                                  			await this.applyProjectChangeToTimeLogs(changeRequest);
                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            		return this.changeRequestRepository.save(changeRequest);
                                                                                                                                                                                                                                                                                                                	}
                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                  	/**
                                                                                                                                                                                                                                                                                                                    	 * When approved, update all time logs within the timesheet to use the new project.
                                                                                                                                                                                                                                                                                                                       	 */
                                                                                                                                                                                                                                                                                                                         	private async applyProjectChangeToTimeLogs(changeRequest: TimesheetProjectChangeRequest): Promise<void> {
                                                                                                                                                                                                                                                                                                                          		const { timesheetId, requestedProjectId } = changeRequest;
                                                                                                                                                                                                                                                                                                                              		// Update all time logs that belong to this timesheet
                                                                                                                                                                                                                                                                                                                                  		await this.timesheetRepository
                                                                                                                                                                                                                                                                                                                                      			.createQueryBuilder()
                                                                                                                                                                                                                                                                                                                                            			.relation(Timesheet, 'timeLogs')
                                                                                                                                                                                                                                                                                                                                                  			.of(timesheetId)
                                                                                                                                                                                                                                                                                                                                                        			.loadRelationIds();
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              		// Update time logs project via query
                                                                                                                                                                                                                                                                                                                                                                  		await this.changeRequestRepository.manager
                                                                                                                                                                                                                                                                                                                                                                      			.createQueryBuilder()
                                                                                                                                                                                                                                                                                                                                                                            			.update('time_log')
                                                                                                                                                                                                                                                                                                                                                                                  			.set({ projectId: requestedProjectId })
                                                                                                                                                                                                                                                                                                                                                                                        			.where('timesheetId = :timesheetId', { timesheetId })
                                                                                                                                                                                                                                                                                                                                                                                              			.execute();
                                                                                                                                                                                                                                                                                                                                                                                                    	}
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                      	/**
                                                                                                                                                                                                                                                                                                                                                                                                        	 * Get all project change requests for a timesheet
                                                                                                                                                                                                                                                                                                                                                                                                           	 */
                                                                                                                                                                                                                                                                                                                                                                                                             	async getChangeRequestsByTimesheet(timesheetId: string): Promise<ITimesheetProjectChangeRequest[]> {
                                                                                                                                                                                                                                                                                                                                                                                                              		return this.changeRequestRepository.find({
                                                                                                                                                                                                                                                                                                                                                                                                                  			where: { timesheetId },
                                                                                                                                                                                                                                                                                                                                                                                                                        			relations: ['requestedProject', 'previousProject', 'reviewedBy'],
                                                                                                                                                                                                                                                                                                                                                                                                                              			order: { createdAt: 'DESC' }
                                                                                                                                                                                                                                                                                                                                                                                                                                    		});
                                                                                                                                                                                                                                                                                                                                                                                                                                        	}
                                                                                                                                                                                                                                                                                                                                                                                                                                          }
