files:
  - source: /packages/ui-core/i18n/assets/i18n/en.json
    translation: /packages/ui-core/i18n/assets/i18n/%two_letters_code%.json
  - source: /apps/api/src/assets/i18n/en/*.json
    translation: /apps/api/src/assets/i18n/%two_letters_code%/%original_file_name%
