version: '3.8'

services:
  api:
    container_name: api
    image: ghcr.io/ever-co/gauzy-api-demo:latest
    environment:
      API_HOST: ${API_HOST:-api}
      API_PORT: ${API_PORT:-3000}
      NODE_ENV: ${NODE_ENV:-production}
      DB_HOST: ${DB_HOST:-db}
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3000}
      CLIENT_BASE_URL: ${CLIENT_BASE_URL:-http://localhost:4200}
      CLOUD_PROVIDER: ${CLOUD_PROVIDER:-}
      SENTRY_DSN: ${SENTRY_DSN:-}
      SENTRY_HTTP_TRACING_ENABLED: ${SENTRY_HTTP_TRACING_ENABLED:-}
      SENTRY_POSTGRES_TRACKING_ENABLED: ${SENTRY_POSTGRES_TRACKING_ENABLED:-}
      SENTRY_PROFILING_ENABLED: ${SENTRY_PROFILING_ENABLED:-}
      JITSU_SERVER_URL: ${JITSU_SERVER_URL:-}
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:-}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:-}
      OTEL_ENABLED: ${OTEL_ENABLED:-}
      JITSU_SERVER_WRITE_KEY: ${JITSU_SERVER_WRITE_KEY:-}
      GAUZY_GITHUB_CLIENT_ID: ${GAUZY_GITHUB_CLIENT_ID:-}
      GAUZY_GITHUB_CLIENT_SECRET: ${GAUZY_GITHUB_CLIENT_SECRET:-}
      GAUZY_GITHUB_WEBHOOK_URL: ${GAUZY_GITHUB_WEBHOOK_URL:-}
      GAUZY_GITHUB_WEBHOOK_SECRET: ${GAUZY_GITHUB_WEBHOOK_SECRET:-}
      GAUZY_GITHUB_APP_PRIVATE_KEY: ${GAUZY_GITHUB_APP_PRIVATE_KEY:-}
      GAUZY_GITHUB_APP_ID: ${GAUZY_GITHUB_APP_ID:-}
      GAUZY_GITHUB_APP_NAME: ${GAUZY_GITHUB_APP_NAME:-}
      GAUZY_GITHUB_POST_INSTALL_URL: ${GAUZY_GITHUB_POST_INSTALL_URL:-}
      GAUZY_GITHUB_OAUTH_CLIENT_ID: ${GAUZY_GITHUB_OAUTH_CLIENT_ID:-}
      GAUZY_GITHUB_OAUTH_CLIENT_SECRET: ${GAUZY_GITHUB_OAUTH_CLIENT_SECRET:-}
      GAUZY_GITHUB_OAUTH_CALLBACK_URL: ${GAUZY_GITHUB_OAUTH_CALLBACK_URL:-}
      MAGIC_CODE_EXPIRATION_TIME: ${MAGIC_CODE_EXPIRATION_TIME:-}
      APP_NAME: ${APP_NAME:-}
      APP_LOGO: ${APP_LOGO:-}
      APP_SIGNATURE: ${APP_SIGNATURE:-}
      APP_LINK: ${APP_LINK:-}
      APP_EMAIL_CONFIRMATION_URL: ${APP_EMAIL_CONFIRMATION_URL:-}
      APP_MAGIC_SIGN_URL: ${APP_MAGIC_SIGN_URL:-}
      COMPANY_LINK: ${COMPANY_LINK:-}
      COMPANY_NAME: ${COMPANY_NAME:-}

    env_file:
      - .env.compose
    entrypoint: './entrypoint.compose.sh'
    command: ['node', 'main.js']
    restart: on-failure   
    ports:
      - '3000:${API_PORT:-3000}'
    networks:
      - overlay

volumes:  
  certificates: {}

networks:
  overlay:
    driver: bridge
