services:
  db:
    image: postgres:17-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-gauzy}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-gauzy_password}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./.deploy/db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - '5432:5432'
    networks:
      - overlay

  api:
    container_name: api
    image: ghcr.io/ever-co/gauzy-api:latest
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: db
      MAKE_WEBHOOK_URL: ${MAKE_WEBHOOK_URL:-}

    env_file:
      - .env.demo.compose
    entrypoint: './entrypoint.compose.sh'
    command: ['node', 'main.js']
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:${DB_HOST:-db}
    # volumes:
    # - webapp_node_modules:/srv/gauzy/node_modules
    # - api_node_modules:/srv/gauzy/apps/api/node_modules
    ports:
      - '3000:${API_PORT:-3000}'
    networks:
      - overlay

  webapp:
    container_name: webapp
    image: ghcr.io/ever-co/gauzy-webapp:latest
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      SENTRY_PROFILE_SAMPLE_RATE: ${SENTRY_PROFILE_SAMPLE_RATE:-1}
      DEMO: 'true'
    entrypoint: './entrypoint.compose.sh'
    command: ['nginx', '-g', 'daemon off;']
    env_file:
      - .env.demo.compose
    restart: on-failure
    links:
      - db:${DB_HOST:-db}
      - api:${API_HOST:-api}
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    # volumes:
    # - webapp_node_modules:/srv/gauzy/node_modules
    ports:
      - '4200:${UI_PORT:-4200}'
    networks:
      - overlay

volumes:
  # webapp_node_modules:
  # api_node_modules:
  postgres_data: {}

networks:
  overlay:
    driver: bridge
