const CONSTANT =  {
	TRAY_ICON_PATH: 'assets/icons/tray/icon.png'
}

const MAIN_EVENT = 'MAIN_EVENT';

const MAIN_EVENT_TYPE = {
	LOGOUT_EVENT: 'LOGOUT_EVENT',
	SETUP_EVENT: 'SETUP_EVENT',
	TRAY_NOTIFY_EVENT: 'TRAY_NOTIFY_EVENT',
	START_TIMER: 'START_TIMER',
	STOP_TIMER: 'STOP_TIMER',
	UPDATE_APP_SETTING: 'UPDATE_APP_SETTING',
	INIT_SCREENSHOT: 'INIT_SCREENSHOT',
	START_TIMER_API: 'START_TIMER_API',
	CHECK_STATUS_TIMER: 'CHECK_STATUS_TIMER',
	TRAY_TIMER_STATUS: 'TRAY_TIMER_STATUS'
}

export type TMainEventType = typeof MAIN_EVENT_TYPE[keyof typeof MAIN_EVENT_TYPE];

export {
	CONSTANT,
	MAIN_EVENT,
	MAIN_EVENT_TYPE
}
