const CONSTANT =  {
	TRAY_ICON_PATH: 'assets/icons/tray/icon.png'
}

const MAIN_EVENT = 'MAIN_EVENT';

const MAIN_EVENT_TYPE = {
	LOGOUT_EVENT: 'LOGOUT_EVENT',
	SETUP_EVENT: 'SETUP_EVENT',
	TRAY_NOTIFY_EVENT: 'TRAY_NOTIFY_EVENT',
	START_TIMER: 'START_TIMER',
	STOP_TIMER: 'STOP_TIMER',
	UPDATE_APP_SETTING: 'UPDATE_APP_SETTING'
}

export {
	CONSTANT,
	MAIN_EVENT,
	MAIN_EVENT_TYPE
}
