import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, FindManyOptions, Between } from 'typeorm';
import {
	IPayrollRun,
  	IPayrollItem,
    	IPayrollRunCreateInput,
      	IPayrollRunUpdateInput,
        	IPayrollRunFindInput,
          	IPayrollSummary,
            	IPayrollStatistics,
              	PayrollRunStatusEnum,
                	PayrollItemCategoryEnum
                  } from '@gauzy/contracts';
                  import { PayrollRun } from './payroll-run.entity';
                  import { PayrollItem } from '../payroll-item/payroll-item.entity';

                  @Injectable()
                  export class PayrollRunService {

                  	constructor(
                    		@InjectRepository(PayrollRun)
                        		private readonly payrollRunRepository: Repository<PayrollRun>,

                            		@InjectRepository(PayrollItem)
                                		private readonly payrollItemRepository: Repository<PayrollItem>
                                    	) {}

                                      	/**
                                        	 * Create a new payroll run (draft)
                                           	 */
                                             	async create(input: IPayrollRunCreateInput): Promise<IPayrollRun> {
                                              		const run = this.payrollRunRepository.create({
                                                  			...input,
                                                        			status: PayrollRunStatusEnum.DRAFT,
                                                              			totalGross: 0,
                                                                    			totalDeductions: 0,
                                                                          			totalNet: 0
                                                                                		});
                                                                                    		return this.payrollRunRepository.save(run);
                                                                                        	}

                                                                                          	/**
                                                                                            	 * Find all payroll runs with optional filters
                                                                                               	 */
                                                                                                 	async findAll(filter: IPayrollRunFindInput = {}): Promise<{ items: IPayrollRun[]; total: number }> {
                                                                                                  		const { organizationId, tenantId, status, frequency, periodStart, periodEnd, skip, take } = filter as any;
                                                                                                      
                                                                                                      		const where: any = {};
                                                                                                          		if (organizationId) where.organizationId = organizationId;
                                                                                                              		if (tenantId) where.tenantId = tenantId;
                                                                                                                  		if (status) where.status = status;
                                                                                                                      		if (frequency) where.frequency = frequency;
                                                                                                                          		if (periodStart && periodEnd) {
                                                                                                                              			where.periodStart = Between(periodStart, periodEnd);
                                                                                                                                    		}
                                                                                                                                        
                                                                                                                                        		const options: FindManyOptions<PayrollRun> = {
                                                                                                                                            			where,
                                                                                                                                                  			relations: ['items'],
                                                                                                                                                        			order: { periodStart: 'DESC' },
                                                                                                                                                              			skip: skip || 0,
                                                                                                                                                                    			take: take || 10
                                                                                                                                                                          		};
                                                                                                                                                                              
                                                                                                                                                                              		const [items, total] = await this.payrollRunRepository.findAndCount(options);
                                                                                                                                                                                  		return { items, total };
                                                                                                                                                                                      	}
                                                                                                                                                                                        
                                                                                                                                                                                        	/**
                                                                                                                                                                                          	 * Find a single payroll run by ID
                                                                                                                                                                                             	 */
                                                                                                                                                                                               	async findOne(id: string): Promise<IPayrollRun> {
                                                                                                                                                                                                		const run = await this.payrollRunRepository.findOne({
                                                                                                                                                                                                    			where: { id },
                                                                                                                                                                                                          			relations: ['items', 'items.employee']
                                                                                                                                                                                                                		});
                                                                                                                                                                                                                    		if (!run) {
                                                                                                                                                                                                                        			throw new NotFoundException(`PayrollRun with id=${id} not found`);
                                                                                                                                                                                                                              		}
                                                                                                                                                                                                                                  		return run;
                                                                                                                                                                                                                                      	}
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        	/**
                                                                                                                                                                                                                                          	 * Update a payroll run (only allowed when DRAFT or PENDING_APPROVAL)
                                                                                                                                                                                                                                             	 */
                                                                                                                                                                                                                                               	async update(id: string, input: IPayrollRunUpdateInput): Promise<IPayrollRun> {
                                                                                                                                                                                                                                                		const run = await this.findOne(id);
                                                                                                                                                                                                                                                    		if (run.status === PayrollRunStatusEnum.PAID || run.status === PayrollRunStatusEnum.CANCELLED) {
                                                                                                                                                                                                                                                        			throw new BadRequestException(`Cannot update a payroll run with status ${run.status}`);
                                                                                                                                                                                                                                                              		}
                                                                                                                                                                                                                                                                  		Object.assign(run, input);
                                                                                                                                                                                                                                                                      		return this.payrollRunRepository.save(run as PayrollRun);
                                                                                                                                                                                                                                                                          	}
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                            	/**
                                                                                                                                                                                                                                                                              	 * Submit a payroll run for approval
                                                                                                                                                                                                                                                                                 	 */
                                                                                                                                                                                                                                                                                   	async submitForApproval(id: string): Promise<IPayrollRun> {
                                                                                                                                                                                                                                                                                    		const run = await this.findOne(id);
                                                                                                                                                                                                                                                                                        		if (run.status !== PayrollRunStatusEnum.DRAFT) {
                                                                                                                                                                                                                                                                                            			throw new BadRequestException('Only DRAFT payroll runs can be submitted for approval');
                                                                                                                                                                                                                                                                                                  		}
                                                                                                                                                                                                                                                                                                      		run.status = PayrollRunStatusEnum.PENDING_APPROVAL;
                                                                                                                                                                                                                                                                                                          		return this.payrollRunRepository.save(run as PayrollRun);
                                                                                                                                                                                                                                                                                                              	}
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                	/**
                                                                                                                                                                                                                                                                                                                  	 * Approve a payroll run
                                                                                                                                                                                                                                                                                                                     	 */
                                                                                                                                                                                                                                                                                                                       	async approve(id: string): Promise<IPayrollRun> {
                                                                                                                                                                                                                                                                                                                        		const run = await this.findOne(id);
                                                                                                                                                                                                                                                                                                                            		if (run.status !== PayrollRunStatusEnum.PENDING_APPROVAL) {
                                                                                                                                                                                                                                                                                                                                			throw new BadRequestException('Only PENDING_APPROVAL payroll runs can be approved');
                                                                                                                                                                                                                                                                                                                                      		}
                                                                                                                                                                                                                                                                                                                                          		run.status = PayrollRunStatusEnum.APPROVED;
                                                                                                                                                                                                                                                                                                                                              		return this.payrollRunRepository.save(run as PayrollRun);
                                                                                                                                                                                                                                                                                                                                                  	}
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                    	/**
                                                                                                                                                                                                                                                                                                                                                      	 * Process (mark as paid) an approved payroll run
                                                                                                                                                                                                                                                                                                                                                         	 * Also recalculates totals from line items
                                                                                                                                                                                                                                                                                                                                                           	 */
                                                                                                                                                                                                                                                                                                                                                             	async process(id: string): Promise<IPayrollRun> {
                                                                                                                                                                                                                                                                                                                                                              		const run = await this.findOne(id);
                                                                                                                                                                                                                                                                                                                                                                  		if (run.status !== PayrollRunStatusEnum.APPROVED) {
                                                                                                                                                                                                                                                                                                                                                                      			throw new BadRequestException('Only APPROVED payroll runs can be processed');
                                                                                                                                                                                                                                                                                                                                                                            		}
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                		// Recalculate totals
                                                                                                                                                                                                                                                                                                                                                                                    		const items = run.items || [];
                                                                                                                                                                                                                                                                                                                                                                                        		let totalGross = 0;
                                                                                                                                                                                                                                                                                                                                                                                            		let totalDeductions = 0;
                                                                                                                                                                                                                                                                                                                                                                                                		for (const item of items) {
                                                                                                                                                                                                                                                                                                                                                                                                    			if (item.category === PayrollItemCategoryEnum.EARNING) {
                                                                                                                                                                                                                                                                                                                                                                                                          				totalGross += Number(item.amount);
                                                                                                                                                                                                                                                                                                                                                                                                                  			} else {
                                                                                                                                                                                                                                                                                                                                                                                                                        				totalDeductions += Number(item.amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                			}
                                                                                                                                                                                                                                                                                                                                                                                                                                      		}
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                          		run.totalGross = totalGross;
                                                                                                                                                                                                                                                                                                                                                                                                                                              		run.totalDeductions = totalDeductions;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  		run.totalNet = totalGross - totalDeductions;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      		run.status = PayrollRunStatusEnum.PAID;
                                                                                                                                                                                                                                                                                                                                                                                                                                                          		return this.payrollRunRepository.save(run as PayrollRun);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                	/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  	 * Cancel a payroll run
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     	 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       	async cancel(id: string): Promise<IPayrollRun> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		const run = await this.findOne(id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		if (run.status === PayrollRunStatusEnum.PAID) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			throw new BadRequestException('Cannot cancel a PAID payroll run');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          		run.status = PayrollRunStatusEnum.CANCELLED;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              		return this.payrollRunRepository.save(run as PayrollRun);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      	 * Get payroll summary per employee for a given run
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         	 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	async getSummaryByRun(runId: string): Promise<IPayrollSummary[]> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		const run = await this.findOne(runId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		const items = run.items || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		const map = new Map<string, IPayrollSummary>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		for (const item of items) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			const empId = item.employeeId;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  			if (!empId) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			if (!map.has(empId)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              				map.set(empId, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      					employeeId: empId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                					employee: item.employee,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          					periodStart: run.periodStart,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    					periodEnd: run.periodEnd,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              					grossPay: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					totalDeductions: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  					netPay: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            					currency: run.currency
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      				});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			const summary = map.get(empId)!;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          			if (item.category === PayrollItemCategoryEnum.EARNING) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				summary.grossPay += Number(item.amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			} else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              				summary.totalDeductions += Number(item.amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			summary.netPay = summary.grossPay - summary.totalDeductions;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      		return Array.from(map.values());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              	 * Get overall payroll statistics
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 	 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   	async getStatistics(organizationId: string): Promise<IPayrollStatistics> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		const runs = await this.payrollRunRepository.find({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			where: { organizationId, status: PayrollRunStatusEnum.PAID }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              		});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  		const totalRuns = runs.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      		let totalGrossPaid = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          		let totalDeductions = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              		let totalNetPaid = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  		for (const r of runs) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      			totalGrossPaid += Number(r.totalGross);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			totalDeductions += Number(r.totalDeductions);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  			totalNetPaid += Number(r.totalNet);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			totalRuns,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      			totalEmployeesPaid: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			totalGrossPaid,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  			totalDeductions,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			totalNetPaid,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              			currency: runs[0]?.currency || 'USD'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
