#!/usr/bin/env sh
set -eux

export PORT=${PORT:-4200}
export HOST=${HOST:-0.0.0.0}

if [ -z "$@" ]; then
  "$0" yarn nx serve gauzy --host "$HOST" --port "$PORT" --disable-host-check
  exit
fi

export API_HOST=${API_HOST:-api}
export API_PORT=${API_PORT:-3000}
export WAIT_HOSTS=$API_HOST:$API_PORT

# if [ -f /etc/nginx/nginx.conf ]; then
#   sed -i -e "s/server api:3000;/server $API_HOST:$API_PORT;/g" \
#       -e "s/listen 4200;/listen $PORT;/g" /etc/nginx/nginx.conf
# fi

./wait
exec "$@"
