#!/bin/sh
set -ex

# This Entrypoint used inside Docker Compose only

export WAIT_HOSTS=$API_HOST:$API_PORT

# In production we should replace some values in generated JS code
sed -i "s#DOCKER_API_HOST#$API_HOST#g" *.js
sed -i "s#DOCKER_API_PORT#$API_PORT#g" *.js
sed -i "s#DOCKER_API_BASE_URL#$API_BASE_URL#g" *.js
sed -i "s#DOCKER_CLIENT_BASE_URL#$CLIENT_BASE_URL#g" *.js
sed -i "s#DOCKER_GAUZY_CLOUD_APP#$GAUZY_CLOUD_APP#g" *.js
sed -i "s#DOCKER_SENTRY_DSN#$SENTRY_DSN#g" *.js
sed -i "s#DOCKER_SENTRY_TRACES_SAMPLE_RATE#$SENTRY_TRACES_SAMPLE_RATE#g" *.js
sed -i "s#DOCKER_CHATWOOT_SDK_TOKEN#$CHATWOOT_SDK_TOKEN#g" *.js
sed -i "s#DOCKER_CHAT_MESSAGE_GOOGLE_MAP#$CHAT_MESSAGE_GOOGLE_MAP#g" *.js
sed -i "s#DOCKER_CLOUDINARY_CLOUD_NAME#$CLOUDINARY_CLOUD_NAME#g" *.js
sed -i "s#DOCKER_CLOUDINARY_API_KEY#$CLOUDINARY_API_KEY#g" *.js
sed -i "s#DOCKER_GOOGLE_MAPS_API_KEY#$GOOGLE_MAPS_API_KEY#g" *.js
sed -i "s#DOCKER_GOOGLE_PLACE_AUTOCOMPLETE#$GOOGLE_PLACE_AUTOCOMPLETE#g" *.js
sed -i "s|DOCKER_HUBSTAFF_REDIRECT_URL|$HUBSTAFF_REDIRECT_URL|g" *.js
sed -i "s#DOCKER_DEFAULT_LATITUDE#$DEFAULT_LATITUDE#g" *.js
sed -i "s#DOCKER_DEFAULT_LONGITUDE#$DEFAULT_LONGITUDE#g" *.js
sed -i "s#DOCKER_DEFAULT_CURRENCY#$DEFAULT_CURRENCY#g" *.js
sed -i "s#DOCKER_DEFAULT_COUNTRY#$DEFAULT_COUNTRY#g" *.js
sed -i "s#DOCKER_DEMO#$DEMO#g" *.js
sed -i "s#DOCKER_WEB_HOST#$WEB_HOST#g" *.js
sed -i "s#DOCKER_WEB_PORT#$WEB_PORT#g" *.js
sed -i "s#DOCKER_GAUZY_GITHUB_CLIENT_ID#$GAUZY_GITHUB_CLIENT_ID#g" *.js
sed -i "s#DOCKER_GAUZY_GITHUB_APP_NAME#$GAUZY_GITHUB_APP_NAME#g" *.js
sed -i "s|DOCKER_GAUZY_GITHUB_REDIRECT_URL|$GAUZY_GITHUB_REDIRECT_URL|g" *.js
sed -i "s#DOCKER_GAUZY_GITHUB_APP_ID#$GAUZY_GITHUB_APP_ID#g" *.js
sed -i "s|DOCKER_GAUZY_GITHUB_POST_INSTALL_URL|$GAUZY_GITHUB_POST_INSTALL_URL|g" *.js
sed -i "s|DOCKER_JITSU_BROWSER_URL|$JITSU_BROWSER_URL|g" *.js
sed -i "s#DOCKER_JITSU_BROWSER_WRITE_KEY#$JITSU_BROWSER_WRITE_KEY#g" *.js
sed -i "s|DOCKER_NO_INTERNET_LOGO|$NO_INTERNET_LOGO|g" *.js
sed -i "s#DOCKER_FILE_PROVIDER#$FILE_PROVIDER#g" *.js
sed -i "s|DOCKER_PLATFORM_LOGO|$PLATFORM_LOGO|g" *.js
sed -i "s|DOCKER_GAUZY_DESKTOP_LOGO_512X512|$GAUZY_DESKTOP_LOGO_512X512|g" *.js
sed -i "s|DOCKER_PLATFORM_PRIVACY_URL|$PLATFORM_PRIVACY_URL|g" *.js
sed -i "s|DOCKER_PLATFORM_TOS_URL|$PLATFORM_TOS_URL|g" *.js
sed -i "s|DOCKER_PROJECT_REPO|$PROJECT_REPO|g" *.js
sed -i "s|DOCKER_I18N_FILES_URL|$I18N_FILES_URL|g" *.js
sed -i "s#DOCKER_COMPANY_NAME#$COMPANY_NAME#g" *.js
sed -i "s|DOCKER_COMPANY_SITE|$COMPANY_SITE|g" *.js
sed -i "s|DOCKER_COMPANY_LINK|$COMPANY_LINK|g" *.js
sed -i "s|DOCKER_COMPANY_SITE_LINK|$COMPANY_SITE_LINK|g" *.js
sed -i "s|DOCKER_COMPANY_GITHUB_LINK|$COMPANY_GITHUB_LINK|g" *.js
sed -i "s|DOCKER_COMPANY_GITLAB_LINK|$COMPANY_GITLAB_LINK|g" *.js
sed -i "s|DOCKER_COMPANY_FACEBOOK_LINK|$COMPANY_FACEBOOK_LINK|g" *.js
sed -i "s|DOCKER_COMPANY_TWITTER_LINK|$COMPANY_TWITTER_LINK|g" *.js
sed -i "s|DOCKER_COMPANY_LINKEDIN_LINK|$COMPANY_LINKEDIN_LINK|g" *.js
sed -i "s|DOCKER_PLATFORM_WEBSITE_URL|$PLATFORM_WEBSITE_URL|g" *.js
sed -i "s|DOCKER_PLATFORM_WEBSITE_DOWNLOAD_URL|$PLATFORM_WEBSITE_DOWNLOAD_URL|g" *.js
sed -i "s|DOCKER_DESKTOP_APP_DOWNLOAD_LINK_APPLE|$DESKTOP_APP_DOWNLOAD_LINK_APPLE|g" *.js
sed -i "s|DOCKER_DESKTOP_APP_DOWNLOAD_LINK_WINDOWS|$DESKTOP_APP_DOWNLOAD_LINK_WINDOWS|g" *.js
sed -i "s|DOCKER_DESKTOP_APP_DOWNLOAD_LINK_LINUX|$DESKTOP_APP_DOWNLOAD_LINK_LINUX|g" *.js
sed -i "s|DOCKER_MOBILE_APP_DOWNLOAD_LINK|$MOBILE_APP_DOWNLOAD_LINK|g" *.js
sed -i "s|DOCKER_EXTENSION_DOWNLOAD_LINK|$EXTENSION_DOWNLOAD_LINK|g" *.js

# We need to copy nginx.conf to correct place
envsubst '${API_HOST} ${API_PORT}' < /etc/nginx/conf.d/compose.conf.template > /etc/nginx/nginx.conf

# In Docker Compose we should wait other services start
./wait

exec "$@"
