#!/usr/bin/env sh
set -eux

# This Entrypoint used inside Docker Compose only

export PORT=${PORT:-4200}
export HOST=${HOST:-0.0.0.0}
export API_HOST=${API_HOST:-api}
export API_PORT=${API_PORT:-3000}
export WAIT_HOSTS=$API_HOST:$API_PORT
export API_BASE_URL=$API_BASE_URL

envsubst '${API_HOST} ${API_PORT} ${API_BASE_URL}' < /etc/nginx/default.conf.template > /etc/nginx/nginx.conf
rm /etc/nginx/default.conf.template

# in Docker Compose we should wait other services start
./wait

exec "$@"
