import { PermissionsEnum, RolesEnum } from '@gauzy/contracts';

export const DEFAULT_ROLE_PERMISSIONS = [
	{
		role: RolesEnum.SUPER_ADMIN,
		defaultEnabledPermissions: [
			PermissionsEnum.ADMIN_DASHBOARD_VIEW,
			PermissionsEnum.TEAM_DASHBOARD,
			PermissionsEnum.PROJECT_MANAGEMENT_DASHBOARD,
			PermissionsEnum.TIME_TRACKING_DASHBOARD,
			PermissionsEnum.ACCOUNTING_DASHBOARD,
			PermissionsEnum.HUMAN_RESOURCE_DASHBOARD,
			PermissionsEnum.ORG_PAYMENT_VIEW,
			PermissionsEnum.ORG_PAYMENT_ADD_EDIT,
			PermissionsEnum.ORG_INCOMES_VIEW,
			PermissionsEnum.ORG_INCOMES_EDIT,
			/** Payroll Permissions Start */
			PermissionsEnum.ORG_PAYROLL_VIEW,
			PermissionsEnum.ORG_PAYROLL_EDIT,
			PermissionsEnum.ORG_PAYROLL_APPROVE,
			/** Payroll Permissions End */
			PermissionsEnum.ORG_EXPENSES_VIEW,
			PermissionsEnum.ORG_EXPENSES_EDIT,
			PermissionsEnum.EMPLOYEE_EXPENSES_VIEW,
			PermissionsEnum.EMPLOYEE_EXPENSES_EDIT,
			PermissionsEnum.ORG_PROPOSALS_VIEW,
			PermissionsEnum.ORG_PROPOSALS_EDIT,
			PermissionsEnum.ORG_PROPOSAL_TEMPLATES_VIEW,
			PermissionsEnum.ORG_PROPOSAL_TEMPLATES_EDIT,
			PermissionsEnum.ORG_TASK_ADD,
			PermissionsEnum.ORG_TASK_VIEW,
			PermissionsEnum.ORG_TASK_EDIT,
			PermissionsEnum.ORG_TASK_DELETE,
			PermissionsEnum.SELECT_EMPLOYEE,
			/** Organization Task Setting Permissions Start */
			PermissionsEnum.ORG_TASK_SETTING,
			/** Organization Task Setting Permissions End */
			/** Employee CRUD Permissions Start */
			PermissionsEnum.ORG_EMPLOYEES_ADD,
			PermissionsEnum.ORG_EMPLOYEES_VIEW,
			PermissionsEnum.ORG_EMPLOYEES_EDIT,
			PermissionsEnum.ORG_EMPLOYEES_DELETE,
			/** Employee CRUD Permissions End */
			/** Member View Permissions Start */
			PermissionsEnum.ORG_MEMBERS_VIEW,
			/** Member View Permissions End */
			PermissionsEnum.ORG_CANDIDATES_VIEW,
			PermissionsEnum.ORG_CANDIDATES_EDIT,
			PermissionsEnum.ORG_CANDIDATES_TASK_EDIT,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEW_EDIT,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEW_VIEW,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEWERS_EDIT,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEWERS_VIEW,
			PermissionsEnum.ORG_INVENTORY_VIEW,
			PermissionsEnum.ORG_INVENTORY_PRODUCT_EDIT,
			PermissionsEnum.ORG_CANDIDATES_DOCUMENTS_VIEW,
			PermissionsEnum.ORG_HELP_CENTER_EDIT,
			PermissionsEnum.ORG_USERS_VIEW,
			PermissionsEnum.ORG_USERS_EDIT,
			PermissionsEnum.ALL_ORG_VIEW,
			PermissionsEnum.ALL_ORG_EDIT,
			/** Equipment Sharing Policy Permissions Start */
			PermissionsEnum.EQUIPMENT_SHARING_POLICY_ADD,
			PermissionsEnum.EQUIPMENT_SHARING_POLICY_VIEW,
			PermissionsEnum.EQUIPMENT_SHARING_POLICY_EDIT,
			PermissionsEnum.EQUIPMENT_SHARING_POLICY_DELETE,
			/** Equipment Sharing Policy Permissions End */
			PermissionsEnum.APPROVAL_POLICY_EDIT,
			PermissionsEnum.APPROVAL_POLICY_VIEW,
			PermissionsEnum.REQUEST_APPROVAL_EDIT,
			PermissionsEnum.REQUEST_APPROVAL_VIEW,
			/** Time Off Permissions Start */
			PermissionsEnum.TIME_OFF_ADD,
			PermissionsEnum.TIME_OFF_VIEW,
			PermissionsEnum.TIME_OFF_EDIT,
			PermissionsEnum.TIME_OFF_DELETE,
			/** Time Off Permissions End */
			PermissionsEnum.CHANGE_SELECTED_EMPLOYEE,
			PermissionsEnum.CHANGE_SELECTED_CANDIDATE,
			PermissionsEnum.CHANGE_SELECTED_ORGANIZATION,
			PermissionsEnum.CHANGE_ROLES_PERMISSIONS,
			PermissionsEnum.ORG_INVITE_VIEW,
			PermissionsEnum.ORG_INVITE_EDIT,
			PermissionsEnum.ACCESS_PRIVATE_PROJECTS,
			PermissionsEnum.TIMESHEET_EDIT_TIME,
			PermissionsEnum.SUPER_ADMIN_EDIT,
			PermissionsEnum.PUBLIC_PAGE_EDIT,
			PermissionsEnum.INVOICES_VIEW,
			PermissionsEnum.INVOICES_EDIT,
			PermissionsEnum.ESTIMATES_VIEW,
			PermissionsEnum.ESTIMATES_EDIT,
			PermissionsEnum.ORG_CANDIDATES_FEEDBACK_EDIT,
			/** Tags Permissions Start */
			PermissionsEnum.ORG_TAGS_ADD,
			PermissionsEnum.ORG_TAGS_VIEW,
			PermissionsEnum.ORG_TAGS_EDIT,
			PermissionsEnum.ORG_TAGS_DELETE,
			/** Tags Permissions End */
			/** Tags Types Permissions Start */
			PermissionsEnum.ORG_TAG_TYPES_ADD,
			PermissionsEnum.ORG_TAG_TYPES_VIEW,
			PermissionsEnum.ORG_TAG_TYPES_EDIT,
			PermissionsEnum.ORG_TAG_TYPES_DELETE,
			/** Tags Types Permissions End */
			PermissionsEnum.VIEW_ALL_EMAILS,
			PermissionsEnum.VIEW_ALL_EMAIL_TEMPLATES,
			PermissionsEnum.VIEW_SALES_PIPELINES,
			PermissionsEnum.EDIT_SALES_PIPELINES,
			PermissionsEnum.CAN_APPROVE_TIMESHEET,
			PermissionsEnum.ORG_SPRINT_ADD,
			PermissionsEnum.ORG_SPRINT_EDIT,
			PermissionsEnum.ORG_SPRINT_VIEW,
			PermissionsEnum.ORG_SPRINT_DELETE,
			PermissionsEnum.ORG_PROJECT_ADD,
			PermissionsEnum.ORG_PROJECT_VIEW,
			PermissionsEnum.ORG_PROJECT_EDIT,
			PermissionsEnum.ORG_PROJECT_DELETE,
			PermissionsEnum.ORG_CONTACT_EDIT,
			PermissionsEnum.ORG_CONTACT_VIEW,
			/** Daily CRUD Permissions Start */
			PermissionsEnum.DAILY_PLAN_CREATE,
			PermissionsEnum.DAILY_PLAN_READ,
			PermissionsEnum.DAILY_PLAN_UPDATE,
			PermissionsEnum.DAILY_PLAN_DELETE,
			/** Daily CRUD Permissions End */
			/** Project Module Permissions start */
			PermissionsEnum.PROJECT_MODULE_CREATE,
			PermissionsEnum.PROJECT_MODULE_READ,
			PermissionsEnum.PROJECT_MODULE_UPDATE,
			PermissionsEnum.PROJECT_MODULE_DELETE,
			/** Project Module Permissions end */
			/** Dashboard Permissions Start */
			PermissionsEnum.DASHBOARD_CREATE,
			PermissionsEnum.DASHBOARD_READ,
			PermissionsEnum.DASHBOARD_UPDATE,
			PermissionsEnum.DASHBOARD_DELETE,
			/** Dashboard Permissions End */
			/** Organization Team */
			PermissionsEnum.ORG_TEAM_ADD,
			PermissionsEnum.ORG_TEAM_VIEW,
			PermissionsEnum.ORG_TEAM_EDIT,
			PermissionsEnum.ORG_TEAM_DELETE,
			PermissionsEnum.ORG_TEAM_EDIT_ACTIVE_TASK,
			PermissionsEnum.ORG_TEAM_REMOVE_ACCOUNT_AS_MEMBER,
			PermissionsEnum.ORG_TEAM_JOIN_REQUEST_VIEW,
			PermissionsEnum.ORG_TEAM_JOIN_REQUEST_EDIT,
			PermissionsEnum.ORG_CONTRACT_EDIT,
			PermissionsEnum.EVENT_TYPES_VIEW,
			PermissionsEnum.TENANT_ADD_EXISTING_USER,
			/** Integration CRUD Permissions Start */
			PermissionsEnum.INTEGRATION_ADD,
			PermissionsEnum.INTEGRATION_VIEW,
			PermissionsEnum.INTEGRATION_EDIT,
			PermissionsEnum.INTEGRATION_DELETE,
			/** Integration CRUD Permissions End */
			/** AI Chat Permissions Start */
			PermissionsEnum.AI_CHAT_ACCESS,
			PermissionsEnum.AI_CHAT_SETTINGS,
			/** AI Chat Permissions End */
			/** Documents Permissions Start */
			PermissionsEnum.DOCS_READ,
			PermissionsEnum.DOCS_CREATE,
			PermissionsEnum.DOCS_UPDATE,
			PermissionsEnum.DOCS_DELETE,
			PermissionsEnum.DOCS_MANAGE,
			PermissionsEnum.DOCS_REVIEW,
			PermissionsEnum.DOCS_AI_IMPORT,
			/** Documents Permissions End */
			PermissionsEnum.IMPORT_ADD,
			PermissionsEnum.EXPORT_ADD,
			PermissionsEnum.FILE_STORAGE_VIEW,
			PermissionsEnum.PAYMENT_GATEWAY_VIEW,
			PermissionsEnum.SMS_GATEWAY_VIEW,
			PermissionsEnum.CUSTOM_SMTP_VIEW,
			/** Job Post Permissions Start */
			PermissionsEnum.ORG_JOB_EMPLOYEE_VIEW,
			PermissionsEnum.ORG_JOB_MATCHING_VIEW,
			PermissionsEnum.ORG_JOB_SEARCH,
			PermissionsEnum.ORG_JOB_APPLY,
			PermissionsEnum.ORG_JOB_EDIT,
			/** Job Post Permissions End */
			PermissionsEnum.ORG_EQUIPMENT_VIEW,
			PermissionsEnum.ORG_EQUIPMENT_EDIT,
			PermissionsEnum.ORG_EQUIPMENT_SHARING_VIEW,
			PermissionsEnum.ORG_EQUIPMENT_SHARING_EDIT,
			PermissionsEnum.EQUIPMENT_MAKE_REQUEST,
			PermissionsEnum.EQUIPMENT_APPROVE_REQUEST,
			PermissionsEnum.ORG_PRODUCT_TYPES_VIEW,
			PermissionsEnum.ORG_PRODUCT_TYPES_EDIT,
			PermissionsEnum.ORG_PRODUCT_CATEGORIES_VIEW,
			PermissionsEnum.ORG_PRODUCT_CATEGORIES_EDIT,
			PermissionsEnum.VIEW_ALL_ACCOUNTING_TEMPLATES,
			PermissionsEnum.MIGRATE_GAUZY_CLOUD,
			PermissionsEnum.INVENTORY_GALLERY_ADD,
			PermissionsEnum.INVENTORY_GALLERY_VIEW,
			PermissionsEnum.INVENTORY_GALLERY_EDIT,
			PermissionsEnum.INVENTORY_GALLERY_DELETE,
			PermissionsEnum.MEDIA_GALLERY_ADD,
			PermissionsEnum.MEDIA_GALLERY_VIEW,
			PermissionsEnum.MEDIA_GALLERY_EDIT,
			PermissionsEnum.MEDIA_GALLERY_DELETE,
			PermissionsEnum.ACCESS_DELETE_ACCOUNT,
			PermissionsEnum.ACCESS_DELETE_ALL_DATA,
			PermissionsEnum.PROFILE_EDIT,
			PermissionsEnum.TIME_TRACKER,
			PermissionsEnum.TENANT_SETTING,
			PermissionsEnum.GLOBAL_SETTING,
			PermissionsEnum.ALLOW_DELETE_TIME,
			PermissionsEnum.ALLOW_MODIFY_TIME,
			PermissionsEnum.ALLOW_MANUAL_TIME,
			PermissionsEnum.DELETE_SCREENSHOTS,
			PermissionsEnum.ORG_MEMBER_LAST_LOG_VIEW,
			/** API Call Log */
			PermissionsEnum.API_CALL_LOG_READ,
			PermissionsEnum.API_CALL_LOG_DELETE,
			/** Tenant API Key */
			PermissionsEnum.TENANT_API_KEY_CREATE,
			PermissionsEnum.TENANT_API_KEY_VIEW,
			PermissionsEnum.TENANT_API_KEY_DELETE,
			/** OAuth App Client Registry (multi-app OAuth provider) */
			PermissionsEnum.OAUTH_CLIENT_VIEW,
			PermissionsEnum.OAUTH_CLIENT_EDIT,
			/** Employee Availability */
			PermissionsEnum.EMPLOYEE_AVAILABILITY_CREATE,
			PermissionsEnum.EMPLOYEE_AVAILABILITY_READ,
			PermissionsEnum.EMPLOYEE_AVAILABILITY_UPDATE,
			PermissionsEnum.EMPLOYEE_AVAILABILITY_DELETE,
			/** Broadcast Permissions Start */
			PermissionsEnum.BROADCAST_CREATE,
			PermissionsEnum.BROADCAST_READ,
			PermissionsEnum.BROADCAST_UPDATE,
			PermissionsEnum.BROADCAST_DELETE,
			/** Broadcast Permissions End */
			/** Organization Strategic Initiative Permissions Start */
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_CREATE,
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_READ,
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_UPDATE,
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_DELETE,
			/** Organization Strategic Initiative Permissions End */
			// Plugin permissions
			PermissionsEnum.PLUGIN_VIEW,
			PermissionsEnum.PLUGIN_DISCOVER,
			PermissionsEnum.PLUGIN_INSTALL,
			PermissionsEnum.PLUGIN_UNINSTALL,
			PermissionsEnum.PLUGIN_UPDATE,
			PermissionsEnum.PLUGIN_ENABLE,
			PermissionsEnum.PLUGIN_DISABLE,
			PermissionsEnum.PLUGIN_CONFIGURE,
			PermissionsEnum.PLUGIN_PUBLISH,
			PermissionsEnum.PLUGIN_RESTRICT,
			PermissionsEnum.PLUGIN_DELETE,
			PermissionsEnum.PLUGIN_DELETE_FOREVER,
			PermissionsEnum.PLUGIN_ASSIGN_ACCESS,
			/** Commerce Permissions Start */
			/** Platform: channels, regions, rules, numbering, operations, outbox, idempotency */
			PermissionsEnum.CHANNELS_VIEW,
			PermissionsEnum.CHANNELS_CREATE,
			PermissionsEnum.CHANNELS_EDIT,
			PermissionsEnum.CHANNELS_DELETE,
			PermissionsEnum.REGIONS_VIEW,
			PermissionsEnum.REGIONS_CREATE,
			PermissionsEnum.REGIONS_EDIT,
			PermissionsEnum.REGIONS_DELETE,
			PermissionsEnum.RULES_VIEW,
			PermissionsEnum.RULES_EDIT,
			PermissionsEnum.SEQUENCES_VIEW,
			PermissionsEnum.SEQUENCES_EDIT,
			PermissionsEnum.OPERATIONS_VIEW,
			PermissionsEnum.OPERATIONS_CANCEL,
			PermissionsEnum.EVENT_OUTBOX_VIEW,
			PermissionsEnum.EVENT_OUTBOX_RETRY,
			PermissionsEnum.IDEMPOTENCY_KEYS_VIEW,
			PermissionsEnum.IDEMPOTENCY_KEYS_DELETE,
			PermissionsEnum.UNITS_VIEW,
			PermissionsEnum.UNITS_EDIT,
			PermissionsEnum.PAYMENT_TERMS_VIEW,
			PermissionsEnum.PAYMENT_TERMS_EDIT,
			/** Catalog */
			PermissionsEnum.PRODUCTS_VIEW,
			PermissionsEnum.PRODUCTS_EDIT,
			PermissionsEnum.PRODUCTS_DELETE,
			PermissionsEnum.PRODUCTS_BULK_IMPORT,
			PermissionsEnum.COLLECTIONS_VIEW,
			PermissionsEnum.COLLECTIONS_CREATE,
			PermissionsEnum.COLLECTIONS_EDIT,
			PermissionsEnum.COLLECTIONS_DELETE,
			/** Pricing and currency */
			PermissionsEnum.PRICE_LISTS_VIEW,
			PermissionsEnum.PRICE_LISTS_CREATE,
			PermissionsEnum.PRICE_LISTS_EDIT,
			PermissionsEnum.PRICE_LISTS_DELETE,
			PermissionsEnum.PRICE_LISTS_SIMULATE,
			PermissionsEnum.PRODUCT_PRICES_VIEW,
			PermissionsEnum.PRODUCT_PRICES_EDIT,
			PermissionsEnum.PRODUCT_PRICES_BULK_EDIT,
			PermissionsEnum.EXCHANGE_RATES_VIEW,
			PermissionsEnum.EXCHANGE_RATES_EDIT,
			/** Tax */
			PermissionsEnum.TAX_CATEGORIES_VIEW,
			PermissionsEnum.TAX_CATEGORIES_EDIT,
			PermissionsEnum.TAX_RATES_VIEW,
			PermissionsEnum.TAX_RATES_EDIT,
			PermissionsEnum.TAX_REGIMES_VIEW,
			PermissionsEnum.TAX_REGIMES_EDIT,
			/** Contacts, groups, credentials and credit */
			PermissionsEnum.CONTACT_GROUPS_VIEW,
			PermissionsEnum.CONTACT_GROUPS_CREATE,
			PermissionsEnum.CONTACT_GROUPS_EDIT,
			PermissionsEnum.CONTACT_GROUPS_DELETE,
			PermissionsEnum.CONTACT_CREDENTIALS_VIEW,
			PermissionsEnum.CONTACT_CREDENTIALS_MANAGE,
			PermissionsEnum.CONTACT_CREDITS_EDIT,
			PermissionsEnum.CONTACT_TAX_IDENTITY_EDIT,
			/** Stock */
			PermissionsEnum.STOCK_VIEW,
			PermissionsEnum.STOCK_EDIT,
			PermissionsEnum.STOCK_RECONCILE,
			PermissionsEnum.STOCK_TRANSFER_VIEW,
			PermissionsEnum.STOCK_TRANSFER_CREATE,
			PermissionsEnum.STOCK_TRANSFER_APPROVE,
			PermissionsEnum.STOCK_TRANSFER_SHIP,
			PermissionsEnum.STOCK_TRANSFER_RECEIVE,
			PermissionsEnum.STOCK_TRANSFER_CANCEL,
			/** Warehouse */
			PermissionsEnum.WAREHOUSE_ZONES_VIEW,
			PermissionsEnum.WAREHOUSE_ZONES_CREATE,
			PermissionsEnum.WAREHOUSE_ZONES_EDIT,
			PermissionsEnum.WAREHOUSE_ZONES_DELETE,
			PermissionsEnum.WAREHOUSE_BINS_VIEW,
			PermissionsEnum.WAREHOUSE_BINS_CREATE,
			PermissionsEnum.WAREHOUSE_BINS_EDIT,
			PermissionsEnum.WAREHOUSE_BINS_DELETE,
			PermissionsEnum.PICK_LISTS_VIEW,
			PermissionsEnum.PICK_LISTS_EDIT,
			PermissionsEnum.PICK_LISTS_PICK,
			PermissionsEnum.PICK_LISTS_CANCEL,
			/** Fulfilment and shipping */
			PermissionsEnum.FULFILLMENTS_VIEW,
			PermissionsEnum.FULFILLMENTS_CREATE,
			PermissionsEnum.FULFILLMENTS_EDIT,
			PermissionsEnum.SHIPPING_OPTIONS_VIEW,
			PermissionsEnum.SHIPPING_OPTIONS_CREATE,
			PermissionsEnum.SHIPPING_OPTIONS_EDIT,
			PermissionsEnum.SHIPPING_OPTIONS_DELETE,
			/** Returns, claims and exchanges */
			PermissionsEnum.RETURNS_VIEW,
			PermissionsEnum.RETURNS_CREATE,
			PermissionsEnum.RETURNS_APPROVE,
			PermissionsEnum.RETURNS_REJECT,
			PermissionsEnum.RETURNS_RECEIVE,
			PermissionsEnum.CLAIMS_VIEW,
			PermissionsEnum.CLAIMS_CREATE,
			PermissionsEnum.CLAIMS_RESOLVE,
			PermissionsEnum.EXCHANGES_VIEW,
			PermissionsEnum.EXCHANGES_CREATE,
			PermissionsEnum.EXCHANGES_RESOLVE,
			/** Orders */
			PermissionsEnum.ORDERS_VIEW,
			PermissionsEnum.ORDERS_CREATE,
			PermissionsEnum.ORDERS_EDIT,
			PermissionsEnum.ORDERS_CANCEL,
			PermissionsEnum.ORDERS_APPROVE,
			/** Carts and checkout */
			PermissionsEnum.CARTS_VIEW,
			PermissionsEnum.CARTS_EDIT,
			PermissionsEnum.CARTS_DELETE,
			PermissionsEnum.CARTS_CHECKOUT,
			/** Promotions, coupons and gift cards */
			PermissionsEnum.PROMOTIONS_VIEW,
			PermissionsEnum.PROMOTIONS_CREATE,
			PermissionsEnum.PROMOTIONS_EDIT,
			PermissionsEnum.PROMOTIONS_DELETE,
			PermissionsEnum.PROMOTIONS_SIMULATE,
			PermissionsEnum.COUPONS_VIEW,
			PermissionsEnum.COUPONS_CREATE,
			PermissionsEnum.COUPONS_EDIT,
			PermissionsEnum.COUPONS_DELETE,
			PermissionsEnum.GIFT_CARDS_VIEW,
			PermissionsEnum.GIFT_CARDS_ISSUE,
			PermissionsEnum.GIFT_CARDS_EDIT,
			/** Payments, refunds and provider callbacks */
			PermissionsEnum.PAYMENT_PROVIDERS_VIEW,
			PermissionsEnum.PAYMENT_PROVIDERS_CREATE,
			PermissionsEnum.PAYMENT_PROVIDERS_EDIT,
			PermissionsEnum.PAYMENT_PROVIDERS_DELETE,
			PermissionsEnum.PAYMENT_SESSIONS_VIEW,
			PermissionsEnum.PAYMENT_SESSIONS_AUTHORIZE,
			PermissionsEnum.PAYMENT_SESSIONS_CAPTURE,
			PermissionsEnum.PAYMENT_SESSIONS_CANCEL,
			PermissionsEnum.REFUNDS_VIEW,
			PermissionsEnum.REFUNDS_CREATE,
			PermissionsEnum.REFUNDS_APPROVE,
			PermissionsEnum.PAYMENT_CALLBACKS_VIEW,
			PermissionsEnum.PAYMENT_CALLBACKS_REPROCESS,
			PermissionsEnum.PAYMENT_ACCOUNT_HOLDERS_VIEW,
			PermissionsEnum.PAYMENT_ACCOUNT_HOLDERS_EDIT,
			PermissionsEnum.PAYMENT_METHOD_TOKENS_VIEW,
			PermissionsEnum.PAYMENT_METHOD_TOKENS_EDIT,
			PermissionsEnum.PAYMENT_METHOD_TOKENS_CHARGE,
			/** Subscriptions */
			PermissionsEnum.SUBSCRIPTIONS_VIEW,
			PermissionsEnum.SUBSCRIPTIONS_CREATE,
			PermissionsEnum.SUBSCRIPTIONS_EDIT,
			PermissionsEnum.SUBSCRIPTIONS_BILL,
			/** Purchasing */
			PermissionsEnum.PURCHASE_ORDERS_VIEW,
			PermissionsEnum.PURCHASE_ORDERS_CREATE,
			PermissionsEnum.PURCHASE_ORDERS_EDIT,
			PermissionsEnum.PURCHASE_ORDERS_APPROVE,
			PermissionsEnum.PURCHASE_ORDERS_SEND,
			PermissionsEnum.GOODS_RECEIPTS_VIEW,
			PermissionsEnum.GOODS_RECEIPTS_CREATE,
			PermissionsEnum.VENDOR_TERMS_VIEW,
			PermissionsEnum.VENDOR_TERMS_EDIT,
			/** Entitlements */
			PermissionsEnum.ENTITLEMENTS_VIEW,
			PermissionsEnum.ENTITLEMENTS_GRANT,
			PermissionsEnum.ENTITLEMENTS_EDIT,
			/** Marketplace */
			PermissionsEnum.SELLERS_VIEW,
			PermissionsEnum.SELLERS_CREATE,
			PermissionsEnum.SELLERS_EDIT,
			PermissionsEnum.SELLERS_DELETE,
			PermissionsEnum.SELLER_PAYOUTS_VIEW,
			PermissionsEnum.SELLER_PAYOUTS_CREATE,
			PermissionsEnum.SELLER_PAYOUTS_APPROVE,
			PermissionsEnum.SELLER_PAYOUTS_CANCEL,
			/** Search */
			PermissionsEnum.SEARCH_VIEW,
			PermissionsEnum.SEARCH_REINDEX,
			/** Webhooks */
			PermissionsEnum.WEBHOOKS_VIEW,
			PermissionsEnum.WEBHOOKS_CREATE,
			PermissionsEnum.WEBHOOKS_EDIT,
			PermissionsEnum.WEBHOOKS_DELETE,
			PermissionsEnum.WEBHOOK_DELIVERIES_RETRY,
			/** Sub-capabilities the plugin catalogues declare on top of the pairs above */
			PermissionsEnum.SELLER_OFFERINGS_VIEW,
			PermissionsEnum.SELLER_OFFERINGS_EDIT,
			PermissionsEnum.SELLER_COMMISSIONS_VIEW,
			PermissionsEnum.SELLER_COMMISSIONS_EDIT,
			PermissionsEnum.SELLER_TRANSACTIONS_VIEW,
			PermissionsEnum.SELLER_TRANSACTIONS_SETTLE,
			PermissionsEnum.SELLER_SETTLEMENTS_VIEW,
			PermissionsEnum.SELLER_SETTLEMENTS_EDIT,
			PermissionsEnum.SEARCH_INDEX_DEFINITIONS_VIEW,
			PermissionsEnum.SEARCH_INDEX_DEFINITIONS_EDIT
,
			/** Platform: channels, regions, rules, numbering, operations, outbox, idempotency */
			PermissionsEnum.PROVIDERS_VIEW
			/** Commerce Permissions End */
		]
	},
	{
		role: RolesEnum.ADMIN,
		defaultEnabledPermissions: [
			PermissionsEnum.ADMIN_DASHBOARD_VIEW,
			PermissionsEnum.TEAM_DASHBOARD,
			PermissionsEnum.PROJECT_MANAGEMENT_DASHBOARD,
			PermissionsEnum.TIME_TRACKING_DASHBOARD,
			PermissionsEnum.ACCOUNTING_DASHBOARD,
			PermissionsEnum.HUMAN_RESOURCE_DASHBOARD,
			PermissionsEnum.ORG_PAYMENT_VIEW,
			PermissionsEnum.ORG_PAYMENT_ADD_EDIT,
			PermissionsEnum.ORG_INCOMES_VIEW,
			PermissionsEnum.ORG_INCOMES_EDIT,
			/** Payroll Permissions Start */
			PermissionsEnum.ORG_PAYROLL_VIEW,
			PermissionsEnum.ORG_PAYROLL_EDIT,
			PermissionsEnum.ORG_PAYROLL_APPROVE,
			/** Payroll Permissions End */
			PermissionsEnum.ORG_EXPENSES_VIEW,
			PermissionsEnum.ORG_EXPENSES_EDIT,
			PermissionsEnum.EMPLOYEE_EXPENSES_VIEW,
			PermissionsEnum.EMPLOYEE_EXPENSES_EDIT,
			PermissionsEnum.ORG_PROPOSALS_VIEW,
			PermissionsEnum.ORG_PROPOSALS_EDIT,
			PermissionsEnum.ORG_PROPOSAL_TEMPLATES_VIEW,
			PermissionsEnum.ORG_PROPOSAL_TEMPLATES_EDIT,
			PermissionsEnum.ORG_TASK_ADD,
			PermissionsEnum.ORG_TASK_VIEW,
			PermissionsEnum.ORG_TASK_EDIT,
			PermissionsEnum.ORG_TASK_DELETE,
			PermissionsEnum.SELECT_EMPLOYEE,
			/** Organization Task Setting */
			PermissionsEnum.ORG_TASK_SETTING,
			/** Employee CRUD Permissions Start */
			PermissionsEnum.ORG_EMPLOYEES_ADD,
			PermissionsEnum.ORG_EMPLOYEES_VIEW,
			PermissionsEnum.ORG_EMPLOYEES_EDIT,
			PermissionsEnum.ORG_EMPLOYEES_DELETE,
			/** Employee CRUD Permissions End */
			/** Member View Permissions Start */
			PermissionsEnum.ORG_MEMBERS_VIEW,
			/** Member View Permissions End */
			PermissionsEnum.ORG_EMPLOYEES_EDIT,
			PermissionsEnum.ORG_CANDIDATES_VIEW,
			PermissionsEnum.ORG_CANDIDATES_EDIT,
			PermissionsEnum.ORG_CANDIDATES_TASK_EDIT,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEW_EDIT,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEW_VIEW,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEWERS_EDIT,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEWERS_VIEW,
			PermissionsEnum.ORG_INVENTORY_VIEW,
			PermissionsEnum.ORG_INVENTORY_PRODUCT_EDIT,
			PermissionsEnum.ORG_CANDIDATES_DOCUMENTS_VIEW,
			PermissionsEnum.ORG_HELP_CENTER_EDIT,
			PermissionsEnum.ORG_USERS_VIEW,
			PermissionsEnum.ORG_USERS_EDIT,
			PermissionsEnum.ALL_ORG_VIEW,
			PermissionsEnum.ALL_ORG_EDIT,
			/** Equipment Sharing Policy Permissions Start */
			PermissionsEnum.EQUIPMENT_SHARING_POLICY_ADD,
			PermissionsEnum.EQUIPMENT_SHARING_POLICY_VIEW,
			PermissionsEnum.EQUIPMENT_SHARING_POLICY_EDIT,
			PermissionsEnum.EQUIPMENT_SHARING_POLICY_DELETE,
			/** Equipment Sharing Policy Permissions End */
			PermissionsEnum.APPROVAL_POLICY_EDIT,
			PermissionsEnum.APPROVAL_POLICY_VIEW,
			PermissionsEnum.REQUEST_APPROVAL_EDIT,
			PermissionsEnum.REQUEST_APPROVAL_VIEW,
			/** Time Off Permissions Start */
			PermissionsEnum.TIME_OFF_ADD,
			PermissionsEnum.TIME_OFF_VIEW,
			PermissionsEnum.TIME_OFF_EDIT,
			PermissionsEnum.TIME_OFF_DELETE,
			/** Time Off Permissions End */
			PermissionsEnum.CHANGE_SELECTED_EMPLOYEE,
			PermissionsEnum.CHANGE_SELECTED_CANDIDATE,
			PermissionsEnum.CHANGE_SELECTED_ORGANIZATION,
			PermissionsEnum.CHANGE_ROLES_PERMISSIONS,
			PermissionsEnum.ORG_INVITE_VIEW,
			PermissionsEnum.ORG_INVITE_EDIT,
			PermissionsEnum.ACCESS_PRIVATE_PROJECTS,
			PermissionsEnum.TIMESHEET_EDIT_TIME,
			PermissionsEnum.PUBLIC_PAGE_EDIT,
			PermissionsEnum.INVOICES_VIEW,
			PermissionsEnum.INVOICES_EDIT,
			PermissionsEnum.ESTIMATES_VIEW,
			PermissionsEnum.ESTIMATES_EDIT,
			PermissionsEnum.ORG_CANDIDATES_FEEDBACK_EDIT,
			/** Tags Permissions Start */
			PermissionsEnum.ORG_TAGS_ADD,
			PermissionsEnum.ORG_TAGS_VIEW,
			PermissionsEnum.ORG_TAGS_EDIT,
			PermissionsEnum.ORG_TAGS_DELETE,
			/** Tags Permissions End */
			/** Tags Types Permissions Start */
			PermissionsEnum.ORG_TAG_TYPES_ADD,
			PermissionsEnum.ORG_TAG_TYPES_VIEW,
			PermissionsEnum.ORG_TAG_TYPES_EDIT,
			PermissionsEnum.ORG_TAG_TYPES_DELETE,
			/** Tags Types Permissions End */
			PermissionsEnum.VIEW_ALL_EMAILS,
			PermissionsEnum.VIEW_ALL_EMAIL_TEMPLATES,
			PermissionsEnum.VIEW_SALES_PIPELINES,
			PermissionsEnum.EDIT_SALES_PIPELINES,
			PermissionsEnum.CAN_APPROVE_TIMESHEET,
			PermissionsEnum.ORG_SPRINT_ADD,
			PermissionsEnum.ORG_SPRINT_EDIT,
			PermissionsEnum.ORG_SPRINT_VIEW,
			PermissionsEnum.ORG_SPRINT_DELETE,
			PermissionsEnum.ORG_PROJECT_ADD,
			PermissionsEnum.ORG_PROJECT_VIEW,
			PermissionsEnum.ORG_PROJECT_EDIT,
			PermissionsEnum.ORG_PROJECT_DELETE,
			PermissionsEnum.ORG_CONTACT_EDIT,
			PermissionsEnum.ORG_CONTACT_VIEW,

			/** Daily CRUD Permissions Start */
			PermissionsEnum.DAILY_PLAN_CREATE,
			PermissionsEnum.DAILY_PLAN_READ,
			PermissionsEnum.DAILY_PLAN_UPDATE,
			PermissionsEnum.DAILY_PLAN_DELETE,
			/** Daily CRUD Permissions End */

			/** Project Module Permissions start */
			PermissionsEnum.PROJECT_MODULE_CREATE,
			PermissionsEnum.PROJECT_MODULE_READ,
			PermissionsEnum.PROJECT_MODULE_UPDATE,
			PermissionsEnum.PROJECT_MODULE_DELETE,
			/** Project Module Permissions end */

			/** Dashboard Permissions Start */
			PermissionsEnum.DASHBOARD_CREATE,
			PermissionsEnum.DASHBOARD_READ,
			PermissionsEnum.DASHBOARD_UPDATE,
			PermissionsEnum.DASHBOARD_DELETE,
			/** Dashboard Permissions End */

			/** Organization Team */
			PermissionsEnum.ORG_TEAM_ADD,
			PermissionsEnum.ORG_TEAM_VIEW,
			PermissionsEnum.ORG_TEAM_EDIT,
			PermissionsEnum.ORG_TEAM_EDIT_ACTIVE_TASK,
			PermissionsEnum.ORG_TEAM_DELETE,
			PermissionsEnum.ORG_TEAM_REMOVE_ACCOUNT_AS_MEMBER,
			PermissionsEnum.ORG_TEAM_JOIN_REQUEST_VIEW,
			PermissionsEnum.ORG_TEAM_JOIN_REQUEST_EDIT,
			PermissionsEnum.ORG_CONTRACT_EDIT,
			PermissionsEnum.EVENT_TYPES_VIEW,
			PermissionsEnum.TENANT_ADD_EXISTING_USER,

			/** Integration CRUD Permissions Start */
			PermissionsEnum.INTEGRATION_ADD,
			PermissionsEnum.INTEGRATION_VIEW,
			PermissionsEnum.INTEGRATION_EDIT,
			PermissionsEnum.INTEGRATION_DELETE,
			/** Integration CRUD Permissions End */

			/** AI Chat Permissions Start */
			PermissionsEnum.AI_CHAT_ACCESS,
			PermissionsEnum.AI_CHAT_SETTINGS,
			/** AI Chat Permissions End */

			/** Documents Permissions Start */
			PermissionsEnum.DOCS_READ,
			PermissionsEnum.DOCS_CREATE,
			PermissionsEnum.DOCS_UPDATE,
			PermissionsEnum.DOCS_DELETE,
			PermissionsEnum.DOCS_MANAGE,
			PermissionsEnum.DOCS_REVIEW,
			PermissionsEnum.DOCS_AI_IMPORT,
			/** Documents Permissions End */

			PermissionsEnum.IMPORT_ADD,
			PermissionsEnum.EXPORT_ADD,
			PermissionsEnum.FILE_STORAGE_VIEW,
			PermissionsEnum.PAYMENT_GATEWAY_VIEW,
			PermissionsEnum.SMS_GATEWAY_VIEW,
			PermissionsEnum.CUSTOM_SMTP_VIEW,
			/** Job Post Permissions Start */
			PermissionsEnum.ORG_JOB_EMPLOYEE_VIEW,
			PermissionsEnum.ORG_JOB_MATCHING_VIEW,
			PermissionsEnum.ORG_JOB_SEARCH,
			PermissionsEnum.ORG_JOB_APPLY,
			PermissionsEnum.ORG_JOB_EDIT,
			/** Job Post Permissions End */
			PermissionsEnum.ORG_EQUIPMENT_VIEW,
			PermissionsEnum.ORG_EQUIPMENT_EDIT,
			PermissionsEnum.ORG_EQUIPMENT_SHARING_VIEW,
			PermissionsEnum.ORG_EQUIPMENT_SHARING_EDIT,
			PermissionsEnum.EQUIPMENT_MAKE_REQUEST,
			PermissionsEnum.EQUIPMENT_APPROVE_REQUEST,
			PermissionsEnum.ORG_PRODUCT_TYPES_VIEW,
			PermissionsEnum.ORG_PRODUCT_TYPES_EDIT,
			PermissionsEnum.ORG_PRODUCT_CATEGORIES_VIEW,
			PermissionsEnum.ORG_PRODUCT_CATEGORIES_EDIT,
			PermissionsEnum.VIEW_ALL_ACCOUNTING_TEMPLATES,
			PermissionsEnum.MIGRATE_GAUZY_CLOUD,
			PermissionsEnum.INVENTORY_GALLERY_ADD,
			PermissionsEnum.INVENTORY_GALLERY_VIEW,
			PermissionsEnum.INVENTORY_GALLERY_EDIT,
			PermissionsEnum.INVENTORY_GALLERY_DELETE,
			PermissionsEnum.MEDIA_GALLERY_ADD,
			PermissionsEnum.MEDIA_GALLERY_VIEW,
			PermissionsEnum.MEDIA_GALLERY_EDIT,
			PermissionsEnum.MEDIA_GALLERY_DELETE,
			PermissionsEnum.ACCESS_DELETE_ACCOUNT,
			PermissionsEnum.ACCESS_DELETE_ALL_DATA,
			PermissionsEnum.PROFILE_EDIT,
			PermissionsEnum.TIME_TRACKER,
			PermissionsEnum.TENANT_SETTING,
			PermissionsEnum.ALLOW_DELETE_TIME,
			PermissionsEnum.ALLOW_MODIFY_TIME,
			PermissionsEnum.ALLOW_MANUAL_TIME,
			PermissionsEnum.DELETE_SCREENSHOTS,
			PermissionsEnum.ORG_MEMBER_LAST_LOG_VIEW,
			/** API Call Log */
			PermissionsEnum.API_CALL_LOG_READ,
			PermissionsEnum.API_CALL_LOG_DELETE,
			/** Tenant API Key */
			PermissionsEnum.TENANT_API_KEY_CREATE,
			PermissionsEnum.TENANT_API_KEY_VIEW,
			PermissionsEnum.TENANT_API_KEY_DELETE,
			/** OAuth App Client Registry (multi-app OAuth provider) */
			PermissionsEnum.OAUTH_CLIENT_VIEW,
			PermissionsEnum.OAUTH_CLIENT_EDIT,
			/** Employee Availability */
			PermissionsEnum.EMPLOYEE_AVAILABILITY_CREATE,
			PermissionsEnum.EMPLOYEE_AVAILABILITY_READ,
			PermissionsEnum.EMPLOYEE_AVAILABILITY_UPDATE,
			PermissionsEnum.EMPLOYEE_AVAILABILITY_DELETE,
			/** Broadcast Permissions Start */
			PermissionsEnum.BROADCAST_CREATE,
			PermissionsEnum.BROADCAST_READ,
			PermissionsEnum.BROADCAST_UPDATE,
			PermissionsEnum.BROADCAST_DELETE,
			/** Broadcast Permissions End */
			/** Organization Strategic Initiative Permissions Start */
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_CREATE,
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_READ,
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_UPDATE,
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_DELETE,
			/** Organization Strategic Initiative Permissions End */
			// Plugin permissions
			PermissionsEnum.PLUGIN_VIEW,
			PermissionsEnum.PLUGIN_DISCOVER,
			PermissionsEnum.PLUGIN_INSTALL,
			PermissionsEnum.PLUGIN_UNINSTALL,
			PermissionsEnum.PLUGIN_UPDATE,
			PermissionsEnum.PLUGIN_ENABLE,
			PermissionsEnum.PLUGIN_DISABLE,
			PermissionsEnum.PLUGIN_CONFIGURE,
			PermissionsEnum.PLUGIN_PUBLISH,
			PermissionsEnum.PLUGIN_RESTRICT,
			PermissionsEnum.PLUGIN_ASSIGN_ACCESS,
			PermissionsEnum.PLUGIN_DELETE,
			PermissionsEnum.PLUGIN_DELETE_FOREVER,
			/** Commerce Permissions Start */
			/** Platform: channels, regions, rules, numbering, operations, outbox, idempotency */
			PermissionsEnum.CHANNELS_VIEW,
			PermissionsEnum.REGIONS_VIEW,
			PermissionsEnum.RULES_VIEW,
			PermissionsEnum.SEQUENCES_VIEW,
			PermissionsEnum.OPERATIONS_VIEW,
			PermissionsEnum.EVENT_OUTBOX_VIEW,
			PermissionsEnum.IDEMPOTENCY_KEYS_VIEW,
			PermissionsEnum.UNITS_VIEW,
			PermissionsEnum.PAYMENT_TERMS_VIEW,
			/** Catalog */
			PermissionsEnum.PRODUCTS_VIEW,
			PermissionsEnum.PRODUCTS_EDIT,
			PermissionsEnum.PRODUCTS_DELETE,
			PermissionsEnum.COLLECTIONS_VIEW,
			PermissionsEnum.COLLECTIONS_CREATE,
			PermissionsEnum.COLLECTIONS_EDIT,
			PermissionsEnum.COLLECTIONS_DELETE,
			/** Pricing and currency */
			PermissionsEnum.PRICE_LISTS_VIEW,
			PermissionsEnum.PRICE_LISTS_CREATE,
			PermissionsEnum.PRICE_LISTS_EDIT,
			PermissionsEnum.PRICE_LISTS_DELETE,
			PermissionsEnum.PRICE_LISTS_SIMULATE,
			PermissionsEnum.PRODUCT_PRICES_VIEW,
			PermissionsEnum.PRODUCT_PRICES_EDIT,
			PermissionsEnum.EXCHANGE_RATES_VIEW,
			/** Tax */
			PermissionsEnum.TAX_CATEGORIES_VIEW,
			PermissionsEnum.TAX_CATEGORIES_EDIT,
			PermissionsEnum.TAX_RATES_VIEW,
			PermissionsEnum.TAX_RATES_EDIT,
			PermissionsEnum.TAX_REGIMES_VIEW,
			/** Contacts, groups, credentials and credit */
			PermissionsEnum.CONTACT_GROUPS_VIEW,
			PermissionsEnum.CONTACT_GROUPS_CREATE,
			PermissionsEnum.CONTACT_GROUPS_EDIT,
			PermissionsEnum.CONTACT_GROUPS_DELETE,
			PermissionsEnum.CONTACT_CREDENTIALS_VIEW,
			/** Stock */
			PermissionsEnum.STOCK_VIEW,
			PermissionsEnum.STOCK_EDIT,
			PermissionsEnum.STOCK_TRANSFER_VIEW,
			PermissionsEnum.STOCK_TRANSFER_CREATE,
			PermissionsEnum.STOCK_TRANSFER_APPROVE,
			PermissionsEnum.STOCK_TRANSFER_SHIP,
			PermissionsEnum.STOCK_TRANSFER_RECEIVE,
			PermissionsEnum.STOCK_TRANSFER_CANCEL,
			/** Warehouse */
			PermissionsEnum.WAREHOUSE_ZONES_VIEW,
			PermissionsEnum.WAREHOUSE_ZONES_CREATE,
			PermissionsEnum.WAREHOUSE_ZONES_EDIT,
			PermissionsEnum.WAREHOUSE_ZONES_DELETE,
			PermissionsEnum.WAREHOUSE_BINS_VIEW,
			PermissionsEnum.WAREHOUSE_BINS_CREATE,
			PermissionsEnum.WAREHOUSE_BINS_EDIT,
			PermissionsEnum.WAREHOUSE_BINS_DELETE,
			PermissionsEnum.PICK_LISTS_VIEW,
			PermissionsEnum.PICK_LISTS_EDIT,
			PermissionsEnum.PICK_LISTS_PICK,
			PermissionsEnum.PICK_LISTS_CANCEL,
			/** Fulfilment and shipping */
			PermissionsEnum.FULFILLMENTS_VIEW,
			PermissionsEnum.FULFILLMENTS_CREATE,
			PermissionsEnum.FULFILLMENTS_EDIT,
			PermissionsEnum.SHIPPING_OPTIONS_VIEW,
			PermissionsEnum.SHIPPING_OPTIONS_CREATE,
			PermissionsEnum.SHIPPING_OPTIONS_EDIT,
			PermissionsEnum.SHIPPING_OPTIONS_DELETE,
			/** Returns, claims and exchanges */
			PermissionsEnum.RETURNS_VIEW,
			PermissionsEnum.RETURNS_CREATE,
			PermissionsEnum.RETURNS_APPROVE,
			PermissionsEnum.RETURNS_REJECT,
			PermissionsEnum.RETURNS_RECEIVE,
			PermissionsEnum.CLAIMS_VIEW,
			PermissionsEnum.CLAIMS_CREATE,
			PermissionsEnum.CLAIMS_RESOLVE,
			PermissionsEnum.EXCHANGES_VIEW,
			PermissionsEnum.EXCHANGES_CREATE,
			PermissionsEnum.EXCHANGES_RESOLVE,
			/** Orders */
			PermissionsEnum.ORDERS_VIEW,
			PermissionsEnum.ORDERS_CREATE,
			PermissionsEnum.ORDERS_EDIT,
			PermissionsEnum.ORDERS_CANCEL,
			PermissionsEnum.ORDERS_APPROVE,
			/** Carts and checkout */
			PermissionsEnum.CARTS_VIEW,
			PermissionsEnum.CARTS_EDIT,
			PermissionsEnum.CARTS_DELETE,
			PermissionsEnum.CARTS_CHECKOUT,
			/** Promotions, coupons and gift cards */
			PermissionsEnum.PROMOTIONS_VIEW,
			PermissionsEnum.PROMOTIONS_CREATE,
			PermissionsEnum.PROMOTIONS_EDIT,
			PermissionsEnum.PROMOTIONS_DELETE,
			PermissionsEnum.PROMOTIONS_SIMULATE,
			PermissionsEnum.COUPONS_VIEW,
			PermissionsEnum.COUPONS_CREATE,
			PermissionsEnum.COUPONS_EDIT,
			PermissionsEnum.COUPONS_DELETE,
			PermissionsEnum.GIFT_CARDS_VIEW,
			PermissionsEnum.GIFT_CARDS_ISSUE,
			PermissionsEnum.GIFT_CARDS_EDIT,
			/** Payments, refunds and provider callbacks */
			PermissionsEnum.PAYMENT_PROVIDERS_VIEW,
			PermissionsEnum.PAYMENT_SESSIONS_VIEW,
			PermissionsEnum.PAYMENT_SESSIONS_AUTHORIZE,
			PermissionsEnum.PAYMENT_SESSIONS_CANCEL,
			PermissionsEnum.REFUNDS_VIEW,
			PermissionsEnum.REFUNDS_CREATE,
			PermissionsEnum.PAYMENT_CALLBACKS_VIEW,
			PermissionsEnum.PAYMENT_CALLBACKS_REPROCESS,
			PermissionsEnum.PAYMENT_ACCOUNT_HOLDERS_VIEW,
			PermissionsEnum.PAYMENT_METHOD_TOKENS_VIEW,
			PermissionsEnum.PAYMENT_METHOD_TOKENS_EDIT,
			/** Subscriptions */
			PermissionsEnum.SUBSCRIPTIONS_VIEW,
			PermissionsEnum.SUBSCRIPTIONS_CREATE,
			PermissionsEnum.SUBSCRIPTIONS_EDIT,
			PermissionsEnum.SUBSCRIPTIONS_BILL,
			/** Purchasing */
			PermissionsEnum.PURCHASE_ORDERS_VIEW,
			PermissionsEnum.PURCHASE_ORDERS_CREATE,
			PermissionsEnum.PURCHASE_ORDERS_EDIT,
			PermissionsEnum.PURCHASE_ORDERS_APPROVE,
			PermissionsEnum.PURCHASE_ORDERS_SEND,
			PermissionsEnum.GOODS_RECEIPTS_VIEW,
			PermissionsEnum.GOODS_RECEIPTS_CREATE,
			PermissionsEnum.VENDOR_TERMS_VIEW,
			PermissionsEnum.VENDOR_TERMS_EDIT,
			/** Entitlements */
			PermissionsEnum.ENTITLEMENTS_VIEW,
			PermissionsEnum.ENTITLEMENTS_GRANT,
			PermissionsEnum.ENTITLEMENTS_EDIT,
			/** Marketplace */
			PermissionsEnum.SELLERS_VIEW,
			PermissionsEnum.SELLERS_CREATE,
			PermissionsEnum.SELLERS_EDIT,
			PermissionsEnum.SELLERS_DELETE,
			PermissionsEnum.SELLER_PAYOUTS_VIEW,
			PermissionsEnum.SELLER_PAYOUTS_CREATE,
			PermissionsEnum.SELLER_PAYOUTS_CANCEL,
			/** Search */
			PermissionsEnum.SEARCH_VIEW,
			/** Webhooks */
			PermissionsEnum.WEBHOOKS_VIEW,
			PermissionsEnum.WEBHOOKS_CREATE,
			PermissionsEnum.WEBHOOKS_EDIT,
			PermissionsEnum.WEBHOOK_DELIVERIES_RETRY,
			/** Sub-capabilities the plugin catalogues declare on top of the pairs above */
			PermissionsEnum.SELLER_OFFERINGS_VIEW,
			PermissionsEnum.SELLER_OFFERINGS_EDIT,
			PermissionsEnum.SELLER_COMMISSIONS_VIEW,
			PermissionsEnum.SELLER_COMMISSIONS_EDIT,
			PermissionsEnum.SELLER_TRANSACTIONS_VIEW,
			PermissionsEnum.SELLER_TRANSACTIONS_SETTLE,
			PermissionsEnum.SELLER_SETTLEMENTS_VIEW,
			PermissionsEnum.SELLER_SETTLEMENTS_EDIT,
			PermissionsEnum.SEARCH_INDEX_DEFINITIONS_VIEW,
			PermissionsEnum.SEARCH_INDEX_DEFINITIONS_EDIT
,
			/** Platform: channels, regions, rules, numbering, operations, outbox, idempotency */
			PermissionsEnum.PROVIDERS_VIEW
			/** Commerce Permissions End */
		]
	},
	{
		role: RolesEnum.DATA_ENTRY,
		defaultEnabledPermissions: [
			PermissionsEnum.ORG_PAYMENT_VIEW,
			PermissionsEnum.ORG_PAYMENT_ADD_EDIT,
			PermissionsEnum.ORG_EXPENSES_EDIT,
			PermissionsEnum.ORG_EXPENSES_VIEW,
			PermissionsEnum.ORG_INCOMES_EDIT,
			PermissionsEnum.ORG_INCOMES_VIEW,
			PermissionsEnum.CHANGE_SELECTED_ORGANIZATION,
			PermissionsEnum.INVOICES_VIEW,
			PermissionsEnum.INVOICES_EDIT,
			PermissionsEnum.ESTIMATES_VIEW,
			PermissionsEnum.ESTIMATES_EDIT,
			PermissionsEnum.ORG_TASK_ADD,
			PermissionsEnum.ORG_TASK_VIEW,
			PermissionsEnum.ORG_TASK_EDIT,
			PermissionsEnum.ORG_TASK_DELETE,
			PermissionsEnum.PROJECT_MODULE_CREATE,
			PermissionsEnum.PROJECT_MODULE_READ,
			PermissionsEnum.PROJECT_MODULE_UPDATE,
			PermissionsEnum.PROJECT_MODULE_DELETE,
			PermissionsEnum.DASHBOARD_CREATE,
			PermissionsEnum.DASHBOARD_READ,
			PermissionsEnum.DASHBOARD_UPDATE,
			PermissionsEnum.DASHBOARD_DELETE,
			PermissionsEnum.ORG_CANDIDATES_TASK_EDIT,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEW_EDIT,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEW_VIEW,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEWERS_EDIT,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEWERS_VIEW,
			PermissionsEnum.ORG_INVENTORY_PRODUCT_EDIT,
			PermissionsEnum.ORG_HELP_CENTER_EDIT,
			PermissionsEnum.PROFILE_EDIT,
			PermissionsEnum.SELECT_EMPLOYEE,
			/** Documents Permissions Start */
			PermissionsEnum.DOCS_READ,
			PermissionsEnum.DOCS_CREATE,
			PermissionsEnum.DOCS_UPDATE,
			/** Documents Permissions End */
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_READ,
			PermissionsEnum.PLUGIN_VIEW,
			PermissionsEnum.PLUGIN_DISCOVER,
			PermissionsEnum.PLUGIN_CONFIGURE
		]
	},
	{
		role: RolesEnum.EMPLOYEE,
		defaultEnabledPermissions: [
			PermissionsEnum.ADMIN_DASHBOARD_VIEW,
			PermissionsEnum.PROJECT_MANAGEMENT_DASHBOARD,
			PermissionsEnum.TIME_TRACKING_DASHBOARD,
			PermissionsEnum.HUMAN_RESOURCE_DASHBOARD,
			PermissionsEnum.CHANGE_SELECTED_ORGANIZATION,
			PermissionsEnum.ORG_PROPOSALS_VIEW,
			PermissionsEnum.ORG_PROPOSALS_EDIT,
			PermissionsEnum.ORG_PROPOSAL_TEMPLATES_VIEW,
			PermissionsEnum.ORG_PROPOSAL_TEMPLATES_EDIT,
			PermissionsEnum.SELECT_EMPLOYEE,
			/** AI Chat Permissions Start */
			PermissionsEnum.AI_CHAT_ACCESS,
			/** AI Chat Permissions End */
			/** Documents Permissions Start */
			PermissionsEnum.DOCS_READ,
			PermissionsEnum.DOCS_CREATE,
			PermissionsEnum.DOCS_UPDATE,
			/** Documents Permissions End */
			/** Time Off Permissions Start */
			PermissionsEnum.TIME_OFF_VIEW,
			/** Time Off Permissions End */
			PermissionsEnum.ORG_INVITE_VIEW,
			PermissionsEnum.ORG_INVITE_EDIT,
			/** Equipment Sharing Policy Permissions Start */
			PermissionsEnum.EQUIPMENT_SHARING_POLICY_VIEW,
			/** Equipment Sharing Policy Permissions End */
			PermissionsEnum.APPROVAL_POLICY_EDIT,
			PermissionsEnum.APPROVAL_POLICY_VIEW,
			PermissionsEnum.REQUEST_APPROVAL_EDIT,
			PermissionsEnum.REQUEST_APPROVAL_VIEW,
			PermissionsEnum.ORG_TASK_ADD,
			PermissionsEnum.ORG_TASK_VIEW,
			PermissionsEnum.ORG_TASK_EDIT,
			/** Member View Permissions Start */
			PermissionsEnum.ORG_MEMBERS_VIEW,
			/** Member View Permissions End */
			PermissionsEnum.ORG_CANDIDATES_TASK_EDIT,
			PermissionsEnum.EVENT_TYPES_VIEW,
			PermissionsEnum.TIME_TRACKER,
			PermissionsEnum.INVOICES_VIEW,
			PermissionsEnum.INVOICES_EDIT,
			PermissionsEnum.ESTIMATES_VIEW,
			PermissionsEnum.ESTIMATES_EDIT,
			PermissionsEnum.ORG_CONTACT_VIEW,
			PermissionsEnum.ORG_PROJECT_ADD,
			PermissionsEnum.ORG_PROJECT_VIEW,
			/** Daily Plan */
			PermissionsEnum.DAILY_PLAN_CREATE,
			PermissionsEnum.DAILY_PLAN_READ,
			PermissionsEnum.DAILY_PLAN_UPDATE,
			PermissionsEnum.DAILY_PLAN_DELETE,
			/** Project Module */
			PermissionsEnum.PROJECT_MODULE_CREATE,
			PermissionsEnum.PROJECT_MODULE_READ,
			PermissionsEnum.PROJECT_MODULE_UPDATE,
			PermissionsEnum.PROJECT_MODULE_DELETE,
			/** Dashboard */
			PermissionsEnum.DASHBOARD_CREATE,
			PermissionsEnum.DASHBOARD_READ,
			PermissionsEnum.DASHBOARD_UPDATE,
			PermissionsEnum.DASHBOARD_DELETE,
			/** Organization Team */
			PermissionsEnum.ORG_TEAM_ADD,
			PermissionsEnum.ORG_TEAM_VIEW,
			PermissionsEnum.ORG_TEAM_EDIT,
			PermissionsEnum.ORG_TEAM_DELETE,
			PermissionsEnum.ORG_TEAM_EDIT_ACTIVE_TASK,
			PermissionsEnum.ORG_TEAM_REMOVE_ACCOUNT_AS_MEMBER,
			PermissionsEnum.ORG_TEAM_JOIN_REQUEST_VIEW,
			/** Tags Permissions Start */
			PermissionsEnum.ORG_TAGS_ADD,
			PermissionsEnum.ORG_TAGS_VIEW,
			PermissionsEnum.ORG_TAGS_EDIT,
			PermissionsEnum.ORG_TAGS_DELETE,
			/** Tags Permissions End */
			/** Tags Types Permissions Start */
			PermissionsEnum.ORG_TAG_TYPES_ADD,
			PermissionsEnum.ORG_TAG_TYPES_VIEW,
			PermissionsEnum.ORG_TAG_TYPES_EDIT,
			PermissionsEnum.ORG_TAG_TYPES_DELETE,
			/** Tags Types Permissions End */
			PermissionsEnum.EMPLOYEE_EXPENSES_VIEW,
			PermissionsEnum.EMPLOYEE_EXPENSES_EDIT,
			PermissionsEnum.INVENTORY_GALLERY_ADD,
			PermissionsEnum.INVENTORY_GALLERY_VIEW,
			PermissionsEnum.INVENTORY_GALLERY_EDIT,
			PermissionsEnum.INVENTORY_GALLERY_DELETE,
			PermissionsEnum.MEDIA_GALLERY_ADD,
			PermissionsEnum.MEDIA_GALLERY_VIEW,
			PermissionsEnum.MEDIA_GALLERY_EDIT,
			PermissionsEnum.MEDIA_GALLERY_DELETE,
			PermissionsEnum.ORG_INVENTORY_VIEW,
			PermissionsEnum.ORG_EQUIPMENT_VIEW,
			PermissionsEnum.ORG_EQUIPMENT_SHARING_VIEW,
			PermissionsEnum.EQUIPMENT_MAKE_REQUEST,
			PermissionsEnum.ORG_PRODUCT_TYPES_VIEW,
			PermissionsEnum.ORG_PRODUCT_CATEGORIES_VIEW,
			PermissionsEnum.ACCESS_DELETE_ACCOUNT,
			PermissionsEnum.PROFILE_EDIT,
			PermissionsEnum.ALLOW_DELETE_TIME,
			PermissionsEnum.ALLOW_MODIFY_TIME,
			PermissionsEnum.ALLOW_MANUAL_TIME,
			PermissionsEnum.DELETE_SCREENSHOTS,
			PermissionsEnum.ORG_MEMBER_LAST_LOG_VIEW,
			/** Employee Availability */
			PermissionsEnum.EMPLOYEE_AVAILABILITY_CREATE,
			PermissionsEnum.EMPLOYEE_AVAILABILITY_READ,
			PermissionsEnum.EMPLOYEE_AVAILABILITY_UPDATE,
			PermissionsEnum.EMPLOYEE_AVAILABILITY_DELETE,
			/** Broadcast Permissions Start */
			PermissionsEnum.BROADCAST_CREATE,
			PermissionsEnum.BROADCAST_READ,
			PermissionsEnum.BROADCAST_UPDATE,
			PermissionsEnum.BROADCAST_DELETE,
			/** Broadcast Permissions End */
			/** Organization Strategic Initiative Permissions Start */
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_READ,
			/** Organization Strategic Initiative Permissions End */
			// Plugin permissions
			PermissionsEnum.PLUGIN_VIEW,
			PermissionsEnum.PLUGIN_DISCOVER,
			PermissionsEnum.PLUGIN_INSTALL,
			PermissionsEnum.PLUGIN_UNINSTALL
		]
	},
	{
		role: RolesEnum.INTERVIEWER,
		defaultEnabledPermissions: [
			PermissionsEnum.ORG_CANDIDATES_INTERVIEW_EDIT,
			PermissionsEnum.ORG_CANDIDATES_INTERVIEW_VIEW,
			PermissionsEnum.ORG_CANDIDATES_DOCUMENTS_VIEW,
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_READ,
			PermissionsEnum.PLUGIN_VIEW
		]
	},
	{
		role: RolesEnum.CANDIDATE,
		defaultEnabledPermissions: [
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_READ,
			PermissionsEnum.PLUGIN_VIEW
		]
	},
	{
		role: RolesEnum.MANAGER,
		defaultEnabledPermissions: [
			/** Organization Strategic Initiative Permissions Start */
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_CREATE,
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_READ,
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_UPDATE,
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_DELETE,
			/** Organization Strategic Initiative Permissions End */
			/** Documents Permissions Start */
			PermissionsEnum.DOCS_READ,
			PermissionsEnum.DOCS_CREATE,
			PermissionsEnum.DOCS_UPDATE,
			PermissionsEnum.DOCS_DELETE,
			PermissionsEnum.DOCS_REVIEW,
			PermissionsEnum.DOCS_AI_IMPORT,
			/** Documents Permissions End */
			// Plugin permissions
			PermissionsEnum.PLUGIN_VIEW,
			PermissionsEnum.PLUGIN_DISCOVER,
			PermissionsEnum.PLUGIN_INSTALL,
			PermissionsEnum.PLUGIN_UNINSTALL,
			PermissionsEnum.PLUGIN_UPDATE,
			PermissionsEnum.PLUGIN_ENABLE,
			PermissionsEnum.PLUGIN_DISABLE,
			PermissionsEnum.PLUGIN_CONFIGURE,
			PermissionsEnum.PLUGIN_DELETE
		]
	},
	{
		role: RolesEnum.VIEWER,
		defaultEnabledPermissions: [
			PermissionsEnum.ORG_STRATEGIC_INITIATIVE_READ,
			/** Documents Permissions Start */
			PermissionsEnum.DOCS_READ,
			/** Documents Permissions End */
			PermissionsEnum.PLUGIN_VIEW,
			PermissionsEnum.PLUGIN_DISCOVER
		]
	}
];
