import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsDate, IsEmail, IsEnum, IsInt, IsObject, IsOptional, IsString, IsUUID, MaxLength, Min } from 'class-validator';
import { ID } from '@gauzy/contracts';
import { TenantOrganizationBaseDTO } from '@gauzy/core';
import { EntitlementKeyStatus, LicenceKeyFormat } from '../../entitlement.enums';

/**
 * An issued licence key as a caller sees it.
 *
 * The digest is never returned and the ciphertext never leaves the service: a caller reads the
 * prefix, the state and the holder, which is everything support needs to answer "which key does this
 * customer have" without the row being a working credential.
 */
export class EntitlementKeyDTO extends TenantOrganizationBaseDTO {
	@ApiPropertyOptional({ type: () => String })
	@IsOptional()
	@IsUUID()
	readonly entitlementId?: ID;

	@ApiPropertyOptional({ type: () => String, maxLength: 16, description: 'The leading characters, in clear.' })
	@IsOptional()
	@IsString()
	@MaxLength(16)
	readonly keyPrefix?: string;

	@ApiPropertyOptional({ type: () => String, maxLength: 64 })
	@IsOptional()
	@IsString()
	@MaxLength(64)
	readonly format?: string;

	@ApiPropertyOptional({ type: () => String, enum: EntitlementKeyStatus })
	@IsOptional()
	@IsEnum(EntitlementKeyStatus)
	readonly status?: EntitlementKeyStatus;

	@ApiPropertyOptional({ type: () => String, maxLength: 320 })
	@IsOptional()
	@IsEmail()
	@MaxLength(320)
	readonly assignedToEmail?: string;

	@ApiPropertyOptional({ type: () => String })
	@IsOptional()
	@IsUUID()
	readonly assignedToCustomerId?: ID;

	@ApiPropertyOptional({ type: () => Number, minimum: 0, description: 'Per-key override; null inherits.' })
	@IsOptional()
	@IsInt()
	@Min(0)
	readonly activationLimit?: number;

	@ApiPropertyOptional({ type: () => Date })
	@IsOptional()
	@IsDate()
	readonly expiresAt?: Date;

	@ApiPropertyOptional({ type: () => Object })
	@IsOptional()
	@IsObject()
	readonly metadata?: Record<string, unknown>;
}

/**
 * A request to issue a key.
 *
 * The plaintext is generated by the service and returned exactly once, in the response to this call;
 * a caller never supplies key material, because a key the caller chose is a key the caller already
 * knows and can reuse anywhere.
 */
export class CreateEntitlementKeyDTO extends EntitlementKeyDTO {
	@ApiPropertyOptional({ type: () => String })
	@IsOptional()
	@IsUUID()
	readonly entitlementId?: ID;

	@ApiPropertyOptional({ type: () => String, enum: LicenceKeyFormat, default: LicenceKeyFormat.UUID })
	@IsOptional()
	@IsEnum(LicenceKeyFormat)
	readonly format?: LicenceKeyFormat;

	@ApiPropertyOptional({
		type: () => Boolean,
		default: false,
		description: 'Store a recoverable ciphertext so an operator can re-display the key to its holder.'
	})
	@IsOptional()
	readonly storeKey?: boolean;
}
