import { test } from './support/fixtures';
import { getPage } from './support/page-context';
import * as loginPage from './support/pages/Login.po';
import { LoginPageData } from '../src/support/Base/pagedata/LoginPageData';
import * as dashboardPage from './support/pages/Dashboard.po';
import { CustomCommands } from './support/commands';
import { RolesPermissionsPageData } from '../src/support/Base/pagedata/RolesPermissionsPageData';
import * as rolesPermissionsPage from './support/pages/RolesPermissions.po';

let checked = 'be.checked';
let notChecked = 'not.checked';

test.describe('Roles and permissions test', () => {
	test('Roles and permissions test', async () => {
		await CustomCommands.login(loginPage, LoginPageData, dashboardPage);

		await test.step('Super admin roles and permissions', async () => {
			await getPage().goto('/#/pages/settings/roles-permissions');
			await rolesPermissionsPage.rolesDropdownVisible();
			await rolesPermissionsPage.clickRolesDropdown();
			await rolesPermissionsPage.rolesDropdownOptionVisible();
			await rolesPermissionsPage.selectRoleFromDropdown(RolesPermissionsPageData.superAdmin);
			// General
			await rolesPermissionsPage.verifyState(0, checked);
			await rolesPermissionsPage.verifyState(1, checked);
			await rolesPermissionsPage.verifyState(2, checked);
			await rolesPermissionsPage.verifyState(3, checked);
			await rolesPermissionsPage.verifyState(4, checked);
			await rolesPermissionsPage.verifyState(5, checked);
			await rolesPermissionsPage.verifyState(6, checked);
			await rolesPermissionsPage.verifyState(7, checked);
			await rolesPermissionsPage.verifyState(8, checked);
			await rolesPermissionsPage.verifyState(9, checked);
			await rolesPermissionsPage.verifyState(10, checked);
			await rolesPermissionsPage.verifyState(11, checked);
			await rolesPermissionsPage.verifyState(12, checked);
			await rolesPermissionsPage.verifyState(13, checked);
			await rolesPermissionsPage.verifyState(14, checked);
			await rolesPermissionsPage.verifyState(15, checked);
			await rolesPermissionsPage.verifyState(16, checked);
			await rolesPermissionsPage.verifyState(17, checked);
			await rolesPermissionsPage.verifyState(18, checked);
			await rolesPermissionsPage.verifyState(19, checked);
			await rolesPermissionsPage.verifyState(20, checked);
			await rolesPermissionsPage.verifyState(21, checked);
			await rolesPermissionsPage.verifyState(22, checked);
			await rolesPermissionsPage.verifyState(23, checked);
			await rolesPermissionsPage.verifyState(24, checked);
			await rolesPermissionsPage.verifyState(25, checked);
			await rolesPermissionsPage.verifyState(26, checked);
			await rolesPermissionsPage.verifyState(27, checked);
			await rolesPermissionsPage.verifyState(28, checked);
			await rolesPermissionsPage.verifyState(29, checked);
			await rolesPermissionsPage.verifyState(30, checked);
			await rolesPermissionsPage.verifyState(31, checked);
			await rolesPermissionsPage.verifyState(32, checked);
			await rolesPermissionsPage.verifyState(33, checked);
			await rolesPermissionsPage.verifyState(34, checked);
			await rolesPermissionsPage.verifyState(35, checked);
			await rolesPermissionsPage.verifyState(36, checked);
			await rolesPermissionsPage.verifyState(37, checked);
			await rolesPermissionsPage.verifyState(38, checked);
			await rolesPermissionsPage.verifyState(39, checked);
			await rolesPermissionsPage.verifyState(40, checked);
			await rolesPermissionsPage.verifyState(41, checked);
			await rolesPermissionsPage.verifyState(42, checked);
			await rolesPermissionsPage.verifyState(43, checked);
			await rolesPermissionsPage.verifyState(44, checked);
			await rolesPermissionsPage.verifyState(45, checked);
			await rolesPermissionsPage.verifyState(46, checked);
			await rolesPermissionsPage.verifyState(47, checked);
			await rolesPermissionsPage.verifyState(48, checked);
			await rolesPermissionsPage.verifyState(49, checked);
			await rolesPermissionsPage.verifyState(50, checked);
			await rolesPermissionsPage.verifyState(51, notChecked);
			await rolesPermissionsPage.verifyState(52, checked);
			// Administration
			await rolesPermissionsPage.verifyState(53, checked);
			await rolesPermissionsPage.verifyState(54, checked);
			await rolesPermissionsPage.verifyState(55, checked);
			await rolesPermissionsPage.verifyState(56, checked);
			await rolesPermissionsPage.verifyState(57, checked);
			await rolesPermissionsPage.verifyState(58, checked);
			await rolesPermissionsPage.verifyState(59, checked);
			await rolesPermissionsPage.verifyState(60, checked);
			await rolesPermissionsPage.verifyState(61, checked);
			await rolesPermissionsPage.verifyState(62, checked);
			await rolesPermissionsPage.verifyState(63, checked);
			await rolesPermissionsPage.verifyState(64, checked);
			await rolesPermissionsPage.verifyState(65, checked);
			await rolesPermissionsPage.verifyState(66, checked);
			await rolesPermissionsPage.verifyState(67, checked);
			await rolesPermissionsPage.verifyState(68, checked);
			await rolesPermissionsPage.verifyState(69, checked);
			await rolesPermissionsPage.verifyState(70, checked);
			await rolesPermissionsPage.verifyState(71, checked);
			await rolesPermissionsPage.verifyState(72, checked);
			await rolesPermissionsPage.verifyState(73, checked);
			await rolesPermissionsPage.verifyState(74, checked);
			await rolesPermissionsPage.verifyState(75, checked);
			await rolesPermissionsPage.verifyState(76, checked);
			await rolesPermissionsPage.verifyState(77, checked);
			await rolesPermissionsPage.verifyState(78, checked);
			await rolesPermissionsPage.verifyState(79, checked);
			await rolesPermissionsPage.verifyState(80, checked);
			await rolesPermissionsPage.verifyState(81, checked);
			await rolesPermissionsPage.verifyState(82, checked);
			await rolesPermissionsPage.verifyState(83, notChecked);
			await rolesPermissionsPage.verifyState(84, checked);
		});

		await test.step('Admin roles and permissions', async () => {
			await rolesPermissionsPage.clickRolesDropdown();
			await rolesPermissionsPage.rolesDropdownOptionVisible();
			await rolesPermissionsPage.selectRoleByIndex(1);
			// General
			await rolesPermissionsPage.verifyState(0, checked);
			await rolesPermissionsPage.verifyState(1, checked);
			await rolesPermissionsPage.verifyState(2, checked);
			await rolesPermissionsPage.verifyState(3, checked);
			await rolesPermissionsPage.verifyState(4, checked);
			await rolesPermissionsPage.verifyState(5, checked);
			await rolesPermissionsPage.verifyState(6, checked);
			await rolesPermissionsPage.verifyState(7, checked);
			await rolesPermissionsPage.verifyState(8, checked);
			await rolesPermissionsPage.verifyState(9, checked);
			await rolesPermissionsPage.verifyState(10, checked);
			await rolesPermissionsPage.verifyState(11, checked);
			await rolesPermissionsPage.verifyState(12, checked);
			await rolesPermissionsPage.verifyState(13, checked);
			await rolesPermissionsPage.verifyState(14, checked);
			await rolesPermissionsPage.verifyState(15, checked);
			await rolesPermissionsPage.verifyState(16, checked);
			await rolesPermissionsPage.verifyState(17, checked);
			await rolesPermissionsPage.verifyState(18, checked);
			await rolesPermissionsPage.verifyState(19, checked);
			await rolesPermissionsPage.verifyState(20, checked);
			await rolesPermissionsPage.verifyState(21, checked);
			await rolesPermissionsPage.verifyState(22, checked);
			await rolesPermissionsPage.verifyState(23, checked);
			await rolesPermissionsPage.verifyState(24, checked);
			await rolesPermissionsPage.verifyState(25, checked);
			await rolesPermissionsPage.verifyState(26, checked);
			await rolesPermissionsPage.verifyState(27, checked);
			await rolesPermissionsPage.verifyState(28, checked);
			await rolesPermissionsPage.verifyState(29, checked);
			await rolesPermissionsPage.verifyState(30, checked);
			await rolesPermissionsPage.verifyState(31, checked);
			await rolesPermissionsPage.verifyState(32, checked);
			await rolesPermissionsPage.verifyState(33, checked);
			await rolesPermissionsPage.verifyState(34, notChecked);
			await rolesPermissionsPage.verifyState(35, checked);
			await rolesPermissionsPage.verifyState(36, checked);
			await rolesPermissionsPage.verifyState(37, checked);
			await rolesPermissionsPage.verifyState(38, checked);
			await rolesPermissionsPage.verifyState(39, checked);
			await rolesPermissionsPage.verifyState(40, checked);
			await rolesPermissionsPage.verifyState(41, checked);
			await rolesPermissionsPage.verifyState(42, checked);
			await rolesPermissionsPage.verifyState(43, checked);
			await rolesPermissionsPage.verifyState(44, checked);
			await rolesPermissionsPage.verifyState(45, checked);
			await rolesPermissionsPage.verifyState(46, checked);
			await rolesPermissionsPage.verifyState(47, checked);
			await rolesPermissionsPage.verifyState(48, checked);
			await rolesPermissionsPage.verifyState(49, checked);
			await rolesPermissionsPage.verifyState(50, checked);
			await rolesPermissionsPage.verifyState(51, notChecked);
			await rolesPermissionsPage.verifyState(52, checked);
			// Administration
			await rolesPermissionsPage.verifyState(53, checked);
			await rolesPermissionsPage.verifyState(54, checked);
			await rolesPermissionsPage.verifyState(55, checked);
			await rolesPermissionsPage.verifyState(56, checked);
			await rolesPermissionsPage.verifyState(57, checked);
			await rolesPermissionsPage.verifyState(58, checked);
			await rolesPermissionsPage.verifyState(59, checked);
			await rolesPermissionsPage.verifyState(60, checked);
			await rolesPermissionsPage.verifyState(61, checked);
			await rolesPermissionsPage.verifyState(62, checked);
			await rolesPermissionsPage.verifyState(63, checked);
			await rolesPermissionsPage.verifyState(64, checked);
			await rolesPermissionsPage.verifyState(65, notChecked);
			await rolesPermissionsPage.verifyState(66, checked);
			await rolesPermissionsPage.verifyState(67, notChecked);
			await rolesPermissionsPage.verifyState(68, checked);
			await rolesPermissionsPage.verifyState(69, checked);
			await rolesPermissionsPage.verifyState(70, checked);
			await rolesPermissionsPage.verifyState(71, checked);
			await rolesPermissionsPage.verifyState(72, checked);
			await rolesPermissionsPage.verifyState(73, checked);
			await rolesPermissionsPage.verifyState(74, checked);
			await rolesPermissionsPage.verifyState(75, checked);
			await rolesPermissionsPage.verifyState(76, checked);
			await rolesPermissionsPage.verifyState(77, checked);
			await rolesPermissionsPage.verifyState(78, checked);
			await rolesPermissionsPage.verifyState(79, checked);
			await rolesPermissionsPage.verifyState(80, checked);
			await rolesPermissionsPage.verifyState(81, checked);
			await rolesPermissionsPage.verifyState(82, checked);
			await rolesPermissionsPage.verifyState(83, notChecked);
			await rolesPermissionsPage.verifyState(84, checked);
		});

		await test.step('Data Entry roles and permissions', async () => {
			await rolesPermissionsPage.clickRolesDropdown();
			await rolesPermissionsPage.rolesDropdownOptionVisible();
			await rolesPermissionsPage.selectRoleFromDropdown(RolesPermissionsPageData.dataEntry);
			// General
			await rolesPermissionsPage.verifyState(0, notChecked);
			await rolesPermissionsPage.verifyState(1, checked);
			await rolesPermissionsPage.verifyState(2, checked);
			await rolesPermissionsPage.verifyState(3, checked);
			await rolesPermissionsPage.verifyState(4, checked);
			await rolesPermissionsPage.verifyState(5, notChecked);
			await rolesPermissionsPage.verifyState(6, notChecked);
			await rolesPermissionsPage.verifyState(7, checked);
			await rolesPermissionsPage.verifyState(8, checked);
			await rolesPermissionsPage.verifyState(9, notChecked);
			await rolesPermissionsPage.verifyState(10, notChecked);
			await rolesPermissionsPage.verifyState(11, notChecked);
			await rolesPermissionsPage.verifyState(12, notChecked);
			await rolesPermissionsPage.verifyState(13, notChecked);
			await rolesPermissionsPage.verifyState(14, notChecked);
			await rolesPermissionsPage.verifyState(15, notChecked);
			await rolesPermissionsPage.verifyState(16, notChecked);
			await rolesPermissionsPage.verifyState(17, notChecked);
			await rolesPermissionsPage.verifyState(18, notChecked);
			await rolesPermissionsPage.verifyState(19, notChecked);
			await rolesPermissionsPage.verifyState(20, notChecked);
			await rolesPermissionsPage.verifyState(21, notChecked);
			await rolesPermissionsPage.verifyState(22, notChecked);
			await rolesPermissionsPage.verifyState(23, notChecked);
			await rolesPermissionsPage.verifyState(24, notChecked);
			await rolesPermissionsPage.verifyState(25, checked);
			await rolesPermissionsPage.verifyState(26, checked);
			await rolesPermissionsPage.verifyState(27, checked);
			await rolesPermissionsPage.verifyState(28, checked);
			await rolesPermissionsPage.verifyState(29, notChecked);
			await rolesPermissionsPage.verifyState(30, checked);
			await rolesPermissionsPage.verifyState(31, checked);
			await rolesPermissionsPage.verifyState(32, checked);
			await rolesPermissionsPage.verifyState(33, notChecked);
			await rolesPermissionsPage.verifyState(34, notChecked);
			await rolesPermissionsPage.verifyState(35, checked);
			await rolesPermissionsPage.verifyState(36, notChecked);
			await rolesPermissionsPage.verifyState(37, notChecked);
			await rolesPermissionsPage.verifyState(38, notChecked);
			await rolesPermissionsPage.verifyState(39, checked);
			await rolesPermissionsPage.verifyState(40, notChecked);
			await rolesPermissionsPage.verifyState(41, notChecked);
			await rolesPermissionsPage.verifyState(42, notChecked);
			await rolesPermissionsPage.verifyState(43, notChecked);
			await rolesPermissionsPage.verifyState(44, notChecked);
			await rolesPermissionsPage.verifyState(45, notChecked);
			await rolesPermissionsPage.verifyState(46, notChecked);
			await rolesPermissionsPage.verifyState(47, notChecked);
			await rolesPermissionsPage.verifyState(48, notChecked);
			await rolesPermissionsPage.verifyState(49, notChecked);
			await rolesPermissionsPage.verifyState(50, notChecked);
			await rolesPermissionsPage.verifyState(51, notChecked);
			await rolesPermissionsPage.verifyState(52, notChecked);
			// Administration
			await rolesPermissionsPage.verifyState(53, notChecked);
			await rolesPermissionsPage.verifyState(54, notChecked);
			await rolesPermissionsPage.verifyState(55, notChecked);
			await rolesPermissionsPage.verifyState(56, notChecked);
			await rolesPermissionsPage.verifyState(57, notChecked);
			await rolesPermissionsPage.verifyState(58, notChecked);
			await rolesPermissionsPage.verifyState(59, notChecked);
			await rolesPermissionsPage.verifyState(60, notChecked);
			await rolesPermissionsPage.verifyState(61, notChecked);
			await rolesPermissionsPage.verifyState(62, notChecked);
			await rolesPermissionsPage.verifyState(63, checked);
			await rolesPermissionsPage.verifyState(64, notChecked);
			await rolesPermissionsPage.verifyState(65, notChecked);
			await rolesPermissionsPage.verifyState(66, notChecked);
			await rolesPermissionsPage.verifyState(67, notChecked);
			await rolesPermissionsPage.verifyState(68, checked);
			await rolesPermissionsPage.verifyState(69, notChecked);
			await rolesPermissionsPage.verifyState(70, notChecked);
			await rolesPermissionsPage.verifyState(71, notChecked);
			await rolesPermissionsPage.verifyState(72, notChecked);
			await rolesPermissionsPage.verifyState(73, notChecked);
			await rolesPermissionsPage.verifyState(74, notChecked);
			await rolesPermissionsPage.verifyState(75, notChecked);
			await rolesPermissionsPage.verifyState(76, notChecked);
			await rolesPermissionsPage.verifyState(77, notChecked);
			await rolesPermissionsPage.verifyState(78, notChecked);
			await rolesPermissionsPage.verifyState(79, notChecked);
			await rolesPermissionsPage.verifyState(80, notChecked);
			await rolesPermissionsPage.verifyState(81, notChecked);
			await rolesPermissionsPage.verifyState(82, notChecked);
			await rolesPermissionsPage.verifyState(83, notChecked);
			await rolesPermissionsPage.verifyState(84, notChecked);
		});

		await test.step('Employee roles and permissions', async () => {
			await rolesPermissionsPage.clickRolesDropdown();
			await rolesPermissionsPage.rolesDropdownOptionVisible();
			await rolesPermissionsPage.selectRoleFromDropdown(RolesPermissionsPageData.employee);
			// General
			await rolesPermissionsPage.verifyState(0, checked);
			await rolesPermissionsPage.verifyState(1, notChecked);
			await rolesPermissionsPage.verifyState(2, notChecked);
			await rolesPermissionsPage.verifyState(3, notChecked);
			await rolesPermissionsPage.verifyState(4, notChecked);
			await rolesPermissionsPage.verifyState(5, checked);
			await rolesPermissionsPage.verifyState(6, checked);
			await rolesPermissionsPage.verifyState(7, notChecked);
			await rolesPermissionsPage.verifyState(8, notChecked);
			await rolesPermissionsPage.verifyState(9, checked);
			await rolesPermissionsPage.verifyState(10, checked);
			await rolesPermissionsPage.verifyState(11, checked);
			await rolesPermissionsPage.verifyState(12, checked);
			await rolesPermissionsPage.verifyState(13, checked);
			await rolesPermissionsPage.verifyState(14, notChecked);
			await rolesPermissionsPage.verifyState(15, notChecked);
			await rolesPermissionsPage.verifyState(16, notChecked);
			await rolesPermissionsPage.verifyState(17, notChecked);
			await rolesPermissionsPage.verifyState(18, notChecked);
			await rolesPermissionsPage.verifyState(19, checked);
			await rolesPermissionsPage.verifyState(20, checked);
			await rolesPermissionsPage.verifyState(21, checked);
			await rolesPermissionsPage.verifyState(22, checked);
			await rolesPermissionsPage.verifyState(23, notChecked);
			await rolesPermissionsPage.verifyState(24, notChecked);
			await rolesPermissionsPage.verifyState(25, checked);
			await rolesPermissionsPage.verifyState(26, checked);
			await rolesPermissionsPage.verifyState(27, checked);
			await rolesPermissionsPage.verifyState(28, checked);
			await rolesPermissionsPage.verifyState(29, notChecked);
			await rolesPermissionsPage.verifyState(30, checked);
			await rolesPermissionsPage.verifyState(31, notChecked);
			await rolesPermissionsPage.verifyState(32, notChecked);
			await rolesPermissionsPage.verifyState(33, notChecked);
			await rolesPermissionsPage.verifyState(34, checked);
			await rolesPermissionsPage.verifyState(35, notChecked);
			await rolesPermissionsPage.verifyState(36, notChecked);
			await rolesPermissionsPage.verifyState(37, notChecked);
			await rolesPermissionsPage.verifyState(38, notChecked);
			await rolesPermissionsPage.verifyState(39, notChecked);
			await rolesPermissionsPage.verifyState(40, notChecked);
			await rolesPermissionsPage.verifyState(41, notChecked);
			await rolesPermissionsPage.verifyState(42, notChecked);
			await rolesPermissionsPage.verifyState(43, notChecked);
			await rolesPermissionsPage.verifyState(44, notChecked);
			await rolesPermissionsPage.verifyState(45, notChecked);
			await rolesPermissionsPage.verifyState(46, notChecked);
			await rolesPermissionsPage.verifyState(47, checked);
			await rolesPermissionsPage.verifyState(48, notChecked);
			await rolesPermissionsPage.verifyState(49, notChecked);
			await rolesPermissionsPage.verifyState(50, checked);
			await rolesPermissionsPage.verifyState(51, checked);
			await rolesPermissionsPage.verifyState(52, notChecked);
			// Administration
			await rolesPermissionsPage.verifyState(53, notChecked);
			await rolesPermissionsPage.verifyState(54, notChecked);
			await rolesPermissionsPage.verifyState(55, notChecked);
			await rolesPermissionsPage.verifyState(56, notChecked);
			await rolesPermissionsPage.verifyState(57, notChecked);
			await rolesPermissionsPage.verifyState(58, notChecked);
			await rolesPermissionsPage.verifyState(59, notChecked);
			await rolesPermissionsPage.verifyState(60, notChecked);
			await rolesPermissionsPage.verifyState(61, notChecked);
			await rolesPermissionsPage.verifyState(62, notChecked);
			await rolesPermissionsPage.verifyState(63, notChecked);
			await rolesPermissionsPage.verifyState(64, notChecked);
			await rolesPermissionsPage.verifyState(65, notChecked);
			await rolesPermissionsPage.verifyState(66, notChecked);
			await rolesPermissionsPage.verifyState(67, checked);
			await rolesPermissionsPage.verifyState(68, notChecked);
			await rolesPermissionsPage.verifyState(69, checked);
			await rolesPermissionsPage.verifyState(70, checked);
			await rolesPermissionsPage.verifyState(71, notChecked);
			await rolesPermissionsPage.verifyState(72, checked);
			await rolesPermissionsPage.verifyState(73, checked);
			await rolesPermissionsPage.verifyState(74, notChecked);
			await rolesPermissionsPage.verifyState(75, notChecked);
			await rolesPermissionsPage.verifyState(76, notChecked);
			await rolesPermissionsPage.verifyState(77, notChecked);
			await rolesPermissionsPage.verifyState(78, notChecked);
			await rolesPermissionsPage.verifyState(79, notChecked);
			await rolesPermissionsPage.verifyState(80, notChecked);
			await rolesPermissionsPage.verifyState(81, notChecked);
			await rolesPermissionsPage.verifyState(82, notChecked);
			await rolesPermissionsPage.verifyState(83, checked);
			await rolesPermissionsPage.verifyState(84, notChecked);
		});

		await test.step('Candidate roles and permissions', async () => {
			await rolesPermissionsPage.clickRolesDropdown();
			await rolesPermissionsPage.rolesDropdownOptionVisible();
			await rolesPermissionsPage.selectRoleFromDropdown(RolesPermissionsPageData.candidate);
			// General
			await rolesPermissionsPage.verifyState(0, checked);
			await rolesPermissionsPage.verifyState(1, notChecked);
			await rolesPermissionsPage.verifyState(2, notChecked);
			await rolesPermissionsPage.verifyState(3, notChecked);
			await rolesPermissionsPage.verifyState(4, notChecked);
			await rolesPermissionsPage.verifyState(5, notChecked);
			await rolesPermissionsPage.verifyState(6, notChecked);
			await rolesPermissionsPage.verifyState(7, notChecked);
			await rolesPermissionsPage.verifyState(8, notChecked);
			await rolesPermissionsPage.verifyState(9, notChecked);
			await rolesPermissionsPage.verifyState(10, checked);
			await rolesPermissionsPage.verifyState(11, notChecked);
			await rolesPermissionsPage.verifyState(12, notChecked);
			await rolesPermissionsPage.verifyState(13, checked);
			await rolesPermissionsPage.verifyState(14, notChecked);
			await rolesPermissionsPage.verifyState(15, notChecked);
			await rolesPermissionsPage.verifyState(16, notChecked);
			await rolesPermissionsPage.verifyState(17, notChecked);
			await rolesPermissionsPage.verifyState(18, notChecked);
			await rolesPermissionsPage.verifyState(19, notChecked);
			await rolesPermissionsPage.verifyState(20, notChecked);
			await rolesPermissionsPage.verifyState(21, notChecked);
			await rolesPermissionsPage.verifyState(22, notChecked);
			await rolesPermissionsPage.verifyState(23, notChecked);
			await rolesPermissionsPage.verifyState(24, notChecked);
			await rolesPermissionsPage.verifyState(25, notChecked);
			await rolesPermissionsPage.verifyState(25, notChecked);
			await rolesPermissionsPage.verifyState(27, notChecked);
			await rolesPermissionsPage.verifyState(28, notChecked);
			await rolesPermissionsPage.verifyState(29, notChecked);
			await rolesPermissionsPage.verifyState(30, notChecked);
			await rolesPermissionsPage.verifyState(31, notChecked);
			await rolesPermissionsPage.verifyState(32, notChecked);
			await rolesPermissionsPage.verifyState(33, notChecked);
			await rolesPermissionsPage.verifyState(34, notChecked);
			await rolesPermissionsPage.verifyState(35, notChecked);
			await rolesPermissionsPage.verifyState(36, checked);
			await rolesPermissionsPage.verifyState(37, notChecked);
			await rolesPermissionsPage.verifyState(38, notChecked);
			await rolesPermissionsPage.verifyState(39, notChecked);
			await rolesPermissionsPage.verifyState(40, notChecked);
			await rolesPermissionsPage.verifyState(41, notChecked);
			await rolesPermissionsPage.verifyState(42, notChecked);
			await rolesPermissionsPage.verifyState(43, notChecked);
			await rolesPermissionsPage.verifyState(44, notChecked);
			await rolesPermissionsPage.verifyState(45, notChecked);
			await rolesPermissionsPage.verifyState(46, notChecked);
			await rolesPermissionsPage.verifyState(47, notChecked);
			await rolesPermissionsPage.verifyState(48, notChecked);
			await rolesPermissionsPage.verifyState(49, notChecked);
			await rolesPermissionsPage.verifyState(50, notChecked);
			await rolesPermissionsPage.verifyState(51, notChecked);
			await rolesPermissionsPage.verifyState(52, notChecked);
			// Administration
			await rolesPermissionsPage.verifyState(53, notChecked);
			await rolesPermissionsPage.verifyState(54, notChecked);
			await rolesPermissionsPage.verifyState(55, notChecked);
			await rolesPermissionsPage.verifyState(56, notChecked);
			await rolesPermissionsPage.verifyState(57, notChecked);
			await rolesPermissionsPage.verifyState(58, notChecked);
			await rolesPermissionsPage.verifyState(59, notChecked);
			await rolesPermissionsPage.verifyState(60, notChecked);
			await rolesPermissionsPage.verifyState(61, notChecked);
			await rolesPermissionsPage.verifyState(62, notChecked);
			await rolesPermissionsPage.verifyState(63, notChecked);
			await rolesPermissionsPage.verifyState(64, notChecked);
			await rolesPermissionsPage.verifyState(65, notChecked);
			await rolesPermissionsPage.verifyState(66, notChecked);
			await rolesPermissionsPage.verifyState(67, notChecked);
			await rolesPermissionsPage.verifyState(68, notChecked);
			await rolesPermissionsPage.verifyState(69, notChecked);
			await rolesPermissionsPage.verifyState(70, notChecked);
			await rolesPermissionsPage.verifyState(71, notChecked);
			await rolesPermissionsPage.verifyState(72, notChecked);
			await rolesPermissionsPage.verifyState(73, notChecked);
			await rolesPermissionsPage.verifyState(74, notChecked);
			await rolesPermissionsPage.verifyState(75, notChecked);
			await rolesPermissionsPage.verifyState(76, notChecked);
			await rolesPermissionsPage.verifyState(77, notChecked);
			await rolesPermissionsPage.verifyState(78, notChecked);
			await rolesPermissionsPage.verifyState(79, notChecked);
			await rolesPermissionsPage.verifyState(80, notChecked);
			await rolesPermissionsPage.verifyState(81, notChecked);
			await rolesPermissionsPage.verifyState(82, notChecked);
			await rolesPermissionsPage.verifyState(83, notChecked);
			await rolesPermissionsPage.verifyState(84, notChecked);
		});

		await test.step('Manager roles and permissions', async () => {
			await rolesPermissionsPage.clickRolesDropdown();
			await rolesPermissionsPage.rolesDropdownOptionVisible();
			await rolesPermissionsPage.selectRoleFromDropdown(RolesPermissionsPageData.manager);
			// General
			await rolesPermissionsPage.verifyState(0, notChecked);
			await rolesPermissionsPage.verifyState(1, notChecked);
			await rolesPermissionsPage.verifyState(2, notChecked);
			await rolesPermissionsPage.verifyState(3, notChecked);
			await rolesPermissionsPage.verifyState(4, notChecked);
			await rolesPermissionsPage.verifyState(5, notChecked);
			await rolesPermissionsPage.verifyState(6, notChecked);
			await rolesPermissionsPage.verifyState(7, notChecked);
			await rolesPermissionsPage.verifyState(8, notChecked);
			await rolesPermissionsPage.verifyState(9, notChecked);
			await rolesPermissionsPage.verifyState(10, notChecked);
			await rolesPermissionsPage.verifyState(11, notChecked);
			await rolesPermissionsPage.verifyState(12, notChecked);
			await rolesPermissionsPage.verifyState(13, notChecked);
			await rolesPermissionsPage.verifyState(14, notChecked);
			await rolesPermissionsPage.verifyState(15, notChecked);
			await rolesPermissionsPage.verifyState(16, notChecked);
			await rolesPermissionsPage.verifyState(17, notChecked);
			await rolesPermissionsPage.verifyState(18, notChecked);
			await rolesPermissionsPage.verifyState(19, notChecked);
			await rolesPermissionsPage.verifyState(20, notChecked);
			await rolesPermissionsPage.verifyState(21, notChecked);
			await rolesPermissionsPage.verifyState(22, notChecked);
			await rolesPermissionsPage.verifyState(23, notChecked);
			await rolesPermissionsPage.verifyState(24, notChecked);
			await rolesPermissionsPage.verifyState(25, notChecked);
			await rolesPermissionsPage.verifyState(26, notChecked);
			await rolesPermissionsPage.verifyState(27, notChecked);
			await rolesPermissionsPage.verifyState(28, notChecked);
			await rolesPermissionsPage.verifyState(29, notChecked);
			await rolesPermissionsPage.verifyState(30, notChecked);
			await rolesPermissionsPage.verifyState(31, notChecked);
			await rolesPermissionsPage.verifyState(32, notChecked);
			await rolesPermissionsPage.verifyState(33, notChecked);
			await rolesPermissionsPage.verifyState(34, notChecked);
			await rolesPermissionsPage.verifyState(35, notChecked);
			await rolesPermissionsPage.verifyState(36, notChecked);
			await rolesPermissionsPage.verifyState(37, notChecked);
			await rolesPermissionsPage.verifyState(38, notChecked);
			await rolesPermissionsPage.verifyState(39, notChecked);
			await rolesPermissionsPage.verifyState(40, notChecked);
			await rolesPermissionsPage.verifyState(41, notChecked);
			await rolesPermissionsPage.verifyState(42, notChecked);
			await rolesPermissionsPage.verifyState(43, notChecked);
			await rolesPermissionsPage.verifyState(44, notChecked);
			await rolesPermissionsPage.verifyState(45, notChecked);
			await rolesPermissionsPage.verifyState(46, notChecked);
			await rolesPermissionsPage.verifyState(47, notChecked);
			await rolesPermissionsPage.verifyState(48, notChecked);
			await rolesPermissionsPage.verifyState(49, notChecked);
			await rolesPermissionsPage.verifyState(50, notChecked);
			await rolesPermissionsPage.verifyState(51, notChecked);
			await rolesPermissionsPage.verifyState(52, notChecked);
			// Administration
			await rolesPermissionsPage.verifyState(53, notChecked);
			await rolesPermissionsPage.verifyState(54, notChecked);
			await rolesPermissionsPage.verifyState(55, notChecked);
			await rolesPermissionsPage.verifyState(56, notChecked);
			await rolesPermissionsPage.verifyState(57, notChecked);
			await rolesPermissionsPage.verifyState(58, notChecked);
			await rolesPermissionsPage.verifyState(59, notChecked);
			await rolesPermissionsPage.verifyState(60, notChecked);
			await rolesPermissionsPage.verifyState(61, notChecked);
			await rolesPermissionsPage.verifyState(62, notChecked);
			await rolesPermissionsPage.verifyState(63, notChecked);
			await rolesPermissionsPage.verifyState(64, notChecked);
			await rolesPermissionsPage.verifyState(65, notChecked);
			await rolesPermissionsPage.verifyState(66, notChecked);
			await rolesPermissionsPage.verifyState(67, notChecked);
			await rolesPermissionsPage.verifyState(68, notChecked);
			await rolesPermissionsPage.verifyState(69, notChecked);
			await rolesPermissionsPage.verifyState(70, notChecked);
			await rolesPermissionsPage.verifyState(71, notChecked);
			await rolesPermissionsPage.verifyState(72, notChecked);
			await rolesPermissionsPage.verifyState(73, notChecked);
			await rolesPermissionsPage.verifyState(74, notChecked);
			await rolesPermissionsPage.verifyState(75, notChecked);
			await rolesPermissionsPage.verifyState(76, notChecked);
			await rolesPermissionsPage.verifyState(77, notChecked);
			await rolesPermissionsPage.verifyState(78, notChecked);
			await rolesPermissionsPage.verifyState(79, notChecked);
			await rolesPermissionsPage.verifyState(80, notChecked);
			await rolesPermissionsPage.verifyState(81, notChecked);
			await rolesPermissionsPage.verifyState(82, notChecked);
			await rolesPermissionsPage.verifyState(83, notChecked);
			await rolesPermissionsPage.verifyState(84, notChecked);
		});

		await test.step('Viewer roles and permissions', async () => {
			await rolesPermissionsPage.clickRolesDropdown();
			await rolesPermissionsPage.rolesDropdownOptionVisible();
			await rolesPermissionsPage.selectRoleFromDropdown(RolesPermissionsPageData.viewer);
			// General
			await rolesPermissionsPage.verifyState(0, notChecked);
			await rolesPermissionsPage.verifyState(1, notChecked);
			await rolesPermissionsPage.verifyState(2, notChecked);
			await rolesPermissionsPage.verifyState(3, notChecked);
			await rolesPermissionsPage.verifyState(4, notChecked);
			await rolesPermissionsPage.verifyState(5, notChecked);
			await rolesPermissionsPage.verifyState(6, notChecked);
			await rolesPermissionsPage.verifyState(7, notChecked);
			await rolesPermissionsPage.verifyState(8, notChecked);
			await rolesPermissionsPage.verifyState(9, notChecked);
			await rolesPermissionsPage.verifyState(10, notChecked);
			await rolesPermissionsPage.verifyState(11, notChecked);
			await rolesPermissionsPage.verifyState(12, notChecked);
			await rolesPermissionsPage.verifyState(13, notChecked);
			await rolesPermissionsPage.verifyState(14, notChecked);
			await rolesPermissionsPage.verifyState(15, notChecked);
			await rolesPermissionsPage.verifyState(16, notChecked);
			await rolesPermissionsPage.verifyState(17, notChecked);
			await rolesPermissionsPage.verifyState(18, notChecked);
			await rolesPermissionsPage.verifyState(19, notChecked);
			await rolesPermissionsPage.verifyState(20, notChecked);
			await rolesPermissionsPage.verifyState(21, notChecked);
			await rolesPermissionsPage.verifyState(22, notChecked);
			await rolesPermissionsPage.verifyState(23, notChecked);
			await rolesPermissionsPage.verifyState(24, notChecked);
			await rolesPermissionsPage.verifyState(25, notChecked);
			await rolesPermissionsPage.verifyState(26, notChecked);
			await rolesPermissionsPage.verifyState(27, notChecked);
			await rolesPermissionsPage.verifyState(28, notChecked);
			await rolesPermissionsPage.verifyState(29, notChecked);
			await rolesPermissionsPage.verifyState(30, notChecked);
			await rolesPermissionsPage.verifyState(31, notChecked);
			await rolesPermissionsPage.verifyState(32, notChecked);
			await rolesPermissionsPage.verifyState(33, notChecked);
			await rolesPermissionsPage.verifyState(34, notChecked);
			await rolesPermissionsPage.verifyState(35, notChecked);
			await rolesPermissionsPage.verifyState(36, notChecked);
			await rolesPermissionsPage.verifyState(37, notChecked);
			await rolesPermissionsPage.verifyState(38, notChecked);
			await rolesPermissionsPage.verifyState(39, notChecked);
			await rolesPermissionsPage.verifyState(40, notChecked);
			await rolesPermissionsPage.verifyState(41, notChecked);
			await rolesPermissionsPage.verifyState(42, notChecked);
			await rolesPermissionsPage.verifyState(43, notChecked);
			await rolesPermissionsPage.verifyState(44, notChecked);
			await rolesPermissionsPage.verifyState(45, notChecked);
			await rolesPermissionsPage.verifyState(46, notChecked);
			await rolesPermissionsPage.verifyState(47, notChecked);
			await rolesPermissionsPage.verifyState(48, notChecked);
			await rolesPermissionsPage.verifyState(49, notChecked);
			await rolesPermissionsPage.verifyState(50, notChecked);
			await rolesPermissionsPage.verifyState(51, notChecked);
			await rolesPermissionsPage.verifyState(52, notChecked);
			// Administration
			await rolesPermissionsPage.verifyState(53, notChecked);
			await rolesPermissionsPage.verifyState(54, notChecked);
			await rolesPermissionsPage.verifyState(55, notChecked);
			await rolesPermissionsPage.verifyState(56, notChecked);
			await rolesPermissionsPage.verifyState(57, notChecked);
			await rolesPermissionsPage.verifyState(58, notChecked);
			await rolesPermissionsPage.verifyState(59, notChecked);
			await rolesPermissionsPage.verifyState(60, notChecked);
			await rolesPermissionsPage.verifyState(61, notChecked);
			await rolesPermissionsPage.verifyState(62, notChecked);
			await rolesPermissionsPage.verifyState(63, notChecked);
			await rolesPermissionsPage.verifyState(64, notChecked);
			await rolesPermissionsPage.verifyState(65, notChecked);
			await rolesPermissionsPage.verifyState(66, notChecked);
			await rolesPermissionsPage.verifyState(67, notChecked);
			await rolesPermissionsPage.verifyState(68, notChecked);
			await rolesPermissionsPage.verifyState(69, notChecked);
			await rolesPermissionsPage.verifyState(70, notChecked);
			await rolesPermissionsPage.verifyState(71, notChecked);
			await rolesPermissionsPage.verifyState(72, notChecked);
			await rolesPermissionsPage.verifyState(73, notChecked);
			await rolesPermissionsPage.verifyState(74, notChecked);
			await rolesPermissionsPage.verifyState(75, notChecked);
			await rolesPermissionsPage.verifyState(76, notChecked);
			await rolesPermissionsPage.verifyState(77, notChecked);
			await rolesPermissionsPage.verifyState(78, notChecked);
			await rolesPermissionsPage.verifyState(79, notChecked);
			await rolesPermissionsPage.verifyState(80, notChecked);
			await rolesPermissionsPage.verifyState(81, notChecked);
			await rolesPermissionsPage.verifyState(82, notChecked);
			await rolesPermissionsPage.verifyState(83, notChecked);
			await rolesPermissionsPage.verifyState(84, notChecked);
		});

		await test.step('Should be able to verify text', async () => {
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewAdminDashboard);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewPayments);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditDeletePayments);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewAllExpenses);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditDeleteExpenses);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewAllEmployeeExpenses);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditDeleteEmployeeExpenses);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditDeleteIncomes);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewAllIncomes);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditDeleteProposalsRegister);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewProposalsPage);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewProposalTemplatesPage);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditDeleteProposalTemplates);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewTimeOffPage);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewOrganizationInvites);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createResendDeleteInvites);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewTimeOffPolicy);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.editTimeOffPolicy);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.editTimeOff);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.editApprovalsPolicy);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewApprovalsPolicy);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.editApprovalRequest);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewApprovalRequest);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.accessPrivateProjects);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.editTimeInTimesheet);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewInvoices);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.editInvoicesAdd);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewEstimates);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.editEstimatesAdd);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewAllCandidatesDocuments);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditTask);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditInterview);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditInterviewers);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditDeleteCandidateFeedback);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.managementProduct);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditDeleteTags);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewAllEmails);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewAllEmailsTemplates);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.editOrganizationHelpCenter);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewSalesPipelines);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.editSalesPipelines);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.approveTimesheet);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditSprints);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewSprints);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditProjects);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditContacts);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewContacts);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditTeams);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditContracts);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewEventTypes);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewOrganizationEmployees);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditDeleteOrganizationEmployees);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewOrganizationCandidates);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditDeleteOrganizationCandidates);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewOrganizationUsers);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditDeleteOrganizationUsers);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewAllOrganizations);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.createEditDeleteAllOrganizations);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.changeSelectedEmployee);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.changeSelectedCandidate);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.changeSelectedOrganization);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.changeRolesPermissions);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.editSuperAdminUsers);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.editOrganizationPublicPage);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.tenantAddUserToOrganization);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewIntegrations);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewFileStorage);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewPaymentGateway);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewSMSGateway);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewCustomSMTP);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewImportExport);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewJobEmployees);
			await rolesPermissionsPage.verifyTextExist(RolesPermissionsPageData.viewJobMatching);
		});
	});
});
