export const CreateButtonData = {
	income: 'Income',
	expense: 'Expense',
	invoice: 'Invoice',
	estimate: 'Estimate',
	payment: 'Payment',
	timeLog: 'Time Log',
	candidate: 'Candidate',
	proposal: 'Proposal',
	contract: 'Contract',
	team: 'Team',
	task: 'Task',
	contact: 'Contact',
	project: 'Project',
	employee: 'Employee',
	incomeHeader: 'Add Income',
	expenseHeader: 'Add Expense',
	invoiceHeader: 'Add Invoice',
	estimateHeader: 'Add Estimate',
	paymentHeader: 'Record Payment',
	timeLogHeader: 'Add Time Logs',
	candidateHeader: 'Add Candidates',
	proposalHeader: 'Register Proposal',
	contractHeader: 'Upwork',
	teamHeader: 'Teams',
	taskHeader: 'Add Tasks',
	contactHeader: 'Add New Contact',
	projectHeader: 'Projects',
	employeeHeader: 'Add Employee'
};
