export const EmailTemplatesPageData = {
	english: 'English',
	bulgarian: 'Bulgarian',
	hebrew: 'Hebrew',
	russian: 'Russian',
	//Subjects by Language
	passwordResetSubjectEnglish: 'Welcome to Gauzy user@domain.com',
	passwordResetSubjectBulgarian: 'Добре дошли в Gauzy™ user@domain.com\n',
	passwordResetSubjectHebrew: 'ברוך הבא לגוזי! user@domain.com',
	passwordResetSubjectRussian: 'Добро пожаловать в Gauzy user@domain.com',
	appointmentConfirmationSubjectEnglish: 'Appointment Confirmed',
	appointmentConfirmationSubjectBulgarian: 'Назначението е потвърдено',
	appointmentConfirmationSubjectHebrew: 'אישור המינוי',
	appointmentConfirmationSubjectRussian: 'Назначение подтверждено',
	appointmentCancellationSubjectEnglish: 'Appointment Cancellation',
	appointmentCancellationSubjectBulgarian: 'Назначението е потвърдено',
	appointmentCancellationSubjectHebrew: 'אישור המינוי',
	appointmentCancellationSubjectRussian: 'Отмена встречи',
	timeOffPolicySubjectEnglish: 'Time Off Policy APPROVE/REJECT',
	timeOffPolicySubjectBulgarian: 'Политика за изключено време APPROVE/REJECT',
	timeOffPolicySubjectHebrew: 'מדיניות זמן המתנה APPROVE/REJECT',
	timeOffPolicySubjectRussian: 'Политика перерыва APPROVE/REJECT',
	taskUpdateSubjectEnglish: 'Task Update from Gauzy',
	taskUpdateSubjectBulgarian: 'Актуализация на задачата от Gauzy',
	taskUpdateSubjectHebrew: 'עדכון המשימה מגוזי',
	taskUpdateSubjectRussian: 'Обновление задачи от Гаузи',
	equipmentCreateSubjectEnglish: 'Equipment created',
	equipmentCreateSubjectBulgarian: 'Създадено оборудване',
	equipmentCreateSubjectHebrew: 'ציוד שנוצר',
	equipmentCreateSubjectRussian: 'Создано оборудование',
	equipmentRequestSubjectEnglish: 'Equipment Request APPROVE/REJECT',
	equipmentRequestSubjectBulgarian: 'Заявка за оборудване APPROVE/REJECT',
	equipmentRequestSubjectHebrew: 'בקשת ציוד APPROVE/REJECT',
	equipmentRequestSubjectRussian: 'Запрос на оборудование APPROVE/REJECT',
	timeSheetOverviewSubjectEnglish: 'Time sheet Overview',
	timeSheetOverviewSubjectBulgarian: 'Преглед на хронологията',
	timeSheetOverviewSubjectHebrew: 'סקירת גיליון זמנים',
	timeSheetOverviewSubjectRussian: 'Обзор табеля рабочего времени',
	timeSheetSubmitSubjectEnglish: 'Time sheet Submit',
	timeSheetSubmitSubjectBulgarian: 'Изпращане на график',
	timeSheetSubmitSubjectHebrew: 'הגשת גיליון זמנים',
	timeSheetSubmitSubjectRussian: 'Отправить расписание',
	timeSheetActionsSubjectEnglish: 'Time sheet Action',
	timeSheetActionsSubjectBulgarian: 'Времеви лист Действие',
	timeSheetActionsSubjectHebrew: 'גיליון זמן פעולה',
	timeSheetActionsSubjectRussian: 'Табель рабочего времени Действие',
	timeSheetDeleteSubjectEnglish: 'Time sheet Delete',
	timeSheetDeleteSubjectBulgarian: 'Изтриване на графика',
	timeSheetDeleteSubjectHebrew: 'מחק גיליון זמנים',
	timeSheetDeleteSubjectRussian: 'Расписание Удалить',
	candidateInterviewScheduleSubjectEnglish: 'Interview Schedule',
	candidateInterviewScheduleSubjectBulgarian: 'График за интервю',
	candidateInterviewScheduleSubjectHebrew: 'לוח הזמנים לראיון',
	candidateInterviewScheduleSubjectRussian: 'Расписание интервью',
	interviewerScheduleSubjectEnglish: 'Interview Schedule',
	interviewerScheduleSubjectBulgarian: 'График за интервю',
	interviewerScheduleSubjectHebrew: 'לוח הזמנים לראיון',
	interviewerScheduleSubjectRussian: 'Расписание интервью',
	welcomeUserSubjectEnglish: 'Welcome to Gauzy user@domain.com',
	welcomeUserSubjectBulgarian: 'Добре дошли в Gauzy™ user@domain.com',
	welcomeUserSubjectHebrew: 'ברוך הבא לגוזי! user@domain.com',
	welcomeUserSubjectRussian: 'Добро пожаловать в Gauzy user@domain.com!',
	inviteOrganizationClientSubjectEnglish:
		"John Doe, you've been invited to Gauzy!",
	inviteOrganizationClientSubjectBulgarian:
		'Добре дошли в Gauzy™ user@domain.com',
	inviteOrganizationClientSubjectHebrew: 'ברוך הבא לגוזי! user@domain.com',
	inviteOrganizationClientSubjectRussian:
		'Добро пожаловать в Gauzy user@domain.com!',
	inviteEmployeeSubjectEnglish: 'Welcome to Gauzy user@domain.com',
	inviteEmployeeSubjectBulgarian: 'Добре дошли в Gauzy user@domain.com',
	inviteEmployeeSubjectHebrew: 'ברוך הבא לגוזי! user@domain.com',
	inviteEmployeeSubjectRussian: 'Добро пожаловать в Gauzy user@domain.com!',
	inviteUserSubjectEnglish: 'Welcome to Gauzy user@domain.com',
	inviteUserSubjectBulgarian: 'Добре дошли в Gauzy user@domain.com',
	inviteUserSubjectHebrew: 'ברוך הבא לגוזי! user@domain.com',
	inviteUserSubjectRussian: 'Добро пожаловать в Gauzy user@domain.com!',
	emailInvoiceSubjectEnglish: 'New invoice received user@domain.com',
	emailEstimateSubjectEnglish: 'New estimate received user@domain.com',
	//Template Names
	appointmentConfirmationTemplateOption: 'Appointment Confirmation',
	appointmentCancellationTemplateOption: 'Appointment Cancellation',
	timeOffPolicyTemplateOption: 'Time off policy action',
	taskUpdateTemplateOption: 'Task Update',
	equipmentCreateTemplateOption: 'Equipment Create',
	equipmentRequestTemplateOption: 'Equipment Request',
	timeSheetOverviewTemplateOption: 'Time sheet overview',
	timeSheetSubmitTemplateOption: 'Time Sheet Submit',
	timeSheetActionsTemplateOption: 'Time Sheet Actions',
	timeSheetDeleteTemplateOption: 'Time Sheet Delete',
	candidateInterviewScheduleTemplateOption: 'Candidate Interview Schedule',
	interviewerScheduleTemplateOption: 'Interviewer Schedule',
	welcomeUserTemplateOption: 'Welcome User',
	inviteOrganizationClientTemplateOption: 'Invite Organization Client',
	inviteEmployeeTemplateOption: 'Invite Employee',
	inviteUserTemplateOption: 'Invite User',
	emailInvoiceTemplateOption: 'Email Invoice',
	emailEstimateTemplateOption: 'Email Estimate'
};
