export const HumanResourcesPageData = {
	totalIncomeText: 'Total Income',
	totalExpenseText: 'Total Expense without salary',
	totalExpensesText: 'Total Expenses',
	profitText: 'Profit',
	barChartText: 'Bar',
	doughnutChartText: 'Doughnut',
	stackedBarChartText: 'Stacked Bar',
	incomeHeaderText: 'INCOME',
	incomeTableHeaderDateText: 'Date',
	incomeTableHeaderClientNameText: 'Contact',
	incomeTableHeaderValueText: 'Value',
	incomeTableHeaderNotesText: 'Notes',
	expensesHeaderText: 'EXPENSES',
	expensesTableHeaderSourceText: 'Source',
	expensesTableHeaderDateText: 'Date',
	expensesTableHeaderVendorText: 'Vendor',
	expensesTableHeaderCategoryText: 'Category',
	expensesTableHeaderValueText: 'Value',
	expensesTableHeaderNotesText: 'Notes',
	profitHeaderText: 'Profit Report',
	profitTableHeaderDateText: 'Date',
	profitTableHeaderExpensesText: 'Expenses',
	profitTableHeaderIncomeText: 'Income',
	profitTableHeaderDescriptionText: 'Description'
};
