export const OrganizationInventoryPageData = {
	defaultInventoryLanguage: 'English',
	defaultInventoryCode: '01A9990Z',
	defaultCategoryLanguage: 'ENGLISH',
	inventoryName: 'Outsource',
	productCategoryName: 'Web Development',
	productCategoryDescription: 'Main category',
	productInventoryDescription: 'Main category and type',
	productTypeName: 'CRM System',
	productTypeDescription: 'Main product',
	categoryButtonText: 'Product categories',
	typeButtonText: 'Product types',
	currency: 'Afghan Afghani (AFN)',
	country: 'Afghanistan',
	nextBtn: 'Next',
	main: 'Main',
	location: 'Location',
	merchantName: 'Dominos Pizza',
	editMerchantName: 'Mambo Pizza',
	editWarehouseName: 'Jumbo',
	merchantCode: '01A9990Z',
	warehouseName: 'Sardo & Sons',
	warehouseCode: '01A9990Z',
	organization: 'Organization',
	merchants: 'Merchants',
	warehouses: 'Warehouses'
};
