export const RolesPermissionsPageData = {
	superAdmin: 'Super Admin',
	admin: 'Admin',
	dataEntry: 'Data Entry',
	employee: 'Employee',
	candidate: 'Candidate',
	manager: 'Manager',
	viewer: 'Viewer',
	// General
	viewAdminDashboard: 'View Admin Dashboard',
	viewPayments: 'View Payments',
	createEditDeletePayments: 'Create/Edit/Delete Payments',
	viewAllExpenses: 'View All Expenses',
	createEditDeleteExpenses: 'Create/Edit/Delete Expenses',
	viewAllEmployeeExpenses: 'View All Employee Expenses',
	createEditDeleteEmployeeExpenses: 'Create/Edit/Delete Employee Expenses',
	createEditDeleteIncomes: 'Create/Edit/Delete Incomes',
	viewAllIncomes: 'View All Incomes',
	createEditDeleteProposalsRegister: 'Create/Edit/Delete Proposals Register',
	viewProposalsPage: 'View Proposals Page',
	viewProposalTemplatesPage: 'View Proposal Templates Page',
	createEditDeleteProposalTemplates: 'Create/Edit/Delete Proposal Templates',
	viewTimeOffPage: 'View Time Off Page',
	viewOrganizationInvites: 'View Organization Invites',
	createResendDeleteInvites: 'Create/Resend/Delete Invites',
	viewTimeOffPolicy: 'View Time Off Policy',
	editTimeOffPolicy: 'Edit Time Off Policy',
	editTimeOff: 'Edit Time Off',
	editApprovalsPolicy: 'Edit Approvals Policy',
	viewApprovalsPolicy: 'View Approvals Policy',
	editApprovalRequest: 'Edit Approval Request',
	viewApprovalRequest: 'View Approval Request',
	accessPrivateProjects: 'Access Private Projects',
	editTimeinTimesheet: 'Edit Time in Timesheet',
	viewInvoices: 'View Invoices',
	editInvoicesAdd: 'Edit Invoices Add',
	viewEstimates: 'View Estimates',
	editEstimatesAdd: 'Edit Estimates Add',
	viewAllCandidatesDocuments: 'View All Candidates Documents',
	createEditTask: 'Create/Edit Task',
	createEditInterview: 'Create/Edit Interview',
	createEditInterviewers: 'Create/Edit Interviewers',
	createEditDeleteCandidateFeedback: 'Create/Edit/Delete Candidate Feedback',
	managementProduct: 'Management Product',
	createEditDeleteTags: 'Create/Edit/Delete Tags',
	viewAllEmails: 'View All Emails',
	viewAllEmailsTemplates: 'View All Emails Templates',
	editOrganizationHelpCenter: 'Edit Organization Help Center',
	viewSalesPipelines: 'View Sales Pipelines',
	editSalesPipelines: 'Edit Sales Pipelines',
	approveTimesheet: 'Approve Timesheet',
	createEditSprints: 'Create/Edit Sprints',
	viewSprints: 'View Sprints',
	createEditProjects: 'Create/Edit Projects',
	createEditContacts: 'Create/Edit Contacts',
	viewContacts: 'View Contacts',
	createEditTeams: 'Create/Edit Teams',
	createEditContracts: 'Create/Edit Contracts',
	viewEventTypes: 'View Event Types',
	// Administration
	viewOrganizationEmployees: 'View Organization Employees',
	createEditDeleteOrganizationEmployees:
		'Create/Edit/Delete Organization Employees',
	viewOrganizationCandidates: 'View Organization Candidates',
	createEditDeleteOrganizationCandidates:
		'Create/Edit/Delete Organization Candidates',
	viewOrganizationUsers: 'View Organization Users',
	createEditDeleteOrganizationUsers: 'Create/Edit/Delete Organization Users',
	viewAllOrganizations: 'View All Organizations',
	createEditDeleteAllOrganizations: 'Create/Edit/Delete All Organizations',
	changeSelectedEmployee: 'Change Selected Employee',
	changeSelectedCandidate: 'Change Selected Candidate',
	changeSelectedOrganization: 'Change Selected Organization',
	changeRolesPermissions: 'Change Roles & Permissions',
	editSuperAdminUsers: 'Edit Super Admin Users',
	editOrganizationPublicPage: 'Edit Organization Public Page',
	tenantAddUserToOrganization: 'Tenant Add User To Organization',
	viewIntegrations: 'View Integrations',
	viewFileStorage: 'View File Storage',
	viewPaymentGateway: 'View Payment Gateway',
	viewSMSGateway: 'View SMS Gateway',
	viewCustomSMTP: 'View Custom SMTP',
	viewImportExport: 'View Import/Export',
	viewJobEmployees: 'View Job Employees',
	viewJobMatching: 'View Job Matching',
	AllowPermissionXX0 : 0,
	AllowPermissionXX1 : 1,
	AllowPermissionXX2 : 2,
	AllowPermissionXX3 : 3,
	AllowPermissionXX4 : 4,
	AllowPermissionXX5 : 5,
	AllowPermissionXX6 : 6,
	AllowPermissionXX7 : 7,
	AllowPermissionXX8 : 8,
	AllowPermissionXX9 : 9,
	AllowPermissionX10 : 10,
	AllowPermissionX11 : 11,
	AllowPermissionX12 : 12,
	AllowPermissionX13 : 13,
	AllowPermissionX14 : 14,
	AllowPermissionX15 : 15,
	AllowPermissionX16 : 16,
	AllowPermissionX17 : 17,
	AllowPermissionX18 : 18,
	AllowPermissionX19 : 19,
	AllowPermissionX20 : 20,
	AllowPermissionX21 : 21,
	AllowPermissionX22 : 22,
	AllowPermissionX23 : 23,
	AllowPermissionX24 : 24,
	AllowPermissionX25 : 25,
	AllowPermissionX26 : 26,
	AllowPermissionX27 : 27,
	AllowPermissionX28 : 28,
	AllowPermissionX29 : 29,
	AllowPermissionX30 : 30,
	AllowPermissionX31 : 31,
	AllowPermissionX32 : 32,
	AllowPermissionX33 : 33,
	AllowPermissionX34 : 34,
	AllowPermissionX35 : 35,
	AllowPermissionX36 : 36,
	AllowPermissionX37 : 37,
	AllowPermissionX38 : 38,
	AllowPermissionX39 : 39,
	AllowPermissionX40 : 40,
	AllowPermissionX41 : 41,
	AllowPermissionX42 : 42,
	AllowPermissionX43 : 43,
	AllowPermissionX44 : 44,
	AllowPermissionX45 : 45,
	AllowPermissionX46 : 46,
	AllowPermissionX47 : 47,
	AllowPermissionX48 : 48,
	AllowPermissionX49 : 49,
	AllowPermissionX50 : 50,
	AllowPermissionX51 : 51,
	AllowPermissionX52 : 52,
	AllowPermissionX53 : 53,
	AllowPermissionX54 : 54,
	AllowPermissionX55 : 55,
	AllowPermissionX56 : 56,
	AllowPermissionX57 : 57,
	AllowPermissionX58 : 58,
	AllowPermissionX59 : 59,
	AllowPermissionX60 : 60,
	AllowPermissionX61 : 61,
	AllowPermissionX62 : 62,
	AllowPermissionX63 : 63,
	AllowPermissionX64 : 64,
	AllowPermissionX65 : 65,
	AllowPermissionX66 : 66,
	AllowPermissionX67 : 67,
	AllowPermissionX68 : 68,
	AllowPermissionX69 : 69,
	AllowPermissionX70 : 70,
	AllowPermissionX71 : 71,
	AllowPermissionX72 : 72,
	AllowPermissionX73 : 73,
	AllowPermissionX74 : 74,
	AllowPermissionX75 : 75,
	AllowPermissionX76 : 76,
	AllowPermissionX77 : 77,
	AllowPermissionX78 : 78,
	AllowPermissionX79 : 79,
	AllowPermissionX80 : 80,
	AllowPermissionX81 : 81,
	AllowPermissionX82 : 82,
	AllowPermissionX83 : 83,
	AllowPermissionX84 : 84,
	AllowPermissionX85 : 85,
	AllowPermissionX86 : 86,
	AllowPermissionX87 : 87,
	AllowPermissionX88 : 88,
	AllowPermissionX89 : 89,
	AllowPermissionX90 : 90,
	AllowPermissionX91 : 91,
	AllowPermissionX92 : 92,
	AllowPermissionX93 : 93,
	AllowPermissionX94 : 94,
	AllowPermissionX95 : 95,
	AllowPermissionX96 : 96,
	AllowPermissionX97 : 97,
	AllowPermissionX98 : 98,
	AllowPermissionX99 : 99,
	AllowPermission100 : 100
};
