export const RolesPermissionsPageData = {
	superAdmin: 'Super Admin',
	admin: 'Admin',
	dataEntry: 'Data Entry',
	employee: 'Employee',
	candidate: 'Candidate',
	manager: 'Manager',
	viewer: 'Viewer',
	// General
	viewAdminDashboard: 'View Admin Dashboard',
	viewPayments: 'View Payments',
	createEditDeletePayments: 'Create/Edit/Delete Payments',
	viewAllExpenses: 'View All Expenses',
	createEditDeleteExpenses: 'Create/Edit/Delete Expenses',
	viewAllEmployeeExpenses: 'View All Employee Expenses',
	createEditDeleteEmployeeExpenses: 'Create/Edit/Delete Employee Expenses',
	createEditDeleteIncomes: 'Create/Edit/Delete Incomes',
	viewAllIncomes: 'View All Incomes',
	createEditDeleteProposalsRegister: 'Create/Edit/Delete Proposals Register',
	viewProposalsPage: 'View Proposals Page',
	viewProposalTemplatesPage: 'View Proposal Templates Page',
	createEditDeleteProposalTemplates: 'Create/Edit/Delete Proposal Templates',
	viewTimeOffPage: 'View Time Off Page',
	viewOrganizationInvites: 'View Organization Invites',
	createResendDeleteInvites: 'Create/Resend/Delete Invites',
	viewTimeOffPolicy: 'View Time Off Policy',
	editTimeOffPolicy: 'Edit Time Off Policy',
	editTimeOff: 'Edit Time Off',
	editApprovalsPolicy: 'Edit Approvals Policy',
	viewApprovalsPolicy: 'View Approvals Policy',
	editApprovalRequest: 'Edit Approval Request',
	viewApprovalRequest: 'View Approval Request',
	accessPrivateProjects: 'Access Private Projects',
	editTimeinTimesheet: 'Edit Time in Timesheet',
	viewInvoices: 'View Invoices',
	editInvoicesAdd: 'Edit Invoices Add',
	viewEstimates: 'View Estimates',
	editEstimatesAdd: 'Edit Estimates Add',
	viewAllCandidatesDocuments: 'View All Candidates Documents',
	createEditTask: 'Create/Edit Task',
	createEditInterview: 'Create/Edit Interview',
	createEditInterviewers: 'Create/Edit Interviewers',
	createEditDeleteCandidateFeedback: 'Create/Edit/Delete Candidate Feedback',
	managementProduct: 'Management Product',
	createEditDeleteTags: 'Create/Edit/Delete Tags',
	viewAllEmails: 'View All Emails',
	viewAllEmailsTemplates: 'View All Emails Templates',
	editOrganizationHelpCenter: 'Edit Organization Help Center',
	viewSalesPipelines: 'View Sales Pipelines',
	editSalesPipelines: 'Edit Sales Pipelines',
	approveTimesheet: 'Approve Timesheet',
	createEditSprints: 'Create/Edit Sprints',
	viewSprints: 'View Sprints',
	createEditProjects: 'Create/Edit Projects',
	createEditContacts: 'Create/Edit Contacts',
	viewContacts: 'View Contacts',
	createEditTeams: 'Create/Edit Teams',
	createEditContracts: 'Create/Edit Contracts',
	viewEventTypes: 'View Event Types',
	// Administration
	viewOrganizationEmployees: 'View Organization Employees',
	createEditDeleteOrganizationEmployees:
		'Create/Edit/Delete Organization Employees',
	viewOrganizationCandidates: 'View Organization Candidates',
	createEditDeleteOrganizationCandidates:
		'Create/Edit/Delete Organization Candidates',
	viewOrganizationUsers: 'View Organization Users',
	createEditDeleteOrganizationUsers: 'Create/Edit/Delete Organization Users',
	viewAllOrganizations: 'View All Organizations',
	createEditDeleteAllOrganizations: 'Create/Edit/Delete All Organizations',
	changeSelectedEmployee: 'Change Selected Employee',
	changeSelectedCandidate: 'Change Selected Candidate',
	changeSelectedOrganization: 'Change Selected Organization',
	changeRolesPermissions: 'Change Roles & Permissions',
	editSuperAdminUsers: 'Edit Super Admin Users',
	editOrganizationPublicPage: 'Edit Organization Public Page',
	tenantAddUserToOrganization: 'Tenant Add User To Organization',
	viewIntegrations: 'View Integrations',
	viewFileStorage: 'View File Storage',
	viewPaymentGateway: 'View Payment Gateway',
	viewSMSGateway: 'View SMS Gateway',
	viewCustomSMTP: 'View Custom SMTP',
	viewImportExport: 'View Import/Export',
	viewJobEmployees: 'View Job Employees',
	viewJobMatching: 'View Job Matching',
	accessDeleteAccount: "Access Delete Account",
	accessDeleteAllData: "Access Delete All Data"
};
