export const RolesPermissionsPageData = {
	superAdmin: 'Super Admin',
	admin: 'Admin',
	dataEntry: 'Data Entry',
	employee: 'Employee',
	candidate: 'Candidate',
	manager: 'Manager',
	viewer: 'Viewer',
	// General
	viewAdminDashboard: 'View Admin Dashboard',
	viewPayments: 'View Payments',
	createEditDeletePayments: 'Create/Edit/Delete Payments',
	viewAllExpenses: 'View All Expenses',
	createEditDeleteExpenses: 'Create/Edit/Delete Expenses',
	viewAllEmployeeExpenses: 'View All Employee Expenses',
	createEditDeleteEmployeeExpenses: 'Create/Edit/Delete Employee Expenses',
	createEditDeleteIncomes: 'Create/Edit/Delete Incomes',
	viewAllIncomes: 'View All Incomes',
	createEditDeleteProposalsRegister: 'Create/Edit/Delete Proposals Register',
	viewProposalsPage: 'View Proposals Page',
	viewProposalTemplatesPage: 'View Proposal Templates Page',
	createEditDeleteProposalTemplates: 'Create/Edit/Delete Proposal Templates',
	viewTimeOffPage: 'View Time Off Page',
	viewOrganizationInvites: 'View Organization Invites',
	createResendDeleteInvites: 'Create/Resend/Delete Invites',
	viewTimeOffPolicy: 'View Time Off Policy',
	editTimeOffPolicy: 'Edit Time Off Policy',
	editTimeOff: 'Edit Time Off',
	editApprovalsPolicy: 'Edit Approvals Policy',
	viewApprovalsPolicy: 'View Approvals Policy',
	editApprovalRequest: 'Edit Approval Request',
	viewApprovalRequest: 'View Approval Request',
	accessPrivateProjects: 'Access Private Projects',
	editTimeinTimesheet: 'Edit Time in Timesheet',
	viewInvoices: 'View Invoices',
	editInvoicesAdd: 'Edit Invoices Add',
	viewEstimates: 'View Estimates',
	editEstimatesAdd: 'Edit Estimates Add',
	viewAllCandidatesDocuments: 'View All Candidates Documents',
	createEditTask: 'Create/Edit Task',
	createEditInterview: 'Create/Edit Interview',
	createEditInterviewers: 'Create/Edit Interviewers',
	createEditDeleteCandidateFeedback: 'Create/Edit/Delete Candidate Feedback',
	managementProduct: 'Management Product',
	createEditDeleteTags: 'Create/Edit/Delete Tags',
	viewAllEmails: 'View All Emails',
	viewAllEmailsTemplates: 'View All Emails Templates',
	editOrganizationHelpCenter: 'Edit Organization Help Center',
	viewSalesPipelines: 'View Sales Pipelines',
	editSalesPipelines: 'Edit Sales Pipelines',
	approveTimesheet: 'Approve Timesheet',
	createEditSprints: 'Create/Edit Sprints',
	viewSprints: 'View Sprints',
	createEditProjects: 'Create/Edit Projects',
	createEditContacts: 'Create/Edit Contacts',
	viewContacts: 'View Contacts',
	createEditTeams: 'Create/Edit Teams',
	createEditContracts: 'Create/Edit Contracts',
	viewEventTypes: 'View Event Types',
	// Administration
	viewOrganizationEmployees: 'View Organization Employees',
	createEditDeleteOrganizationEmployees:
		'Create/Edit/Delete Organization Employees',
	viewOrganizationCandidates: 'View Organization Candidates',
	createEditDeleteOrganizationCandidates:
		'Create/Edit/Delete Organization Candidates',
	viewOrganizationUsers: 'View Organization Users',
	createEditDeleteOrganizationUsers: 'Create/Edit/Delete Organization Users',
	viewAllOrganizations: 'View All Organizations',
	createEditDeleteAllOrganizations: 'Create/Edit/Delete All Organizations',
	changeSelectedEmployee: 'Change Selected Employee',
	changeSelectedCandidate: 'Change Selected Candidate',
	changeSelectedOrganization: 'Change Selected Organization',
	changeRolesPermissions: 'Change Roles & Permissions',
	editSuperAdminUsers: 'Edit Super Admin Users',
	editOrganizationPublicPage: 'Edit Organization Public Page',
	tenantAddUserToOrganization: 'Tenant Add User To Organization',
	viewIntegrations: 'View Integrations',
	viewFileStorage: 'View File Storage',
	viewPaymentGateway: 'View Payment Gateway',
	viewSMSGateway: 'View SMS Gateway',
	viewCustomSMTP: 'View Custom SMTP',
	viewImportExport: 'View Import/Export',
	viewJobEmployees: 'View Job Employees',
	viewJobMatching: 'View Job Matching',
	ViewAdminDashboard : 0,
	ViewPayments : 1,
	CreateEditDeletePayments : 2,
	ViewAllExpenses : 3,
	CreateEditDeleteExpenses : 4,
	ViewAllEmployeeExpenses : 5,
	CreateEditDeleteEmployeeExpenses : 6,
	CreateEditDeleteIncomes : 7,
	ViewAllIncomes : 8,
	CreateEditDeleteProposalsRegister : 9,
	ViewProposalsPage : 10,
	ViewProposalTemplatesPage : 11,
	CreateEditDeleteProposalTemplates : 12,
	ViewTimeOffPage : 13,
	ViewOrganizationInvites : 14,
	CreateResendDeleteInvites : 15,
	ViewTimeOffPolicy : 16,
	EditTimeOffPolicy : 17,
	EditTimeOff : 18,
	EditApprovalsPolicy : 19,
	ViewApprovalsPolicy : 20,
	EditApprovalRequest : 21,
	ViewApprovalRequest : 22,
	AccessPrivateProjects : 23,
	EditTimeInTimesheet : 24,
	ViewInvoices : 25,
	EditInvoicesAdd : 26,
	ViewEstimates : 27,
	EditEstimatesAdd : 28,
	ViewAllCandidatesDocuments : 29,
	CreateEditTask : 30,
	CreateEditInterview : 31,
	CreateEditInterviewers : 32,
	CreateEditDeleteCandidateFeedback : 33,
	ViewOrganizationInventory : 34,
	ManagementProduct : 35,
	CreateEditDeleteTags : 36,
	ViewAllEmails : 37,
	ViewAllEmailsTemplates : 38,
	EditOrganizationHelpCenter : 39,
	ViewSalesPipelines : 40,
	EditSalesPipelines : 41,
	ApproveTimesheet : 42,
	CreateEditSprints : 43,
	ViewSprints : 44,
	CreateEditProjects : 45,
	CreateEditContacts : 46,
	ViewContacts : 47,
	CreateEditTeams : 48,
	CreateEditContracts : 49,
	ViewEventTypes : 50,
	AccessTimeTracker : 51,
	ViewInventoryGallery : 52,
	EditInventoryGallery : 53,
	ViewOrganizationEquipment : 54,
	EditOrganizationEquipment : 55,
	ViewOrganizationEquipmentSharing : 56,
	EditOrganizationEquipmentSharing : 57,
	RequestMakeEquipmentMake : 58,
	RequestApproveEquipment : 59,
	ViewOrganizationProductTypes : 60,
	ViewOrganizationProductCategories : 61,
	EditOrganizationProductCategories : 62,
	ViewAllAccountingTemplates : 63,
	ViewOrganizationEmployees : 64,
	CreateEditDeleteOrganizationEmployees : 65,
	ViewOrganizationCandidates : 66,
	CreateEditDeleteOrganizationCandidates : 67,
	ViewOrganizationUsers : 68,
	CreateEditDeleteOrganizationUsers : 69,
	ViewAllOrganizations : 70,
	CreateEditDeleteAllOrganizations : 71,
	ChangeSelectedEmployee : 72,
	ChangeSelectedCandidate : 73,
	ChangeSelectedOrganization : 74,
	ChangeRolesAndPermissions : 75,
	EditSuperAdminUsers : 76,
	EditOrganizationPublicPage : 77,
	ViewOrganizationInventoryAdmin : 78,
	ManagementProductAdmin : 79,
	EditApprovalsPolicyAdmin : 80,
	ViewApprovalsPolicyAdmin : 81,
	EditTimeOffAdmin : 82,
	EditApprovalRequestAdmin : 83,
	ViewApprovalRequestAdmin : 84,
	TenantAddUserToOrganization : 85,
	ViewIntegrations : 86,
	ViewFileStorage : 87,
	ViewPaymentGateway : 88,
	ViewSMSGateway : 89,
	ViewCustomSMTP : 90,
	ViewImportExport : 91,
	ViewJobEmployees : 92,
	ViewJobMatching : 93,
	ViewInventoryGalleryAdmin : 94,
	ViewOrganizationEquipmentAdmin : 95,
	ViewOrganizationEquipmentSharingAdmin : 96,
	ViewOrganizationProductTypesAdmin : 97,
	ViewOrganizationProductCategoriesAdmin : 98,
	MigrateIntoGauzyCloud : 99,
	AccessDeleteAccount : 100,
	AccessDeleteAllData : 101
};
