export const SettingsButtonData = {
	themeButtonLight: 'Light',
	themeButtonDark: 'Dark',
	themeButtonCosmic: 'Cosmic',
	themeButtonCorporate: 'Corporate',
	languageEnglish: 'English',
	languageBulgarian: 'Bulgarian',
	languageHebrew: 'Hebrew',
	changeLangHebrew: 'Иврит',
	changeLangRussian: 'Руски',
	languageRussian: 'Russian',
	layoutGrid: 'Cards Grid',
	layoutTable: 'Table',
	layoutSprint: 'Sprint View',
	headerEnglish: 'Employee Statistics',
	headerRussian: 'Статистика сотрудников',
	headerBulgarian: 'Статистика на служителите',
	headerHebrew: 'סטטיסטיקת עובדים',
	lightTheme: 'nb-theme-default',
	darkTheme: 'nb-theme-dark',
	cosmicTheme: 'nb-theme-cosmic',
	corporateTheme: 'nb-theme-corporate'
};
