version: '3.8'

services:
  proxy:
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      CERTBOT_EMAIL: "ever@ever.tech"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - with-letsencrypt_overlay
    volumes:
      - ./demo.conf.d:/etc/nginx/user.conf.d:ro
volumes:
  certificates: {}

networks:
  with-letsencrypt_overlay:
    external: true
      
