version: '3.8'

services:
  proxy:
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      - CERTBOT_EMAIL
    env_file:
      - ./nginx-certbot.env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - with-letsencrypt_overlay
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./stage.conf.d:/etc/nginx/user.conf.d:ro
volumes:
  nginx_secrets: {}
  certificates: {}

networks:
  with-letsencrypt_overlay:
    external: true
      
