/**
 * DO NOT EDIT BY HAND.
 *
 * Generated by packages/plugins/legal-ui/scripts/sync-legal-content.mjs from
 * @ever-co/legal@0.1.0 (content/cookies/gauzy/en.html).
 *
 * The document's title, version and effective date come from the corpus index and are rendered
 * by the page header, so the corresponding front-matter lines are not repeated in `html`.
 *
 * Run `node packages/plugins/legal-ui/scripts/sync-legal-content.mjs --fetch` to refresh.
 */
import { ILegalDocument } from '../models/legal-document.model';

export const LEGAL_COOKIES_EN: ILegalDocument = {
	document: 'cookies',
	product: 'gauzy',
	productName: 'Ever Gauzy',
	domain: 'gauzy.co',
	entity: 'Ever Technologies LTD',
	entityId: 'ever-technologies-bg',
	locale: 'en',
	version: '1.0.0',
	effectiveDate: '2026-08-02',
	sha256: '61eea69d44ce770c8255fcb17567a7204de8765f43c7d6d983b4ac33d250710e',
	title: 'Cookie Policy',
	html: `<h2 id="what-this-policy-covers" tabindex="-1">What this policy covers</h2>
<p>This Cookie Policy explains the cookies and similar technologies we use on
<a href="https://gauzy.co">gauzy.co</a> and in Ever Gauzy Cloud — the public website, the documentation,
the signed-in application, and any desktop or mobile application we publish for it. The product-specific
section below lists what is actually in use on each of those surfaces.</p>
<p>It sits alongside our <a href="https://gauzy.co/privacy">Privacy Policy</a>. The two documents answer different
questions, and it is worth knowing which one you are reading:</p>
<ul>
<li><strong>This policy is about your device.</strong> What we store on it, what we read back from it, why, and how you
control that.</li>
<li><strong>The <a href="https://gauzy.co/privacy">Privacy Policy</a> is about the information itself.</strong> What we do with personal
data once we hold it, the lawful basis for each purpose, who receives it, how long we keep it, and the
rights you can exercise over it.</li>
</ul>
<p>Where something described here involves personal data, the Privacy Policy governs that processing.
<strong>Nothing in this policy narrows the rights that document gives you.</strong></p>
<h3 id="what-this-policy-does-not-cover" tabindex="-1">What this policy does not cover</h3>
<p><strong>Other people's sites and services.</strong> Our pages link to third-party sites, and our Service connects to
third-party tools when you ask it to. Once you are on someone else's site, their cookie notice applies, not
ours. We have no control over what they store on your device.</p>
<p><strong>Your own workspace, your own site, your own people.</strong> Where you use the Service as a customer to run
something of your own — a workspace for your organisation, or a site we provision for you — the pages you
publish and the people you invite are yours. <strong>This policy is not your cookie notice to your own visitors or
personnel, and our banner is not your consent mechanism.</strong> Providing those is your responsibility, on your
own domain, under your own control.</p>
<p><strong>A copy you run yourself.</strong> Where the software behind the Service is published as open source and you run
your own deployment, this policy describes the service <em>we</em> operate — not yours. You choose what your
deployment loads and what it stores on your users' devices, and only you can describe it to them.</p>
<h2 id="cookies-and-the-other-technologies-that-behave-like-them" tabindex="-1">Cookies and the other technologies that behave like them</h2>
<p>A <strong>cookie</strong> is a small text file that a website asks your browser to keep and hands back to a server on
later requests. It is the oldest way of doing this, and the best known — but it is only one of several, and
the rules that matter here do not turn on which one is used.</p>
<p><strong>The law we work to attaches to storing information on your device or reading information back from it,
whatever the mechanism.</strong> So wherever this policy says &quot;cookies&quot;, read it as covering all of the following.</p>
<h3 id="the-technologies" tabindex="-1">The technologies</h3>
<ul>
<li><strong>Cookies</strong> — as above. Set by the site you are visiting, or by another provider whose code runs on the
page.</li>
<li><strong>Local storage and session storage</strong> — key-value storage inside your browser. Larger than a cookie, not
sent automatically with every request, and it can hold exactly the same kind of identifier.</li>
<li><strong>IndexedDB and the browser cache</strong> — structured storage and cached files. Ordinarily used to make pages
load faster and to let parts of the Service work offline, but capable of holding an identifier too.</li>
<li><strong>Pixels, beacons and tags</strong> — a tiny image or a short script whose only job is to load. The act of
loading it tells the provider that a page was opened, or an email read, along with your IP address and
browser details. A pixel often stores nothing at all and still reports on you.</li>
<li><strong>Tracking parameters in links</strong> — identifiers added to a URL so that a click can be attributed to the
campaign or message that produced it.</li>
<li><strong>SDK identifiers in desktop and mobile applications</strong> — an installed application has no cookie jar. It
stores identifiers in its own application storage instead, and may use identifiers the operating system
provides: an advertising identifier, an installation identifier, or a push notification token.</li>
<li><strong>Device and network characteristics</strong> — your IP address, screen size, language, time zone, fonts and
browser version. Individually unremarkable; combined, they can form a <strong>fingerprint</strong> that recognises a
device without storing anything on it.</li>
</ul>
<h3 id="first-party-and-third-party" tabindex="-1">First-party and third-party</h3>
<p><strong>First-party</strong> means we set it, on our own domain, and it goes to our servers.</p>
<p><strong>Third-party</strong> means it belongs to another company whose code we have chosen to run on the page — an
analytics provider, an embedded video player, a bot-protection service. Their technology reports to them,
not to us, and they decide what it does. Note the awkward part plainly: <strong>a third-party resource embedded in
our page discloses your IP address, your browser and the page you were on to that provider, even when it
stores nothing on your device at all.</strong> Loading it is the disclosure.</p>
<p>Some third-party technologies are deliberately set up to look first-party — served from a subdomain of ours,
or routed through our own servers. Where we do that, we say so in the table below rather than letting the
appearance stand.</p>
<h3 id="session-and-persistent" tabindex="-1">Session and persistent</h3>
<p><strong>Session</strong> items are discarded when you close the browser or the application. They are typically what keeps
you signed in and moving through a single visit.</p>
<p><strong>Persistent</strong> items survive until they expire or you delete them, which is what lets us recognise a
returning visitor, remember your preferences, or remember that you refused something. Each entry in the
table below states how long it lasts.</p>
<h2 id="why-we-use-them" tabindex="-1">Why we use them</h2>
<p>There are six reasons, and each one maps to one of the categories in the next section. We have written the
category next to each so you can see immediately which ones you control.</p>
<ul>
<li><strong>To sign you in and keep you signed in.</strong> Your session has to be attached to the right account, the right
workspace and the right organisation as you move between pages, and it has to be protected against being
replayed or forged by someone else. → <em>strictly necessary</em></li>
<li><strong>To keep the Service secure.</strong> Telling a person apart from an abusive script, protecting forms against
automated submission, enforcing rate limits, and detecting fraudulent sign-ups and payments.
→ <em>strictly necessary</em></li>
<li><strong>To make the Service work at all.</strong> Routing your request to a healthy server, keeping you on the same one
where a feature requires it, balancing load, and serving the right version of the application.
→ <em>strictly necessary</em></li>
<li><strong>To remember what you decided about cookies.</strong> Your choice has to be stored somewhere, or we would have
to ask you on every page. → <em>strictly necessary</em></li>
<li><strong>To remember your preferences.</strong> Language, time zone, theme, layout, a panel you collapsed, a message you
dismissed, and whether you want the support widget open. → <em>functional</em></li>
<li><strong>To understand how the Service is used.</strong> Which pages and features people actually use, which paths fail,
and where things are slow — so that we improve the right things rather than the ones we happen to notice.
→ <em>analytics</em></li>
<li><strong>To measure our marketing.</strong> Whether a campaign reached anyone, which content leads to sign-ups, and
which organisations show interest in the product. → <em>marketing</em></li>
</ul>
<p>Two things follow from that list, and we would rather state them than leave them implied.</p>
<p><strong>Only the first four are needed for the Service to function.</strong> Everything in the last three groups is
optional. If you refuse all of it, every feature you are entitled to still works, at the same price.</p>
<p><strong>Where we can achieve a purpose without storing anything on your device, we do.</strong> That is the whole reason
our own analytics is built the way it is — see the section on analytics without consent below.</p>
<h2 id="the-four-categories-we-use" tabindex="-1">The four categories we use</h2>
<p>Every entry in the table below belongs to exactly one of these four categories. The banner and the
preference centre use the same four names, so what you agree to and what this policy describes are the same
thing.</p>
<h3 id="1-strictly-necessary-no-consent-because-the-service-cannot-run-without-them" tabindex="-1">1. Strictly necessary — no consent, because the Service cannot run without them</h3>
<p>These are the ones we set because you asked for a service that cannot be delivered otherwise. They are not
optional, they are not used for analytics or marketing, and there is no switch for them in the preference
centre. If you block them at the browser level, parts of the Service will stop working.</p>
<ul>
<li><strong>Session and authentication</strong> — signing you in, keeping you signed in, refreshing your session, and
binding it to the correct account, workspace and organisation.</li>
<li><strong>Security</strong> — protection against cross-site request forgery, detection of abusive automated traffic, rate
limiting, and fraud prevention on sign-up and payment.</li>
<li><strong>Load balancing and routing</strong> — sending your request to a healthy server and keeping you there where a
feature needs it.</li>
<li><strong>Your consent choice</strong> — storing what you decided, so that we can honour it and stop asking.</li>
</ul>
<p>Error and crash diagnostics are <strong>not</strong> in this category by default. Where we use a diagnostics tool that
records more than a technical error — a reconstruction of what was on your screen, for example — it is
listed under analytics and it waits for your consent.</p>
<h4 id="recaptcha-is-in-this-category-and-here-is-our-reasoning" tabindex="-1">reCAPTCHA is in this category, and here is our reasoning</h4>
<p>We use Google reCAPTCHA — and on some surfaces an alternative provider, named in the table below — to stop
automated abuse of forms such as sign-up, password reset and contact. <strong>We treat it as strictly necessary,
which means it loads without asking you first.</strong></p>
<p>The reason is that it protects the specific form you are trying to use. You cannot meaningfully ask for the
form and refuse the protection on it: without it, those endpoints are abused within hours, which is a
security failure that harms you as much as us.</p>
<p>What that means in practice, stated plainly:</p>
<ul>
<li>It collects device and behaviour signals from your browser — mouse and touch movement, timing, browser and
device characteristics, and your IP address — and <strong>sends them to Google, which acts as its own controller
for that data under its own privacy notice.</strong></li>
<li>We load it only on pages carrying a protected form. It is not present across the whole site.</li>
<li>Where an equivalent provider is available on a surface, we prefer the one that collects less.</li>
</ul>
<p><strong>Not every data protection authority accepts that a bot-protection service belongs in the strictly
necessary category.</strong> We think it does, for the reason above, and we would rather publish the reasoning and
let you judge it than bury the tool in a list. If you would prefer not to submit a form protected this way,
write to privacy@ever.co and we will take it from you another way.</p>
<h3 id="2-functional-and-preferences-consent-required" tabindex="-1">2. Functional and preferences — consent required</h3>
<p>These remember choices you have made so that the Service behaves the way you left it: language, time zone,
theme, layout, dismissed messages, and support or chat widgets where we offer them.</p>
<p><strong>Refusing this category costs you convenience, not access.</strong> Everything still works; it simply forgets your
preferences between visits and you set them again.</p>
<h3 id="3-analytics-consent-required" tabindex="-1">3. Analytics — consent required</h3>
<p>These tell us how the Service is used: which pages and features are used, which paths people abandon, what
is slow, and what fails. Depending on the surface this may include a provider's own persistent identifier
and, where the table says so, a masked reconstruction of a session.</p>
<p>Third-party analytics tools are <strong>off until you turn them on</strong>, and nothing in this category loads before you
choose.</p>
<p>There is one deliberate exception, and it is the subject of the next section: <strong>our own analytics, running on
our own servers, is designed to operate without a consent requirement</strong> — cookieless, with no persistent
identifier and aggregate reporting only. The next section sets out exactly what that involves and the
conditions it depends on.</p>
<h3 id="4-marketing-consent-required" tabindex="-1">4. Marketing — consent required</h3>
<p>These measure whether our marketing works and help us understand who is interested in the product:
attribution of a sign-up to the campaign that produced it, and business-audience identification tools.</p>
<p>One of these deserves a plain sentence rather than a euphemism. <strong>Visitor identification tools resolve a
visitor's IP address to the organisation it belongs to, so that we can see which companies have looked at
the product.</strong> They do not tell us your name, but most people do not expect a website to work out their
employer, so we would rather say it here than let you find it in a table. It is off unless you consent.</p>
<h3 id="no-cookie-walls-ever" tabindex="-1">No cookie walls, ever</h3>
<p><strong>We do not use cookie walls, and we never make access conditional on consenting to non-essential cookies.</strong></p>
<p>You can refuse everything except the strictly necessary category and the whole of the Service remains
available to you — the same features, the same content, the same price. We do not offer a &quot;consent or pay&quot;
alternative. We do not degrade the experience, hide content, or nag you on every page because you said no.
Refusing is a decision we record and respect, not a negotiating position.</p>
<h2 id="our-own-analytics-and-why-it-runs-without-asking-you" tabindex="-1">Our own analytics, and why it runs without asking you</h2>
<p>We want to know whether the Service works — which pages load, which fail, whether a change made things
better or worse. That is a legitimate thing for us to want, and it is also the reason most websites hand
their visitors to a third-party analytics company. <strong>We built ours the other way round: we run our own
analytics software, on our own servers, in our own infrastructure, and it is designed so that there is
nothing about you worth asking permission for.</strong> No third-party analytics vendor receives this data. The
table below names the software and where it runs.</p>
<h3 id="what-it-does-and-what-it-deliberately-does-not-do" tabindex="-1">What it does, and what it deliberately does not do</h3>
<ul>
<li><strong>It sets no cookies.</strong> Nothing is written to your device — no cookie, no local storage entry, nothing.</li>
<li><strong>It creates no persistent identifier.</strong> There is no visitor ID that follows you from one day to the next.</li>
<li><strong>It does not track you across sites or across devices.</strong> It measures our own site only. It has no
presence anywhere else, so there is nothing to join up.</li>
<li><strong>It counts visits using a hash that is salted and rotated daily.</strong> A one-way value is derived from your
IP address and browser details together with a secret salt, purely to tell one visit apart from another
within a single day. <strong>We change the salt every day, which breaks the link between today's value and
tomorrow's by design.</strong> The inputs are not stored.</li>
<li><strong>It reports only in aggregate</strong> — page counts, referrers, countries, browsers. No profile of you, no
individual visitor record to open, nothing to hand to a marketing tool.</li>
<li><strong>It keeps data for a bounded period,</strong> stated in the table below, after which the underlying records go
and only aggregate statistics remain.</li>
<li><strong>It is never used for advertising,</strong> and the data is not sold, shared for anyone else's purposes, or
combined with data from another source.</li>
</ul>
<h3 id="why-this-can-run-without-consent-and-the-condition-attached" tabindex="-1">Why this can run without consent, and the condition attached</h3>
<p>Under the ePrivacy rules, storing information on your device or reading it back generally requires your
prior consent, with a narrow exemption for what is strictly necessary. European regulators — the French CNIL
most explicitly — have also published criteria under which a first-party audience-measurement tool can be
treated as exempt: it must serve only the operator's own site, produce only aggregate statistics, avoid
cross-site and cross-device tracking, avoid a persistent identifier, and keep data for a limited period.</p>
<p><strong>Our configuration is built to meet those criteria. That is the whole basis on which it runs without
asking you — and it is conditional on every one of the measures listed above.</strong></p>
<p>We are not claiming a general permission. If we ever changed any of it — a persistent identifier, a fixed
salt, measurement across more than one of our own sites, a third-party vendor, reporting at the level of an
individual visitor — <strong>the exemption would no longer apply, and we would move this tool into the analytics
category and ask for your consent before making the change.</strong> The category is a configuration setting in our
consent system, not a paragraph in this document, precisely so that it can be changed the moment the facts
change.</p>
<p>One further distinction worth being precise about. The exemption above is about <strong>storage on your device</strong>.
Where the resulting data is still personal data, the separate question of a lawful basis under data
protection law arises, and ours is our legitimate interest in understanding whether our own service works —
assessed against the fact that the measurement is aggregate, short-lived and cannot be traced back to you.
<strong>You can object to that processing</strong>, and the paragraph below is how.</p>
<h3 id="you-can-switch-it-off-anyway" tabindex="-1">You can switch it off anyway</h3>
<p>You do not have to accept our reasoning to escape the measurement.</p>
<ul>
<li>Open <strong>Cookie preferences</strong> from the footer of any page. Our own analytics appears there with a switch,
even though it runs without consent, and turning it off stops it.</li>
<li>Blocking it at the browser or network level also works, and we do not try to detect or defeat that.</li>
<li>Or write to privacy@ever.co and ask us to exclude you.</li>
</ul>
<p><strong>We do not ask for a reason and we do not require an account.</strong></p>
<h3 id="separately-and-only-with-your-consent-we-also-use-third-party-tools" tabindex="-1">Separately, and only with your consent, we also use third-party tools</h3>
<p>Alongside our own analytics we use third-party analytics and marketing products. Those are a genuinely
different proposition: another company receives the data, they typically use a persistent identifier of
their own, and some are capable of following a visitor across other sites entirely.</p>
<p><strong>Nothing in that group runs until you consent to it</strong>, and none of it is covered by the exemption described
above. Each tool is named in the table below, with what it does, who operates it, and how long anything it
stores lasts.</p>
<h2 id="annex-ever-gauzy" tabindex="-1">Annex: Ever Gauzy</h2>
<h3 id="where-this-applies" tabindex="-1">Where this applies</h3>
<p>This policy covers the gauzy.co website and the web application. <strong>The desktop applications are
a different matter</strong>: they are not browsers and they do not use cookies for tracking. What they capture,
and what governs it, is set out in the privacy annex for this product rather than here.</p>
<h3 id="on-the-website" tabindex="-1">On the website</h3>
<p>The website is where the consent choice is offered. Nothing in the analytics, marketing or preferences
categories runs until you have made one.</p>
<table>
<thead>
<tr>
<th>Purpose</th>
<th>Category</th>
<th>Consent</th>
</tr>
</thead>
<tbody>
<tr>
<td>Session, sign-in and security</td>
<td>Strictly necessary</td>
<td>Not required</td>
</tr>
<tr>
<td>Remembering your cookie choice</td>
<td>Strictly necessary</td>
<td>Not required</td>
</tr>
<tr>
<td>Bot and abuse protection on forms</td>
<td>Strictly necessary</td>
<td>Not required</td>
</tr>
<tr>
<td>Our own self-hosted analytics</td>
<td>Strictly necessary</td>
<td>Not required — see the core section on analytics without consent</td>
</tr>
<tr>
<td>Third-party product and site analytics</td>
<td>Analytics</td>
<td>Required</td>
</tr>
<tr>
<td>Tag management</td>
<td>Analytics</td>
<td>Required</td>
</tr>
<tr>
<td>Business visitor identification</td>
<td>Marketing</td>
<td>Required</td>
</tr>
<tr>
<td>Language and interface preferences</td>
<td>Preferences</td>
<td>Required</td>
</tr>
</tbody>
</table>
<p><strong>Business visitor identification deserves naming rather than burying.</strong> With your consent, a third-party
service attempts to identify the organisation a visitor is connecting from, using the IP address, so that
our sales team knows which companies have shown interest. It is aimed at organisations rather than
individuals, but an IP address is personal data and the inference is drawn from it, so it sits in the
marketing category and runs only on consent. Refuse it and nothing is sent.</p>
<h3 id="in-the-web-application" tabindex="-1">In the web application</h3>
<p>Once you are signed in, the cookies in use are the ones that keep you signed in, keep the session secure,
and remember interface preferences such as language, time zone and time format. These are strictly
necessary or preference cookies for a service you have asked us to provide.</p>
<p><strong>We do not run advertising or cross-site tracking inside the application.</strong> Nothing you do in a workspace
is used to target advertising anywhere, and no advertising network receives data from it.</p>
<h3 id="if-your-employer-runs-ever-gauzy" tabindex="-1">If your employer runs Ever Gauzy</h3>
<p>Cookie consent is about this website and this application in your browser. It has nothing to do with the
desktop monitoring features — refusing analytics cookies here does not switch off screen capture, and
accepting them does not switch it on. Those are configured by your employer and described in the privacy
annex.</p>
<h3 id="changing-your-mind" tabindex="-1">Changing your mind</h3>
<p>The preference centre is reachable from the footer of https://gauzy.co at any time. Withdrawing consent is
as easy as giving it, and takes effect immediately for anything not already loaded.</p>
<h2 id="third-party-cookies-and-the-providers-behind-them" tabindex="-1">Third-party cookies and the providers behind them</h2>
<p>Some of what runs on our pages belongs to other companies. We chose to include it, so we tell you it is
there — but the provider decides what its own technology collects, and for that collection it is usually
acting in its own right and under its own privacy notice rather than ours. Where that is the case, the table
below links to their notice.</p>
<p>These are the kinds of provider involved, and what each kind does.</p>
<h3 id="analytics-providers" tabindex="-1">Analytics providers</h3>
<p>Measure how the Service is used: page views, feature use, funnels, errors and performance. Most set a
persistent identifier of their own so a returning visitor is recognised, and some can record a <strong>session
replay</strong> — a reconstructed, masked playback of what happened on the screen. Where a tool on a surface can do
that, the table says so explicitly.</p>
<p><strong>Consent required.</strong> They do not load until you agree.</p>
<h3 id="tag-management" tabindex="-1">Tag management</h3>
<p>A tag manager is a container we load once, through which other tags can then be delivered without shipping
new code. That flexibility is exactly what makes it worth describing carefully: <strong>a container is a delivery
mechanism, so what it delivers matters more than the container itself.</strong></p>
<p>Every tag we deliver through a container is declared in the table below, in its own category. The container
is consent-gated as a whole, and <strong>we do not use it to deliver anything from a category you have refused.</strong></p>
<p><strong>Consent required.</strong></p>
<h3 id="marketing-and-visitor-identification" tabindex="-1">Marketing and visitor identification</h3>
<p>Campaign measurement and attribution — which advertisement, email or article led to a visit or a sign-up —
and business-audience identification, which resolves a visitor's IP address to the organisation that holds
it so we can see which companies are interested in the product. It gives us a company, not your name. Most
people still do not expect it, which is why it is named here as well as in the table.</p>
<p><strong>Consent required.</strong></p>
<h3 id="video-maps-fonts-and-other-embedded-content" tabindex="-1">Video, maps, fonts and other embedded content</h3>
<p>Where a page embeds something served from another provider's network — a video player, a map, a code
sandbox, a font, a script from a public content delivery network — your browser fetches it directly from
that provider.</p>
<p><strong>That fetch discloses your IP address, your browser and the page you were on to the provider, whether or
not anything is stored on your device.</strong> There is no way to embed a resource and hide the request for it.</p>
<p>We handle this in two ways: where we can serve the asset ourselves, we do, which removes the third party
entirely; and where an embed stores or reads anything on your device, we treat it as <strong>consent required</strong>
and it does not load until you agree. Embeds that store nothing but are still fetched from a third party are
listed in the table so you can see the disclosure even where no cookie is involved.</p>
<h3 id="security-and-delivery" tabindex="-1">Security and delivery</h3>
<p>The network in front of our sites — the proxy and content delivery layer that terminates the connection,
absorbs attacks and filters hostile traffic — along with bot protection on forms and fraud checks on
payment. These see connection metadata and may set their own security cookies.</p>
<p><strong>Strictly necessary</strong>, and therefore not consent-gated. Our reasoning for putting bot protection in that
category, including what it sends to its provider, is set out in the categories section above.</p>
<h3 id="where-these-providers-are-and-where-to-find-the-full-list" tabindex="-1">Where these providers are, and where to find the full list</h3>
<p>Some of these providers are established outside the European Economic Area, and using them involves an
international transfer of personal data. <strong>The transfers section of our
<a href="https://gauzy.co/privacy">Privacy Policy</a> sets out the destinations and the safeguards we rely on for each</strong>,
and you can ask us for a copy of those safeguards.</p>
<p>Two lists keep this current, and between them they are the authoritative answer:</p>
<ul>
<li><strong>The table in the product-specific section below</strong> names every cookie and similar technology in use on
this product's surfaces — the provider, whether it is first- or third-party, its category, its purpose,
how long it lasts, and a link to the provider's own notice.</li>
<li><strong>Our Sub-processor List</strong> covers the wider set of providers that process personal data for us, including
the many that never touch your device at all. You can obtain the current version at any time from
privacy@ever.co, and it names the sub-processor, what it does, and where it processes.</li>
</ul>
<p>We update both when a provider is added, removed or changed. If you find something on our pages that is not
in either list, tell us at privacy@ever.co — that is a defect and we will fix it.</p>
<h2 id="consent-and-how-to-withdraw-it" tabindex="-1">Consent, and how to withdraw it</h2>
<h3 id="how-the-banner-works" tabindex="-1">How the banner works</h3>
<p>On your first visit we show a consent banner, and <strong>nothing in the functional, analytics or marketing
categories is written to or read from your device until you have made a choice.</strong> The strictly necessary
items load, because the page cannot be delivered otherwise. Everything else waits.</p>
<p>The first layer of the banner — the one you see without clicking anything further — carries both a
<strong>Reject all</strong> and an <strong>Accept all</strong> control, presented with equal prominence. <strong>Refusing everything takes
one click, exactly like accepting everything.</strong> Alongside them is a route into per-category choice, so you
can accept analytics and refuse marketing, or any other combination.</p>
<p>Three things that some banners do and ours does not:</p>
<ul>
<li><strong>No pre-ticked boxes.</strong> Every category except strictly necessary starts switched off.</li>
<li><strong>Closing the banner is not consent.</strong> Neither is dismissing it, scrolling past it, or carrying on
browsing. If you do not make a choice, nothing optional is set — you simply have not decided yet.</li>
<li><strong>No dark patterns.</strong> We do not make the reject control smaller, greyer, slower or harder to find than the
accept control, and we do not hide it a layer down.</li>
</ul>
<h3 id="changing-your-mind-1" tabindex="-1">Changing your mind</h3>
<p><strong>Withdrawing consent is as easy as giving it, and you can do it at any time.</strong></p>
<p>There is a persistent <strong>Cookie preferences</strong> link in the footer of every page, and an equivalent entry
inside the application's settings. It opens the same per-category controls you saw in the banner, showing
what you currently allow. Change a switch and it takes effect immediately: we stop, and where we can, we
remove what was stored.</p>
<p>Two honest limits on that:</p>
<ul>
<li><strong>Withdrawal works forwards, not backwards.</strong> It does not make lawful past processing unlawful, and it
does not reach into data a third-party provider already received. If you want that deleted too, ask us at
privacy@ever.co and we will tell you who holds it and how to ask them.</li>
<li><strong>Your choice is stored on the device and browser you made it on.</strong> A different browser, a different
device or a private window will ask again, because there is nothing there to read. Clearing your browser
storage deletes the record of your refusal as well, which is why the banner reappears afterwards.</li>
</ul>
<h3 id="the-record-we-keep" tabindex="-1">The record we keep</h3>
<p>When you make a choice we record what you chose, when you chose it, which categories it covered, and which
version of this policy was in force at the time. That record exists for two reasons: so that we honour your
choice, and so that we can show what you were asked and what you answered.</p>
<p>You can ask us for a copy of your own consent record at privacy@ever.co.</p>
<h3 id="how-long-a-choice-lasts-before-we-ask-again" tabindex="-1">How long a choice lasts before we ask again</h3>
<p>We store a consent choice for <strong>six months</strong>. After that the banner appears again so you can confirm or
change it. We will also ask again sooner if we add a purpose or a category your earlier choice did not
cover, or if this policy changes in a way that materially affects what you agreed to.</p>
<p><strong>This is our own practice, not a legal requirement.</strong> There is no EU-wide statutory interval for asking
again — six months follows regulator guidance we consider sensible and proportionate, and we have chosen to
apply it. If you would rather not be asked at all, refusing everything is a decision we keep for the same
six months, and blocking storage at the browser level stops the question permanently.</p>
<h2 id="controls-in-your-browser-and-on-your-device" tabindex="-1">Controls in your browser and on your device</h2>
<p>Our banner is not the only way to control this, and it is not the strongest one. Your browser and your
operating system can enforce a choice on every site at once, including ours.</p>
<h3 id="in-a-browser" tabindex="-1">In a browser</h3>
<p>Every major browser — Chrome, Firefox, Safari, Edge and the rest — offers the same set of controls, under
privacy or site settings:</p>
<ul>
<li><strong>Delete cookies and site data</strong>, for one site or all of them.</li>
<li><strong>Block cookies</strong>, either all of them or only those set by third parties.</li>
<li><strong>Clear storage on exit</strong>, so nothing survives the session.</li>
<li><strong>Private or incognito windows</strong>, which discard everything when the window closes.</li>
<li><strong>Per-site permissions</strong>, so you can allow storage on the sites you use and block it everywhere else.</li>
</ul>
<p>Your browser's own help pages describe exactly where these live in your version — we deliberately do not
reproduce click-by-click instructions here, because they go stale faster than this document does.</p>
<p>Content blockers and privacy extensions work on our sites too. <strong>Using one is a legitimate choice</strong>, and we
build the Service so that it keeps working when the optional things are blocked.</p>
<h3 id="in-our-desktop-and-mobile-applications" tabindex="-1">In our desktop and mobile applications</h3>
<p>An installed application has no browser settings to change, so the controls are at the operating-system
level instead:</p>
<ul>
<li>Reset or limit the <strong>advertising identifier</strong> your device provides.</li>
<li>Answer <strong>no</strong> to the app-tracking permission prompt on iOS, which stops access to that identifier
entirely.</li>
<li>Withdraw <strong>notification permission</strong>, which stops the push token being useful.</li>
<li>Clear the application's stored data, or uninstall it, which removes everything it kept locally.</li>
</ul>
<p>The <strong>Cookie preferences</strong> controls described above are also available inside the application, and they
govern the same categories there as on the website.</p>
<h3 id="what-breaks-if-you-block-the-strictly-necessary-ones" tabindex="-1">What breaks if you block the strictly necessary ones</h3>
<p>Blocking the optional categories breaks nothing. Blocking storage entirely does, and you should know what to
expect:</p>
<ul>
<li><strong>You will not be able to sign in, or stay signed in.</strong> Authentication needs somewhere to keep the
session.</li>
<li><strong>Forms may fail their security check</strong> and refuse to submit.</li>
<li><strong>Some features will behave inconsistently</strong>, because requests can no longer be kept on the same server.</li>
<li><strong>We cannot remember that you refused.</strong> The record of your choice is itself stored on your device, so
blocking storage means the banner returns on every visit — the one genuinely irritating consequence, and
it comes from the mechanism rather than from us being difficult.</li>
</ul>
<h3 id="do-not-track" tabindex="-1">Do Not Track</h3>
<p>Browsers once offered a <strong>Do Not Track</strong> header, and some still do. <strong>We do not treat it, on its own, as a
refusal</strong> — and we would rather explain why than quietly ignore it.</p>
<p>No consistent standard was ever agreed for what a site should do on receiving it. It was never clear whether
it expressed a considered decision or a default someone else had set, browsers behaved differently, and
several have withdrawn it. A signal we cannot interpret is not a safe basis for deciding what you want.</p>
<p>Use the banner or the preference centre instead. A choice made there is unambiguous, and we record it.</p>
<h3 id="global-privacy-control" tabindex="-1">Global Privacy Control</h3>
<p><strong>Global Privacy Control (GPC)</strong> is the later, better-specified signal, and unlike Do Not Track it is
defined to express an actual opt-out rather than a preference.</p>
<p><strong>Where we receive a GPC signal from your browser, we treat it as a refusal of the analytics and marketing
categories</strong> on that browser, and we act on it without waiting for you to interact with a banner.</p>
<p>Two points of detail:</p>
<ul>
<li>It applies to the browser or device sending it. Another browser sends its own signal, or none.</li>
<li><strong>An explicit choice you make later in our preference centre takes precedence</strong>, in either direction. If
you switch a category on there while GPC is enabled, we treat that as your decision, and we record it as
such. If you would rather that never happened, leave the categories switched off.</li>
</ul>
<h2 id="changes-to-this-policy" tabindex="-1">Changes to this policy</h2>
<p>We update this policy when what we do changes — a provider added or removed, a technology retired, a
category reassigned. Every update gets its own version number and effective date, recorded at the end of
this document.</p>
<p><strong>Where a change materially affects what you agreed to</strong> — a new purpose, a new category, or a tool moving
out of the strictly necessary or exempt group — <strong>we ask for your consent again rather than relying on the
choice you made against the old text.</strong> Corrections, clarifications and provider renames are published with
a new version and no fresh request.</p>
<p>Earlier versions stay available, with the dates each was in force, at
<a href="https://gauzy.co/cookies">https://gauzy.co/cookies</a>. The effective date shown with this policy tells you which
version applies today.</p>
<h2 id="how-to-reach-us" tabindex="-1">How to reach us</h2>
<p>Questions about this policy, about anything in the table above, or about a choice you have made — write to
privacy@ever.co. That address is monitored and we answer it. Ask us for a copy of your own consent
record, for the current sub-processor list, or to be excluded from our own analytics, and we will do it
without asking why.</p>
<p>By post: <strong>Ever Technologies LTD</strong>, Mladost 2, bl. 211, ent. A, Sofia 1799, Bulgaria — registered in Bulgaria under company
number 204599535. We correspond in English.</p>
<p>If you think we have handled your data badly, tell us first — we would rather fix it. <strong>You can also
complain to a data protection supervisory authority at any time.</strong> Ours is the
Commission for Personal Data Protection (Комисия за защита на личните данни), the CPDP, at
<a href="https://www.cpdp.bg/">https://www.cpdp.bg/</a>. You may instead complain
to the authority for the country where you live or work.</p>
<p>This document is version 1.0.0 of the Cookie Policy for
<a href="https://gauzy.co">gauzy.co</a>, in force from 2026-08-02. Earlier versions, with the dates
they applied, are at <a href="https://gauzy.co/cookies">https://gauzy.co/cookies</a>.</p>
`
};
