import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString, Length, Matches } from 'class-validator';
import { TenantOrganizationBaseDTO } from '@gauzy/core';

/**
 * DTO for completing a provider "Connect" flow (e.g. OpenRouter PKCE).
 *
 * The browser is sent to the provider's authorize page with a PKCE
 * challenge; the provider redirects back with a one-time `code`. The
 * backend exchanges `code` + `codeVerifier` for an API key server-side
 * (the key never passes through the browser) and stores it as the
 * tenant's BYOK credential.
 */
export class ConnectAiProviderCredentialDTO extends TenantOrganizationBaseDTO {
	@ApiProperty({ type: () => String, description: 'AI provider identifier (must support a connect flow)' })
	@IsNotEmpty({ message: 'Provider id is required' })
	@IsString({ message: 'Provider id must be a string' })
	@Matches(/^[a-z0-9][a-z0-9._-]*$/i, {
		message: 'Provider id can only contain letters, numbers, dots, underscores, and hyphens'
	})
	providerId: string;

	@ApiProperty({ type: () => String, description: 'One-time authorization code returned by the provider' })
	@IsNotEmpty({ message: 'Authorization code is required' })
	@IsString({ message: 'Authorization code must be a string' })
	@Length(1, 2048, { message: 'Authorization code must be between 1 and 2048 characters' })
	code: string;

	@ApiProperty({ type: () => String, description: 'PKCE code verifier generated by the client before authorizing' })
	@IsNotEmpty({ message: 'Code verifier is required' })
	@IsString({ message: 'Code verifier must be a string' })
	@Length(43, 128, { message: 'Code verifier must be between 43 and 128 characters (RFC 7636)' })
	codeVerifier: string;
}
