import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsDateString, IsEnum, IsInt, IsOptional, IsString, IsUUID, Min } from 'class-validator';
import { EventOutboxStatus, ID, IEventOutbox, JsonData } from '@gauzy/contracts';
import { TenantOrganizationBaseEntity } from '../core/entities/internal';
import { ColumnIndex, JsonColumn, MultiORMColumn, MultiORMEntity } from '../core/decorators/entity';
import { ColumnNumericTransformerPipe } from '../shared/pipes';
import { MikroOrmEventOutboxRepository } from './repository/mikro-orm-event-outbox.repository';

/**
 * The transactional outbox.
 *
 * A state change and its event are written in one transaction; dispatch happens afterwards, so an
 * event can never be lost by a process crash between the commit and the publish. The row is written
 * **last** inside the caller's transaction, which is what makes a rollback remove the event too.
 *
 * `sequence` is allocated inside the same transaction and is monotonic within `partitionKey`, so
 * consumers see one aggregate's events in order and can detect a gap across a restart.
 */
@MultiORMEntity('event_outbox', { mikroOrmRepository: () => MikroOrmEventOutboxRepository })
export class EventOutbox extends TenantOrganizationBaseEntity implements IEventOutbox {
	/**
	 * Stable event identity.
	 *
	 * Generated by the writer rather than by the database, because the caller needs the id in the
	 * same transaction that stores the event, and because it is the id the delivery records and the
	 * webhook signature carry.
	 */
	@ApiProperty({ type: () => String })
	@IsUUID()
	@ColumnIndex()
	@MultiORMColumn({ type: 'uuid' })
	eventId: ID;

	/**
	 * `<aggregate>.<action>`, for example `order.placed`.
	 */
	@ApiProperty({ type: () => String })
	@IsString()
	@MultiORMColumn({ type: 'varchar', length: 160 })
	eventName: string;

	/**
	 * The aggregate that changed, for example `order`.
	 */
	@ApiProperty({ type: () => String })
	@IsString()
	@ColumnIndex()
	@MultiORMColumn({ type: 'varchar', length: 64 })
	aggregateType: string;

	/**
	 * Id of the aggregate that changed.
	 */
	@ApiProperty({ type: () => String })
	@IsUUID()
	@ColumnIndex()
	@MultiORMColumn({ type: 'uuid' })
	aggregateId: ID;

	/**
	 * The event body: a projection, never an entity dump.
	 *
	 * Non-null with an empty-object default, so a consumer never has to guard against a missing body.
	 */
	@ApiProperty({ type: () => Object })
	@JsonColumn<JsonData>({ defaultValue: {} })
	payload: JsonData;

	/**
	 * Correlation id, causation id, actor and channel.
	 */
	@ApiPropertyOptional({ type: () => Object })
	@IsOptional()
	@JsonColumn<JsonData>({ nullable: true })
	headers?: JsonData;

	/**
	 * Where dispatch stands.
	 */
	@ApiProperty({ type: () => String, enum: EventOutboxStatus })
	@IsEnum(EventOutboxStatus)
	@MultiORMColumn({ type: 'varchar', default: EventOutboxStatus.PENDING })
	status: EventOutboxStatus;

	/**
	 * Dispatch attempts.
	 */
	@ApiProperty({ type: () => Number, default: 0 })
	@IsInt()
	@Min(0)
	@MultiORMColumn({ type: 'int', default: 0 })
	attemptCount: number;

	/**
	 * Earliest dispatch time.
	 *
	 * The lease and the backoff are the same column: claiming a batch pushes it forward by the lease
	 * window, so a dispatcher that dies mid-pass leaves rows that another worker picks up once the
	 * window expires, with no extra locking column.
	 */
	@ApiProperty({ type: () => Date })
	@IsDateString()
	@ColumnIndex()
	@MultiORMColumn({ type: 'timestamptz' })
	availableAt: Date;

	/**
	 * When dispatch completed.
	 */
	@ApiPropertyOptional({ type: () => Date })
	@IsOptional()
	@IsDateString()
	@MultiORMColumn({ type: 'timestamptz', nullable: true })
	publishedAt?: Date;

	/**
	 * Last dispatch error.
	 */
	@ApiPropertyOptional({ type: () => String })
	@IsOptional()
	@IsString()
	@MultiORMColumn({ type: 'text', nullable: true })
	lastError?: string;

	/**
	 * Ordering key, normally `<aggregateType>:<aggregateId>`.
	 */
	@ApiPropertyOptional({ type: () => String })
	@IsOptional()
	@IsString()
	@ColumnIndex()
	@MultiORMColumn({ type: 'varchar', length: 128, nullable: true })
	partitionKey?: string;

	/**
	 * Monotonic per `partitionKey`, allocated inside the writing transaction.
	 *
	 * It is a `bigint` and is read through the platform's numeric transformer, because the Postgres
	 * driver hands a bigint back as a string and comparing two of those orders `10` before `9`.
	 */
	@ApiProperty({ type: () => Number, default: 0 })
	@IsInt()
	@Min(0)
	@MultiORMColumn({ type: 'bigint', default: 0, transformer: new ColumnNumericTransformerPipe() })
	sequence: number;
}
