import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Transform, TransformFnParams, Type } from 'class-transformer';
import {
	IsArray,
	IsBoolean,
	IsInt,
	IsObject,
	IsOptional,
	IsString,
	IsUrl,
	IsUUID,
	Max,
	MaxLength,
	Min,
	MinLength,
	ValidateNested
} from 'class-validator';
import { ID, JsonData } from '@gauzy/contracts';
import { parseToBoolean } from '@gauzy/utils';

/**
 * What a caller states when it subscribes an endpoint.
 *
 * **No tenant and no organization is a member**, and that is a statement rather than an omission: the
 * service stamps both from the credential, so a body here would promise a scope the write refuses.
 * Neither is the signing secret: it is generated by the service and answered once, so there is
 * nothing for a caller to choose and no member through which one could be set.
 *
 * The members are exactly the ones `WebhookSubscriptionService.createSubscription` reads. A member the
 * service never looks at would be accepted, validated and then silently dropped, which is worse than
 * a member that is absent.
 */
export class CreateWebhookSubscriptionDTO {
	/**
	 * Operator-facing name.
	 */
	@ApiProperty({ type: () => String, maxLength: 255 })
	@IsString()
	@MinLength(1)
	@MaxLength(255)
	readonly name: string;

	/**
	 * Absolute HTTPS endpoint. The service refuses anything else, and refuses the development escape
	 * outright when the platform runs in production.
	 */
	@ApiProperty({ type: () => String, maxLength: 1024 })
	@IsString()
	@MaxLength(1024)
	@IsUrl({ require_tld: false })
	readonly url: string;

	/**
	 * The event names or patterns the endpoint receives.
	 *
	 * The shape is validated here and the emptiness is not: a subscription that names no event is
	 * refused by the service, which is where the rule and its message live.
	 */
	@ApiProperty({ type: () => [String] })
	@IsArray()
	@IsString({ each: true })
	readonly events: string[];

	/**
	 * The channel the subscription listens to; absent means every channel.
	 */
	@ApiPropertyOptional({ type: () => String })
	@IsOptional()
	@IsUUID()
	readonly channelId?: ID;

	/**
	 * Free-text note for operators.
	 */
	@ApiPropertyOptional({ type: () => String })
	@IsOptional()
	@IsString()
	readonly description?: string;

	/**
	 * Static extra headers sent with every delivery. Non-secret by contract: these are routing hints a
	 * receiver needs, and the service never lets one override a reserved delivery header.
	 */
	@ApiPropertyOptional({ type: () => Object })
	@IsOptional()
	@IsObject()
	readonly headers?: Record<string, string>;

	/**
	 * Contract version the consumer expects, echoed in the delivery headers.
	 */
	@ApiPropertyOptional({ type: () => String, maxLength: 16 })
	@IsOptional()
	@IsString()
	@MaxLength(16)
	readonly apiVersion?: string;

	/**
	 * Operator metadata, including the development-only `allowInsecure` the endpoint check reads.
	 */
	@ApiPropertyOptional({ type: () => Object })
	@IsOptional()
	@IsObject()
	readonly metadata?: JsonData;
}

/**
 * What a caller may change on a subscription that exists.
 *
 * Every member is optional, because the delivered update touches the members the body states and
 * leaves the rest as they are. Four members are deliberately absent: the secret, which has an
 * operation of its own because rotating it is a different decision from editing an endpoint; the
 * failure counters and `disabledAt`, which are the delivery path's record of what the endpoint did;
 * and `isActive`, which is claimed through the enable and disable operations rather than by writing
 * the column, so a caller cannot switch an endpoint on without the reset those operations perform.
 */
export class UpdateWebhookSubscriptionDTO {
	/**
	 * Operator-facing name.
	 */
	@ApiPropertyOptional({ type: () => String, maxLength: 255 })
	@IsOptional()
	@IsString()
	@MinLength(1)
	@MaxLength(255)
	readonly name?: string;

	/**
	 * Absolute HTTPS endpoint.
	 */
	@ApiPropertyOptional({ type: () => String, maxLength: 1024 })
	@IsOptional()
	@IsString()
	@MaxLength(1024)
	@IsUrl({ require_tld: false })
	readonly url?: string;

	/**
	 * The event names or patterns the endpoint receives, replacing the set whole.
	 */
	@ApiPropertyOptional({ type: () => [String] })
	@IsOptional()
	@IsArray()
	@IsString({ each: true })
	readonly events?: string[];

	/**
	 * The channel the subscription listens to. An explicit `null` clears it, which is how a
	 * subscription is widened back to every channel.
	 */
	@ApiPropertyOptional({ type: () => String, nullable: true })
	@IsOptional()
	@IsUUID()
	readonly channelId?: ID | null;

	/**
	 * Free-text note for operators.
	 */
	@ApiPropertyOptional({ type: () => String })
	@IsOptional()
	@IsString()
	readonly description?: string;

	/**
	 * Static extra headers, replacing the set whole.
	 */
	@ApiPropertyOptional({ type: () => Object })
	@IsOptional()
	@IsObject()
	readonly headers?: Record<string, string>;

	/**
	 * Contract version the consumer expects.
	 */
	@ApiPropertyOptional({ type: () => String, maxLength: 16 })
	@IsOptional()
	@IsString()
	@MaxLength(16)
	readonly apiVersion?: string;

	/**
	 * Operator metadata, replaced whole.
	 */
	@ApiPropertyOptional({ type: () => Object })
	@IsOptional()
	@IsObject()
	readonly metadata?: JsonData;
}

/**
 * Why a caller is switching an endpoint off.
 *
 * The reason is kept on the subscription's metadata, so the operator who re-enables it later reads
 * what the last person knew — which is the whole of what this body carries, and why it is a body of
 * its own rather than a query member on the route.
 */
export class DisableWebhookSubscriptionDTO {
	/**
	 * Why the endpoint is being switched off.
	 */
	@ApiPropertyOptional({ type: () => String })
	@IsOptional()
	@IsString()
	readonly reason?: string;
}

/**
 * Reads a filter member stated either as the value itself or as the equality operator.
 *
 * The endpoint table writes its examples in the bracketed operator form — `filter[isActive][eq]=true`
 * — while a hand-written query usually names the member alone, and both arrive here as the same
 * question. Reading them the same way is what keeps the documented spelling from being a request this
 * resource answers with a validation failure.
 *
 * @param value The member as the query string carried it.
 * @returns The boolean it means.
 */
function readEquality(value: unknown): boolean {
	if (value && typeof value === 'object' && !Array.isArray(value)) {
		return parseToBoolean((value as { eq?: unknown }).eq);
	}

	return parseToBoolean(value);
}

/**
 * The narrowing members of the subscription list.
 *
 * Two members and no more, because two are what the endpoint table names for this route: whether the
 * endpoint is switched on, and which channel it listens to. The rest of the row's columns are
 * narrowable through the GraphQL connection's own filter, which is a protocol of its own rather than
 * something a query string can spell.
 */
export class WebhookSubscriptionFilterDTO {
	/**
	 * Restrict to the endpoints that are switched on, or to the ones that are not.
	 */
	@ApiPropertyOptional({ type: () => Boolean })
	@IsOptional()
	@Transform(({ value }: TransformFnParams) => readEquality(value))
	@IsBoolean()
	readonly isActive?: boolean;

	/**
	 * Restrict to the subscriptions listening to one channel.
	 */
	@ApiPropertyOptional({ type: () => String })
	@IsOptional()
	@IsUUID()
	readonly channelId?: ID;
}

/**
 * The query of `GET /webhooks/subscriptions`.
 *
 * Both spellings of the same filter are accepted: the flat one the platform's list routes are called
 * with, and the bracketed one the endpoint table names. The bracketed members win when both are
 * stated, because that is the spelling the specification fixes.
 */
export class WebhookSubscriptionQueryDTO extends WebhookSubscriptionFilterDTO {
	/**
	 * The bracketed spelling of the same two members.
	 */
	@ApiPropertyOptional({ type: () => WebhookSubscriptionFilterDTO })
	@IsOptional()
	@ValidateNested()
	@Type(() => WebhookSubscriptionFilterDTO)
	readonly filter?: WebhookSubscriptionFilterDTO;

	/**
	 * How many subscriptions to answer with.
	 */
	@ApiPropertyOptional({ type: () => Number, minimum: 1, maximum: 100 })
	@IsOptional()
	@Type(() => Number)
	@IsInt()
	@Min(1)
	@Max(100)
	readonly take?: number;

	/**
	 * How many subscriptions to skip.
	 */
	@ApiPropertyOptional({ type: () => Number, minimum: 0 })
	@IsOptional()
	@Type(() => Number)
	@IsInt()
	@Min(0)
	readonly skip?: number;
}
