import { DynamicModule, Type } from '@nestjs/common';
import { GraphQLTypesLoader } from '@nestjs/graphql';
import { getPluginExtensions } from '@gauzy/plugin';
import { isNotEmpty } from '@gauzy/utils';
import * as fs from 'fs';
import { buildSchema, extendSchema, GraphQLSchema, printSchema } from 'graphql';
import * as path from 'path';

/**
 * The committed schema snapshot, and how it is produced.
 *
 * The snapshot is the schema: it is what a client generator reads, what a reviewer diffs, and what
 * the CI gate compares against. That is why it is generated by the SAME pipeline the server boots
 * with — the same loader, the same `buildSchema`, the same `extendSchema` over the plugin
 * contributions, in the same order — rather than by a tool that reads the SDL files its own way.
 * Anything less and the committed file would eventually describe a schema nobody serves.
 *
 * A plugin's SDL is part of the snapshot. A plugin that changes its types without changing its own
 * file is caught by the diff, and a plugin missing from `apps/api/src/plugins.ts` shows up as a
 * removal — which is why the CLI reads the shipped plugin list rather than a fixture.
 *
 * The composition needs no database, no HTTP server and no Nest container: it is SDL in, SDL out.
 * A failure here is therefore always a schema or a plugin-registration error, never an environment
 * problem, and the error names the plugin whose SDL threw.
 */

/** Where the snapshot lives, relative to the repository root. */
export const GRAPHQL_SCHEMA_SNAPSHOT_PATH = 'packages/core/src/lib/graphql/schema/schema.graphql';

/** The source glob the runtime loads its `.gql` files from, relative to the repository root. */
export const GRAPHQL_SCHEMA_SOURCE_GLOB = 'packages/core/src/lib/**/schema/*.gql';

/** Where the shipped plugin list lives, relative to the repository root. */
export const GRAPHQL_PLUGIN_LIST_PATH = 'apps/api/src/plugins.ts';

/** A plugin contribution, as the `@Plugin` decorator declares it. */
export type PluginEntry = Type<any> | DynamicModule;

export interface SchemaSnapshotOptions {
	/** The repository root. Defaults to the first ancestor directory holding an `nx.json`. */
	readonly repositoryRoot?: string;
	/** The globs to merge core SDL from. Defaults to the runtime's own source glob. */
	readonly typePaths?: readonly string[];
}

/**
 * Composes the schema the API serves and returns it as SDL.
 *
 * @param plugins - The shipped plugin list, exactly as `apps/api/src/plugins.ts` exports it.
 * @param options - Where to read from.
 * @returns The `printSchema` output of the fully composed schema.
 */
export async function composeSchemaForSnapshot(
	plugins: readonly PluginEntry[],
	options: SchemaSnapshotOptions = {}
): Promise<string> {
	const repositoryRoot = options.repositoryRoot ?? resolveRepositoryRoot();
	const typePaths = options.typePaths ?? [path.join(repositoryRoot, GRAPHQL_SCHEMA_SOURCE_GLOB)];

	// The loader is the one the runtime uses, so file discovery and the merge order are the
	// runtime's rather than a second implementation of them.
	const typesLoader = new GraphQLTypesLoader();
	const typeDefs = await typesLoader.mergeTypesByPaths(typePaths.map(toPosixPath));

	const schema = extendWithPlugins(buildSchema(typeDefs), getPluginExtensions(plugins as PluginEntry[]));
	return printSchema(schema);
}

/**
 * Applies every plugin's SDL document to the schema, in the order the plugins are registered.
 *
 * @param schema - The schema built from the core SDL.
 * @param extensions - The extension configurations the registered plugins declare.
 */
function extendWithPlugins(schema: GraphQLSchema, extensions: ReturnType<typeof getPluginExtensions>): GraphQLSchema {
	let composed = schema;

	for (const extension of extensions) {
		const document = typeof extension.schema === 'function' ? extension.schema() : extension.schema;
		if (!isNotEmpty(document)) continue;

		try {
			composed = extendSchema(composed, document);
		} catch (error) {
			throw new Error(
				`The GraphQL SDL contributed by a plugin could not be applied: ${(error as Error)?.message ?? error}`
			);
		}
	}

	return composed;
}

/** The first ancestor holding an `nx.json` — the workspace root, wherever the file is run from. */
export function resolveRepositoryRoot(from: string = __dirname): string {
	let current = path.resolve(from);

	for (;;) {
		if (fs.existsSync(path.join(current, 'nx.json'))) {
			return current;
		}
		const parent = path.dirname(current);
		if (parent === current) {
			throw new Error(`Could not find the repository root above '${from}': no nx.json in any ancestor directory.`);
		}
		current = parent;
	}
}

function toPosixPath(value: string): string {
	return value.split(path.sep).join('/');
}

/* ------------------------------------------------------------------ *
 * Command line
 * ------------------------------------------------------------------ */

interface CommandLineOptions {
	readonly mode: 'write' | 'check' | 'stdout' | 'help';
	readonly repositoryRoot: string;
	readonly pluginListPath: string;
}

/**
 * `--write` regenerates the snapshot, `--check` compares the composed schema with the committed
 * file and fails on a difference, and no flag prints it. The `core:graphql-snapshot` target runs
 * `--write`; the CI job runs it and then `git diff --exit-code`, so a stale snapshot cannot pass.
 */
async function main(argv: readonly string[]): Promise<number> {
	const options = parseArguments(argv);

	if (options.mode === 'help') {
		process.stdout.write(usage());
		return 0;
	}

	const plugins = loadShippedPlugins(options.pluginListPath);
	const composed = await composeSchemaForSnapshot(plugins, { repositoryRoot: options.repositoryRoot });
	const snapshotPath = path.join(options.repositoryRoot, GRAPHQL_SCHEMA_SNAPSHOT_PATH);

	if (options.mode === 'stdout') {
		process.stdout.write(composed);
		return 0;
	}

	if (options.mode === 'write') {
		const previous = readIfPresent(snapshotPath);
		if (previous === composed) {
			process.stdout.write(`${GRAPHQL_SCHEMA_SNAPSHOT_PATH} is up to date.\n`);
			return 0;
		}
		fs.mkdirSync(path.dirname(snapshotPath), { recursive: true });
		fs.writeFileSync(snapshotPath, composed, 'utf8');
		process.stdout.write(`${previous === undefined ? 'Wrote' : 'Updated'} ${GRAPHQL_SCHEMA_SNAPSHOT_PATH}.\n`);
		return 0;
	}

	const committed = readIfPresent(snapshotPath);
	if (committed === composed) {
		process.stdout.write(`${GRAPHQL_SCHEMA_SNAPSHOT_PATH} matches the composed schema.\n`);
		return 0;
	}

	process.stderr.write(
		`${GRAPHQL_SCHEMA_SNAPSHOT_PATH} does not match the composed schema. ` +
			'Run `yarn nx run core:graphql-snapshot` and commit the result.\n'
	);
	process.stderr.write(`${committed === undefined ? '(the snapshot does not exist)' : unifiedDiff(committed, composed)}\n`);
	return 1;
}

function parseArguments(argv: readonly string[]): CommandLineOptions {
	const repositoryRoot = readArgument(argv, '--root') ?? resolveRepositoryRoot();
	const pluginListPath =
		readArgument(argv, '--plugins') ?? path.join(repositoryRoot, GRAPHQL_PLUGIN_LIST_PATH);

	const mode = argv.includes('--write')
		? 'write'
		: argv.includes('--check')
			? 'check'
			: argv.includes('--help') || argv.includes('-h')
				? 'help'
				: 'stdout';

	return { mode, repositoryRoot, pluginListPath };
}

function readArgument(argv: readonly string[], name: string): string | undefined {
	const index = argv.indexOf(name);
	return index >= 0 ? argv[index + 1] : undefined;
}

function usage(): string {
	return [
		'Usage: node -r ts-node/register packages/core/src/lib/graphql/schema-snapshot.ts [options]',
		'',
		'  --write             regenerate the committed snapshot',
		'  --check             fail when the committed snapshot differs from the composed schema',
		'  --stdout            print the composed schema (default)',
		'  --root <dir>        the repository root (defaults to the nearest ancestor with nx.json)',
		`  --plugins <file>    the shipped plugin list (defaults to ${GRAPHQL_PLUGIN_LIST_PATH})`,
		''
	].join('\n');
}

/**
 * Reads the plugin list the API actually ships.
 *
 * It is loaded at run time rather than imported, so this file stays free of a compile-time
 * dependency on the application: the composition needs the array, not the module graph.
 *
 * @param file - The absolute path of the plugin list module.
 */
function loadShippedPlugins(file: string): PluginEntry[] {
	if (!fs.existsSync(file)) {
		throw new Error(
			`The plugin list '${file}' does not exist. The snapshot must be composed with the plugins the API ` +
				'ships, so the file is required rather than substituted.'
		);
	}

	// eslint-disable-next-line @typescript-eslint/no-var-requires
	const loaded = require(file) as { plugins?: PluginEntry[] };
	if (!Array.isArray(loaded?.plugins)) {
		throw new Error(`The plugin list '${file}' does not export a 'plugins' array.`);
	}

	return loaded.plugins;
}

function readIfPresent(file: string): string | undefined {
	return fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : undefined;
}

/** A line-by-line diff, enough for a CI log without pulling a diff library into the build. */
function unifiedDiff(previous: string, next: string): string {
	const before = previous.split('\n');
	const after = next.split('\n');
	const lines: string[] = [];
	const length = Math.max(before.length, after.length);

	for (let index = 0; index < length; index += 1) {
		if (before[index] === after[index]) continue;
		if (before[index] !== undefined) lines.push(`- ${before[index]}`);
		if (after[index] !== undefined) lines.push(`+ ${after[index]}`);
	}

	return lines.join('\n');
}

if (require.main === module) {
	main(process.argv.slice(2))
		.then((code) => {
			process.exitCode = code;
		})
		.catch((error: unknown) => {
			process.stderr.write(`${(error as Error)?.stack ?? String(error)}\n`);
			process.exitCode = 1;
		});
}
