export const AddEmployeePositionPage = {
	gridButtonCss: 'div.layout-switch > button',
	addNewPositionButtonCss: 'button[status="success"]',
	newPositionInputCss: '[placeholder="Position name"]',
	tagsSelectCss: '#addTags',
	tagsSelectOptionCss: '[type="checkbox"]',
	saveNewPositionButtonCss: '.appearance-filled.size-medium',
	updatePositionButtonCss: '.appearance-filled.size-medium',
	cancelNewPositionButtonCss: 'button[status="danger"]:not(nb-card-footer button)',
	editEmployeePositionButtonCss: 'button.action.primary',
	removeEmployeePositionButtonCss: 'button.action.appearance-filled',
	confirmDeletePositionButtonCss: 'nb-card-footer > button[status="danger"]',
	editPositionInputCss: 'div.d-flex > input[type="text"]',
	verifyTextCss: 'ga-notes-with-tags',
	cardBodyCss: 'nb-card-body',
	toastrMessageCss: 'nb-toast.ng-trigger',
	cancelButtonCss: 'button[status="danger"]:not(nb-card-footer button)',
	selectPositionToEditCss: 'ga-notes-with-tags',
	selectPositionToDeleteCss: 'ga-notes-with-tags'
};
