export const AddTaskPage = {
	gridButtonCss: 'div.layout-switch > button',
	addTaskButtonCss: 'div.mb-3 > button[status="success"]',
	selectProjectDropdownCss: '[formControlName="project"]',
	selectProjectDrodownOptionCss: '.ng-option',
	duplicateOrEditTaskButtonCss: 'div.mb-3 > button[status="info"]',
	deleteTaskButtonCss: 'div.mb-3 > button[status="danger"]',
	selectTableRowCss: 'table > tbody > tr.ng2-smart-row',
	tagsSelectCss: '#addTags',
	tagsSelectOptionCss: '[type="checkbox"]',
	closeTagsMultyselectDropdownCss: '.ng-select-container > .ng-arrow-wrapper',
	confirmDuplicateOrEditTaskButtonCss:
		'nb-card-footer > button[status="success"]',
	confirmDeleteTaskButtonCss: 'nb-card-footer > button[status="danger"]',
	addTitleInputCss: '[formControlName="title"]',
	selectEmloyeeMultyselectCss: 'button[class="select-button placeholder"]',
	selectEmployeeDropdownOptionCss: '.option-list nb-option',
	dueDateInputCss: '[formControlName="dueDate"]',
	estimateDaysInputCss: '[formControlName="estimateDays"]',
	estimateHoursInputCss: '[formControlName="estimateHours"]',
	estimateMinsInputCss: '[formControlName="estimateMinutes"]',
	descriptionTextareaCss: '[formControlName="description"]',
	saveNewTaskButtonCss: 'nb-card-footer > button[status="success"]',
	requestNewProjectButtonCss: 'div.mb-3 > button[status="success"]',
	projectNameInputCss: '#name',
	saveProjectButtonCss: 'div.form-group > button[status="success"]'
};
