export const AddTaskPage = {
	gridButtonCss: 'div.layout-switch > button',
	addTaskButtonCss: 'button[status="success"]',
	selectProjectDropdownCss: 'ga-project-selector ng-select',
	selectProjectDropdownOptionCss: '.ng-dropdown-panel .ng-option',
	editTaskButtonCss: 'button.action.primary',
	duplicateTaskButtonCss: 'button.action.primary',
	deleteTaskButtonCss: 'button:has(nb-icon[icon="trash-2-outline"])',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	selectTableFirstRowCss: 'tr.angular2-smart-row.selected',
	tagsSelectCss: '#addTags',
	tagsSelectOptionCss: '[type="checkbox"]',
	closeTagsMultiSelectDropdownCss: '.ng-select-container > .ng-arrow-wrapper',
	confirmDuplicateOrEditTaskButtonCss: 'nb-card-footer > button[status="success"]',
	confirmEditTaskButtonCss: '',
	confirmDeleteTaskButtonCss: 'button.mr-3.ml-3',
	addTitleInputCss: '[formControlName="title"]',
	selectEmployeeMultiSelectCss: 'ga-employee-multi-select nb-select button.select-button',
	selectEmployeeDropdownOptionCss: '.option-list nb-option',
	dueDateInputCss: '[formControlName="dueDate"]',
	estimateDaysInputCss: '[formControlName="estimateDays"]',
	estimateHoursInputCss: '[formControlName="estimateHours"]',
	estimateMinsInputCss: '[formControlName="estimateMinutes"]',
	descriptionTextareaCss: '[formControlName="description"]',
	saveNewTaskButtonCss: 'nb-card-footer > button[status="success"]',
	verifyTextCss: 'angular2-smart-table table tbody',
	toastrMessageCss: 'nb-toast.ng-trigger',
	searchTitleInputCss: 'input[placeholder="Title"]'
};
