export const ApprovalRequestPage = {
	gridButtonCss: 'div.layout-switch > button',
	addApprovalRequestButtonCss: 'button[status="success"]',
	editApprovalRequestButtonCss: 'button.action.primary',
	deleteApprovalRequestButtonCss: 'button:has(nb-icon[icon="trash-2-outline"])',
	nameInputCss: '[formcontrolname="name"]',
	minCountInputCss: '[formcontrolname="min_count"]',
	approvalPolicyDropdownCss: '[formcontrolname="approvalPolicyId"]',
	checkApprovalPolicyDropdownOptionCss: '.option-list nb-option',
	usersMultiSelectCss: 'ga-employee-multi-select nb-select button.select-button',
	checkUsersMultiSelectCss: '.option-list nb-option',
	saveButtonCss: 'nb-card-footer > button[status="success"]',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	approvalPolicyButtonCss: 'button[status="primary"]:has-text("Approval Policy")',
	descriptionInputCss: '[formcontrolname="description"]',
	backButtonCss: 'ngx-back-navigation button',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyApprovalPolicyCss: 'angular2-smart-table table tbody',
	verifyRequestCss: 'angular2-smart-table table tbody',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	headerCss: 'nb-dialog-container > nb-card.main',
	approvalRefuseButtonCss: 'table > tbody > tr.angular2-smart-row > td.ng-star-inserted',
	approvalStatusCss: 'table > tbody > tr.angular2-smart-row',
	searchByNameInputCss: 'input[placeholder="Name"]',
	rowCss: 'table > tbody > tr.angular2-smart-row',
	tableBodyCss: 'table > tbody'
};
