export const CandidatesPage = {
	gridButtonCss: 'div.layout-switch > button',
	inviteButtonCss: 'span.show-button button[status="primary"]',
	emailInputCss: '#emails',
	dateInputCss: '[placeholder="Date"]',
	sendInviteButtonCss: 'nb-card-footer button[status="success"]',
	addButtonCss: 'span.show-button button[status="success"]',
	firstNameInputCss: '#firstName',
	lastNameInputCss: '#lastName',
	usernameInputCss: '#username',
	newCandidateEmailInputCss: '#email',
	passwordInputCss: 'input#password',
	imageInputCss: '#inputImageUrl input[placeholder="Image"]',
	newCandidateDateInputCss: '#appliedDate',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	nextButtonCss: 'nb-dialog-container button.green',
	nextStepButtonCss: 'nb-dialog-container button.green',
	allCurrentCandidatesButtonCss: 'nb-dialog-container button[status="success"]',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	editButtonCss: 'div.btn-group.actions button.action.primary',
	archiveButtonCss: 'div.btn-group.actions button.action.secondary',
	rejectButtonCss: 'div.btn-group.actions button.action.warning',
	saveEditButtonCss: 'div.actions > button[status="success"]',
	backButtonCss: 'ngx-back-navigation button[status="primary"]',
	confirmActionButtonCss: 'nb-card-footer > button[status="danger"]',
	checkboxButtonCss: 'nb-toggle.custom-toggle',
	manageAddButtonCss: 'div.header > button[status="success"]',
	locationButtonCss: '[router-link="/pages/employees/candidates/ed"]',
	countryDropdownCss: 'ga-country ng-select',
	selectDropdownOptionCss: '.option-list nb-option',
	cityInputCss: '#cityInput',
	addressOneInputCss: '#addressInput',
	postCodeInputCss: '#postcodeInput',
	saveActionButtonCss: 'ga-edit-candidate-main div.actions > button[status="success"]',
	ratesButtonCss: '.route-tab:nth-child(5) > .tab-text',
	payPeriodDropdownCss: '#payPeriodsSelect',
	billRateInputCss: '#billRateValueInput',
	experienceButtonCss: '.route-tab:nth-child(7) > .tab-text',
	addExperienceButtonCss: 'div.btn > button[status="success"]',
	schoolNameInputCss: '[formcontrolname="schoolName"]',
	degreeInputCss: '[formcontrolname="degree"]',
	saveExperienceButtonCss: 'div.col-2 > button[status="success"]',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyCandidateCss: 'a.link-text',
	badgeCss: 'div.badge-danger'
};
