export const CandidatesPage = {
	gridButtonCss: 'div.layout-switch > button',
	inviteButtonCss: 'div.mb-3 > button[status="primary"]',
	emailInputCss: '#emailsSelect',
	dateInputCss: '[placeholder="Date"]',
	sendInviteButtonCss: 'nb-card-footer.text-right > button[status="success"]',
	addButtonCss: 'div.mb-3 > button[status="success"]',
	firstNameInputCss: '#inputFirstName',
	lastNameInputCss: '#inputLastName',
	usernameInputCss: '#inputUsername',
	newCandidateEmailInputCss: '#inputEmail',
	passwordInputCss: '#inputPassword',
	imageInputCss: '#inputImageUrl',
	newCandidateDateInputCss: '#appliedDateInput',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	nextButtonCss: 'div.text-right > button[status="success"]',
	nextStepButtonCss: 'div.button-container > button[status="success"]',
	allCurrentCandidatesButtonCss:
		'div.step-container > button[status="success"]',
	selectTableRowCss: 'table > tbody > tr.ng2-smart-row',
	editButtonCss: '.status-info',
	archiveButtonCss: 'div.mb-3 > button[status="warning"]',
	rejectButtonCss: 'div.mb-3 > button[status="danger"]',
	saveEditButtonCss:
		'div.employee-form > div.actions > button[status="success"]',
	backButtonCss:
		'div.header-selector-wrapper > div.main > button[status="primary"]',
	confirmActionButtonCss: 'nb-card-footer > button[status="danger"]',
	checkboxButtonCss: 'span.custom-checkbox',
	manageAddButtonCss: 'div.header > button[status="success"]',
	locationButtonCss: '[router-link="/pages/employees/candidates/ed"]',
	countryDropdownCss: '#countrySelect',
	selectDropdownOptionCss: '.option-list nb-option',
	cityInputCss: '#cityInput',
	addressOneInputCss: 'addressInput',
	postcodeInputCss: '#postcodeInput',
	saveActionButtonCss:
		'ga-edit-candidate-main div.actions > button[status="success"]',
	ratesButtonCss: '.route-tab:nth-child(5) > .tab-text',
	payPeriodDropdownCss: '#payPeriodsSelect',
	billRateInputCss: '#billRateValueInput',
	experienseButtonCss: '.route-tab:nth-child(7) > .tab-text',
	addExperienceButtonCss: 'div.btn > button[status="success"]',
	schoolNameInputCss: '[formcontrolname="schoolName"]',
	degreeInputCss: '[formcontrolname="degree"]',
	saveExperisnceButtonCss: 'div.col-2 > button[status="success"]'
};
