export const ContactsLeadsPage = {
	gridButtonCss: 'div.layout-switch > button',
	addButtonCss: 'div.mb-3 > button[status="success"]',
	editButtonCss: 'div.mb-3 > button[status="info"]',
	inviteButtonCss: 'div.mb-3 > button[status="primary"]',
	deleteButtonCss: 'div.mb-3 > button[status="danger"]',
	nameInputCss: '#name',
	emailInputCss: '#email',
	phoneInputCss: '[formcontrolname="primaryPhone"]',
	countryInputCss: '[formcontrolname="country"]',
	cityInpuCss: '[formcontrolname="city"]',
	postcodeinputCss: '[formcontrolname="postcode"]',
	streetInputCss: '[formcontrolname="address"]',
	projectsDropdownCss: '[formcontrolname="projects"]',
	projectsDropdownOptionCss: 'div.ng-option',
	usersMultyselectCss: 'button[class="select-button placeholder"]',
	checkUsersMultyselectCss: '.option-list nb-option',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	websiteInputCss: '[formcontrolname="website"]',
	cardBodyCss: 'div.contact-container',
	saveButtonCss: 'div.form-group > button[status="success"]',
	selectTableRowCss: 'table > tbody > tr.ng2-smart-row',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="info"]',
	contactNameCss: '[formcontrolname="name"]',
	contactPhoneCss: '[formcontrolname="primaryPhone"]',
	contactEmailCss: '#emailInput',
	toastrMessageCss: 'nb-toast.ng-trigger',
	saveInviteButtonCss: 'nb-card-footer > button[status="success"]'
};
