export const ContactsLeadsPage = {
	gridButtonCss: 'div.layout-switch > button',
	addButtonCss: 'div.mb-3 > button[status="success"]',
	editButtonCss: 'div.mb-3 > button[status="success"]',
	inviteButtonCss: 'div.mb-3 > button[status="primary"]',
	deleteButtonCss: 'div.mb-3 > button[status="danger"]',
	nameInputCss: '#name',
	emailInputCss: '#email',
	phoneInputCss: '[formcontrolname="primaryPhone"]',
	lastStepBtnCss: 'div.step-content > form > div > button[status="success"]',
	countryDropdownCss: 'ga-country div.form-group nb-select',
	cityInpuCss: '[formcontrolname="city"]',
	budgetInpuCss: 'input[formcontrolname="budget"]',
	postcodeinputCss: '[formcontrolname="postcode"]',
	streetInputCss: '[formcontrolname="address"]',
	projectsDropdownCss: '[formcontrolname="projects"]',
	projectsDropdownOptionCss: 'div.ng-option',
	usersMultiSelectCss: 'div.form-group ga-employee-multi-select nb-select',
	dropdownOptionCss: '.option-list nb-option',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	websiteInputCss: '[formcontrolname="website"]',
	cardBodyCss: 'div.contact-container',
	saveButtonCss: 'div.form-group > button[status="success"]',
	nextButtonCss: 'div.fields > div > button[status="success"]',
	finishButtonCss: 'div.fields > div > button[status="success"]',
	selectTableRowCss: 'table > tbody > tr.ng2-smart-row',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	contactNameCss: '[formcontrolname="name"]',
	contactPhoneCss: '[formcontrolname="primaryPhone"]',
	contactEmailCss: '#emailInput',
	toastrMessageCss: 'nb-toast.ng-trigger',
	saveInviteButtonCss: 'nb-card-footer > button[status="success"]',
	verifyLeadCss: 'div.d-block'
};
