export const CustomersPage = {
	gridButtonCss: 'div.layout-switch > button',
	addButtonCss: 'button[status="success"]:has(nb-icon[icon="plus-outline"])',
	editButtonCss: 'button:has(nb-icon[icon="edit-outline"])',
	inviteButtonCss: 'button.action.info',
	deleteButtonCss: 'button:has(nb-icon[icon="trash-2-outline"])',
	// Scope the add/edit stepper Name + Phone to nb-stepper: the invite step opens an NbDialog that,
	// once closed, lingers in a fading cdk-overlay carrying the SAME formcontrolnames. Unscoped, these
	// match 2 elements during the later edit step, so clearField()/enterInput() (which don't use
	// .first()) throw a Playwright strict-mode violation. Mirrors the verified-green ClientsPageObject.
	nameInputCss: 'nb-stepper [formcontrolname="name"]',
	emailInputCss: '#email',
	budgetInputCss: 'input[formcontrolname="budget"]',
	lastStepBtnCss: 'button[status="success"]:has-text("Save")',
	phoneInputCss: 'nb-stepper [formcontrolname="primaryPhone"]',
	countryDropdownCss: 'ga-country ng-select',
	cityInputCss: '[formcontrolname="city"]',
	postCodeInputCss: '[formcontrolname="postcode"]',
	streetInputCss: '[formcontrolname="address"]',
	projectsDropdownCss: '[formcontrolname="projects"]',
	projectsDropdownOptionCss: 'div.ng-option',
	usersMultiSelectCss: 'div.form-group ga-employee-multi-select nb-select',
	dropdownOptionCss: '.option-list nb-option, .ng-option',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	websiteInputCss: '[formcontrolname="website"]',
	cardBodyCss: 'div.contact-container',
	saveButtonCss: 'button[status="success"]',
	nextButtonCss: 'button:has-text("Next")',
	finishButtonCss: 'button[status="success"]:has-text("Save")',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	customerNameCss: '[formcontrolname="name"]',
	customerPhoneCss: '[formcontrolname="primaryPhone"]',
	customerEmailCss: '#emailInput',
	toastrMessageCss: 'nb-toast.ng-trigger',
	saveInviteButtonCss: 'nb-card-footer > button[status="success"]',
	verifyCustomerCss: 'a.link-text'
};
