export const EditUserPage = {
	gridButtonCss: 'div.layout-switch > button',
	selectTableRowCss: 'table > tbody > tr.ng2-smart-row',
	editButtonCss: 'button[status="info"]',
	orgTabButtonCss: 'ul.route-tabset > li > a.tab-link',
	addOrgButtonCss: 'nb-card-header > button[status="success"]',
	removeOrgButtonCss: 'g[data-name="close"]',
	confirmRemoveOrgButtonCss: 'nb-card-footer > button[status="danger"]',
	selectOrgMultiSelectCss: 'button[class="select-button placeholder"]',
	selectOrgDropdownOptionCss: '.option-list nb-option',
	saveSelectedOrgButton: 'div.form-group > button[status="success"]',
	firstNameInputCss: '#firstName',
	lastNameInputCss: '#lastName',
	passwordInputCss: '#password',
	repeatPasswordInputCss: '[placeholder="Repeat Password"]',
	emailInputCss: '#email',
	tagsSelectCss: '#addTags',
	tagsSelectOptionCss: '[type="checkbox"]',
	roleSelectCss: '#roleName',
	roleSelectOptionCss: '.option-list nb-option',
	preferredLanguageCss: '#preferredLanguage',
	preferredLanguageOptionCss: '.option-list nb-option',
	saveButtonCss: 'div.actions > button[status="success"]',
	verifyUserCss: 'div.d-block',
	toastrMessageCss: 'nb-toast.ng-trigger'
};
