export const EmployeeDashboardPage = {
	addNewExpenseButtonCss: 'button.action[status="success"]',
	employeeDropdownCss: '[placeholder="Employee"]',
	dropdownOptionCss: 'div.ng-option',
	expenseDropdownCss: '#categoryInput',
	valueInputCss: '#valueInput',
	saveExpenseButtonCss:
		'nb-card-footer > button[status="success"]',
	toastrMessageCss: 'nb-toast.ng-trigger',
	menuButtonsCss: 'nb-menu > ul.menu-items > li',
	employeeSelectorCss: 'ga-employee-selector',
	selectEmployeeDropdownOptionCss: 'ng-dropdown-panel > div[class="ng-dropdown-panel-items scroll-host"] > div > div.ng-star-inserted',
	salaryCss: 'div.header-container div.employee-salary',
	incomeBtn: 'a[title="Income"]',
	addNewIncomeBtnCss: 'button[status="success"]:has(nb-icon[icon="plus-outline"])',
	gridButtonCss: 'div.layout-switch > button',
	addIncomeButtonCss: 'div.mb-3 > button[status="success"]',
	selectEmployeeDropdownCss: 'ga-employee-selector.employees',
	selectEmployeeDropdownOptCss: 'div.ng-option',
	dateInputCss: '[formcontrolname="valueDate"]',
	organizationContactCss: '[formcontrolname="organizationContact"]',
	amountInputCss: '[formcontrolname="amount"]',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	notesInputCss: '[formcontrolname="notes"]',
	saveIncomeButtonCss: 'nb-card-footer > button[status="success"]',
	verifyIncomeCss: 'ga-notes-with-tags > div > div.ng-star-inserted',
	verifyDashboardIncomeCss: 'ga-info-block[color="#089c17"]',
	verifyDashboardBonusCss: 'div.bonus',
	currencyFieldCss: 'ng-select.currency-selector',
	currencyOptionCss: 'div.ng-option'

};
