export const IncomePage = {
	gridButtonCss: 'div.layout-switch > button',
	addIncomeButtonCss: 'div.actions-container button[status="success"]',
	selectEmployeeDropdownCss: 'ngx-income-mutation ga-employee-selector ng-select',
	selectEmployeeDropdownOptionCss: 'div.ng-option',
	dateInputCss: 'ngx-income-mutation [formcontrolname="valueDate"]',
	organizationContactCss: 'ngx-income-mutation ga-contact-select ng-select',
	organizationContactSearchInputCss: 'ngx-income-mutation ga-contact-select ng-select input[type="text"]',
	amountInputCss: 'ngx-income-mutation [formcontrolname="amount"]',
	addTagsDropdownCss: 'ngx-income-mutation #addTags',
	tagsDropdownOption: 'div.ng-option',
	notesInputCss: 'ngx-income-mutation textarea[formcontrolname="notes"]',
	saveIncomeButtonCss: 'ngx-income-mutation nb-card-footer > button[status="success"]',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	editIncomeButtonCss: 'div.actions-container button.action.primary:has-text("Edit")',
	deleteIncomeButtonCss: 'div.actions-container button.action:has(nb-icon[icon="trash-2-outline"])',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	cardBodyCss: 'ngx-income-mutation nb-card-header',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyIncomeCss: 'table > tbody > tr.angular2-smart-row'
};
