export const InvoicesPage = {
	gridButtonCss: 'div.layout-switch > button',
	tabButtonCss: 'ul.tabset > li.tab  > a.tab-link',
	addButtonCss: 'div.actions-container button[status="success"]',
	// Edit + Download both render as `button.action.primary` in the invoice toolbar — scope to the
	// Edit label so clickEditButton targets Edit (not Download).
	editButtonCss: 'div.btn-group button.action.primary:has-text("Edit")',
	setStatusButtonCss: 'div.btn-group nb-select.select-nb',
	// View + Payments both render as `button.action.secondary` for invoices — scope to the View label.
	viewButtonCss: 'div.btn-group button.action.secondary:has-text("View")',
	popoverButtonCss: 'div.popover-container-action button.action',
	deleteButtonCss: 'div.popover-container-action button.action.danger',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	discountInputCss: '#inputDiscountValue',
	discountTypeDropdownCss: '[formcontrolname="discountType"]',
	dropdownOptionCss: '.option-list nb-option',
	organizationContactDropdownCss: 'div.col-sm-6 > ga-contact-select > ng-select',
	contactOptionCss: 'div.ng-option',
	taxInputCss: '#inputTax',
	taxTypeDropdownCss: '[formcontrolname="taxType"]',
	invoiceTypeDropdownCss: '[formcontrolname="invoiceType"]',
	generateItemsButtonCss: 'div.buttons > button.gen',
	selectEmployeeCss: 'div.form-group ga-employee-multi-select nb-select',
	saveAsDraftButtonCss: 'nb-card-footer > button[status="primary"]',
	emailInputCss: '#email',
	moreButtonCss: 'div.btn-group button.action:has(nb-icon[icon="more-vertical-outline"])',
	tableRowCss: 'table > tbody > tr.angular2-smart-row',
	toastrMessageCss: 'nb-toast.ng-trigger',
	cardBodyCss: 'nb-card-header.d-flex',
	backButtonCss: 'ngx-back-navigation button',
	deleteItemCss: 'i.nb-trash',
	confirmButtonCss: 'nb-card-footer.text-left > button[status="success"]',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	verifyInvoiceCss: 'tr.ng-star-inserted > td',
	draftBadgeCss: 'div.badge-warning',
	successBadgeCss: 'div.badge-success',
	emailCardCss: 'nb-card-body.invoice-email-body',
	inputInvoiceNumberCss: '#inputInvoiceNumber',
	estimateDateCss: '#inputInvoiceDate',
	dueDateInputCss: '#inputDueDate',
	totalValueInputCss: '#inputTotalValue',
	currencySelectCss: 'ga-currency ng-select',
	inputStatusCss: '#inputStatus',
	searchButtonCss: 'button[type="submit"][status="success"]',
	resetButtonCss: 'button[type="reset"]'
};
