export const ManageEmployeesPage = {
	gridButtonCss: 'div.layout-switch > button',
	inviteButtonCss: 'button.action[status="info"]',
	emailsInputCss: '#emails',
	dateInputCss: '[formcontrolname="startedWorkOn"]',
	selectProjectDropdownCss: '#projectSelection',
	selectProjectDropdownOptionCss: 'div.ng-option > span.ng-option-label',
	sendInviteButtonCss: 'nb-card-footer > button[status="success"]',
	addEmployeeButtonCss: 'button[status="success"]:has-text("Add")',
	editEmployeeButtonCss: 'button.action.primary',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	// Full Name column filter input in the smart-table header (tr.angular2-smart-filters). Typing the
	// created employee's name filters the grid down to just that record so row 0 is the one we created,
	// not a seeded employee (the fresh seed renders Super Admin + Default Employee ahead of it).
	nameFilterInputCss: 'th.angular2-smart-th.fullName input',
	deleteEmployeeButtonCss: 'button.action:has(nb-icon[icon="trash-2-outline"])',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	endWorkButtonCss: 'button.action.orange',
	endWorkDateInputCss: '[placeholder="Pick a Date"]',
	confirmEndWorkButtonCss: 'nb-card-footer > button[status="success"]',
	firstNameInputCss: '#firstName',
	lastNameInputCss: '#lastName',
	usernameInputCss: '#username',
	emailInputCss: '#email',
	// ngx-password-form-field reflects id onto BOTH its host element and the inner input; scope to
	// input# so enterInput's fill() (no .first()) doesn't hit a strict-mode violation.
	passwordInputCss: 'input#password',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	// ngx-file-uploader-input renders TWO inputs (text URL + hidden file); target the text one only,
	// else enterInput's fill() (no .first()) hits a strict-mode violation.
	imgInputCss: '#inputImageUrl input[type="text"]',
	// Scope stepper buttons to the dialog: nb-stepper only renders the ACTIVE step's content, so an
	// unscoped 'button.green' could match a different overlay; inside the dialog it's the current
	// step's nbStepperNext. Step-3 "Finished adding" is the dialog's lone status="success" button.
	nextButtonCss: 'nb-dialog-container button.green',
	nextStepButtonCss: 'nb-dialog-container button.green',
	lastStepButtonCss: 'nb-dialog-container button[status="success"]',
	saveEditButtonCss: 'div.actions > button[status="success"]',
	backButtonCss: 'div.main > button[status="primary"]',
	usernameEditInputCss: '#username',
	emailEditInputCss: '#email',
	firstNameEditInputCss: '#firstName',
	lastNameEditInputCss: '#lastName',
	usernameEditSecondInputCss: '#usernameInput',
	emailEditSecondInputCss: '#emailInput',
	firstNameSecondEditInputCss: '#firstNameInput',
	lastNameSecondEditInputCss: '#lastNameInput',
	preferredLanguageDropdownCss: 'div.col-sm-6 > div.form-group > ngx-language-selector > ng-select',
	preferredLanguageOptionCss: 'ng-dropdown-panel.ng-dropdown-panel > div.ng-dropdown-panel-items div.ng-option',
	cardBodyCss: 'ga-employee-mutation nb-card-body',
	manageInvitesButtonCss: 'div.card-header-title > div.mr-2 > button[status="primary"]',
	copyLinkButtonCss: 'button.action.success',
	resendInviteButtonCss: 'button.action.warning',
	deleteInviteButtonCss: 'button.action:has(nb-icon[icon="trash-2-outline"])',
	confirmResendInviteButtonCss: 'nb-card-footer > button[status="success"]',
	confirmDeleteInviteButtonCss: 'nb-card-footer > button[status="danger"]',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyEmployeeCss: 'angular2-smart-table',
	verifyInviteCss: 'angular2-smart-table'
};
