export const ManageEmployeesPage = {
	gridButtonCss: 'div.layout-switch > button',
	inviteButtonCss: 'div.mb-3 > button[status="primary"]',
	emailsInputCss: '#emailsSelect',
	dateInputCss: '[formcontrolname="startedWorkOn"]',
	selectProjectDropdownCss: '#projectsSelect',
	selectProjectDropdownOptionCss: 'div.ng-option',
	sendInviteButtonCss: 'nb-card-footer.text-right > button[status="success"]',
	addEmployeeButtonCss: 'div.mb-3 > button[status="success"]',
	editEmployeeButtonCss: 'div.mb-3 > button[status="info"]',
	selectTableRowCss: 'table > tbody > tr.ng2-smart-row',
	deleteEmployeeButtonCss: 'div.mb-3 > button[status="danger"]',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	endWorkButtonCss: 'div.mb-3 > button[status="warning"]',
	endWorkDateInputCss: '[placeholder="Pick a Date"]',
	confirmEndWorkButtonCss:
		'nb-card-footer.text-right > button[status="success"]',
	firstNameInputCss: '#inputFirstName',
	lastNameInputCss: '#inputLastName',
	usernameInputCss: '#inputUsername',
	emailInputCss: '#inputEmail',
	passwordInputCss: '#inputPassword',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	imgInputCss: '#inputImageUrl',
	nextButtonCss: 'div.text-right > button[status="success"]',
	nextStepButtonCss: 'div.button-container > button[status="success"]',
	lastStepButtonCss: 'div.step-container > button[status="success"]',
	saveEditButtonCss: 'div.actions > button[status="success"]',
	backButtonCss: 'div.main > button[status="primary"]',
	usernameEditInputCss: '#usernameInput',
	emailEditInputCss: '#emailInput',
	firstNameEditInputCss: '#firstNameInput',
	lastNameEditInputCss: '#lastNameInput',
	preferedLanguageDropdownCss: 'button',
	preferedLanguageOptionCss: '.option-list nb-option',
	cardBodyCss: 'div.text-right'
};
