export const MyTasksTrackedInTimesheets = {
    addButtonCss: 'button[status="success"]:has-text("Add")',
    projectDropdownCss: '[formControlName="projectId"]',
    statusDropdownCss: '[formControlName="taskStatus"]',
    addTitleInputCss: '[formControlName="title"]',
    tagsSelectCss: '#addTags',
    tagsSelectOptionCss: '[type="checkbox"]',
    cardBodyCss: 'nb-card-footer',
    dueDateInputCss: '[formControlName="dueDate"]',
    estimateDaysInputCss: '[formControlName="estimateDays"]',
    estimateHoursInputCss: '[formControlName="estimateHours"]',
    estimateMinsInputCss: '[formControlName="estimateMinutes"]',
    descriptionTextareaCss: '[formControlName="description"]',
    saveNewTaskButtonCss: 'nb-card-footer > button[status="success"]',
    toastrMessageCss: 'nb-toast.ng-trigger',
    timerCss: 'nb-action.timer-action',
    timerBtnCss: 'nb-action.timer-action nb-icon[icon="clock-outline"]',
    taskSelectCss: 'div.form-group ga-task-selector ng-select',
    dropdownOptionCss: 'div.ng-option',
    startTimerBtnCss: 'div.actions div.toggle button[status="success"]',
    stopTimerBtnCss: 'div.actions div.toggle button[status="danger"]',
    viewTimesheetBtnCss: 'div.view-log-button a.timesheet',
    projectNameCss: 'div[class="col project-name"] > div[class="mt-2 small"] > span.ng-star-inserted'

}
