export const OrganizationDepartmentsPage = {
	gridButtonCss: 'div.layout-switch > button',
	addDepartmentButtonCss: 'nb-card-body > div > button[status="success"]',
	nameInputCss: '[placeholder="Department name"]',
	selectEmployeeDropdownCss: 'button[class="select-button placeholder"]',
	selectEmployeeDropdownOptionCss: '.option-list nb-option',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	selectTableRowCss: 'table > tbody > tr.ng2-smart-row',
	saveDepartmentButtonCss: 'div.form-group > button[status="success"]',
	editDepartmentButtonCss: 'nb-card-body > div > button[status="info"]',
	deleteDepartmentButtonCss: 'nb-card-body > div > button[status="danger"]',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	footerCss: 'nb-card-body > div.form-group',
	verifyDepartmentCss: 'div.ng-star-inserted',
	toastrMessageCss: 'nb-toast.ng-trigger',
};
