export const OrganizationInventoryPage = {
	gridButtonCss: 'div.layout-switch > button',
	addButtonCss: 'button[status="success"]:has-text("Add")',
	languageDropdownCss: 'ngx-language-selector ng-select',
	dropdownOptionCss: '.ng-option',
	nameInputCss: 'input[id="name"]',
	codeInputCss: 'input[id="codeInput"]',
	productTypeDropdownCss: 'ngx-product-type-selector ng-select',
	productCategoryDropdownCss: 'ngx-product-category-selector ng-select',
	descriptionInputCss: '#description',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	saveButtonCss: 'nb-card-footer button[status="success"]',
	editButtonCss: 'button.action.primary',
	deleteButtonCss: 'button.action:has(nb-icon[icon="trash-2-outline"])',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	addCategoryOrTypeButtonCss: 'button[status="success"]:has-text("Add")',
	backButtonCss: 'ngx-back-navigation button[status="primary"]',
	backFromInventoryButtonCss: 'ngx-back-navigation button[status="primary"]',
	backFromCategoryButtonCss: 'ngx-back-navigation button[status="primary"]',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyTypeCss: 'angular2-smart-table',
	verifyCategoryCss: 'angular2-smart-table',
	verifyInventoryCss: 'gauzy-name-with-description div.name',
	merchantsOrWarehousesBtnCss: 'div.mb-3 > button[status="warning"]',
	addMerchantBtnCss: 'div.mb-3 > button[status="success"]',
	merchantNameInputCss: 'div.form-group > input[id="name"]',
	merchantCodeInputCss: 'div.form-group > input[id="code"]',
	merchantEmailInputCss: 'div.form-group > input[id="email"]',
	merchantPhoneInputCss: 'div.form-group > input[id="phone"]',
	merchantCurrencySelectCss: 'div.form-group > nb-select[id="currencySelect"] > button.select-button',
	merchantFaxInputCss: 'div[class="col-md-6 col-sm-12"] > input[id="fax"]',
	merchantFiscalInfoInputCss: 'div.form-group > input[formcontrolname="fiscalInformation"]',
	merchantWebsiteInputCss: 'div.form-group > input[id="website"]',
	tagsSelectCss: 'ga-tags-color-input > div > ng-select[id="addTags"]',
	tagsDropdownOptionCss: 'div.ng-option',
	merchantDescriptionInputCss: 'div.form-group > textarea[formcontrolname="description"]',
	merchantActiveCheckboxCss: 'nb-checkbox > label > span.custom-checkbox',
	merchantNextBtnCss: 'div.row > div[class="form-group col-4"] > button[status="primary"]',
	countrySelectCss: 'div.col-4 > ga-country > div.form-group > nb-select > button.select-button',
	cityInputCss: 'div.form-group > input[id="cityInput"]',
	postCodeInputCss: 'div.form-group > input[id="postcodeInput"]',
	addressInputCss: 'div.form-group > input[id="addressInput"]',
	saveMerchantBtnCss: 'div.row > div[class="form-group col-4"] > button[status="success"]',
	editMerchantBtnCss: 'div.mb-3 > button[status="info"]',
	deleteMerchantBtnCss: 'div.mb-3 > button[status="danger"]',
	addWarehouseBtnCss: 'div.mb-3 > button[status="success"]',
	warehousesSelectCss: 'div[class="col-md-9 col-sm-12 pl-5"] > div.form-group > nb-select > button.select-button',
	warehouseNameInputCss: 'div.form-group > input[id="name"]',
	warehouseCodeInputCss: 'div.form-group > input[id="code"]',
	warehouseEmailInputCss: 'div.form-group > input[id="email"]',
	warehouseActiveCheckboxCss: 'nb-checkbox > label > span.custom-checkbox',
	warehouseDescriptionInputCss: 'div.form-group > textarea[id="description"]',
	tabBtnCss: 'div[class="step ng-star-inserted"] > div.label > span.ng-star-inserted',
	saveWarehouseBtnCss: 'nb-card-footer.text-right > button[status="success"]',
	editWarehouseBtnCss: 'div.mb-3 > button[status="info"]',
	deleteWarehouseBtnCss: 'div.mb-3 > button[status="danger"]',
	sidebarBtnCss: 'span.menu-title',
	inventorySidebarBtnCss: 'a[href="#/pages/organization/inventory"] > span.menu-title',
	verifyMerchantWarehouseCss: 'div.d-block'
};
