export const OrganizationHelpCenterPage = {
	addButtonCss: 'div.add-icon-field > button[status="success"]',
	languageDropdownCss: 'div.form-group > ngx-language-selector > ng-select',
	dropdownOptionCss: '.ng-option, .option-list nb-option',
	toggleButtonCss: 'nb-toggle:has-text("Publish Status")',
	iconDropdownCss:
		'nb-select#icon > button.select-button',
	colorInputCss: 'input[id="color"]',
	nameInputCss: 'input[id="name"]',
	descriptioninputCss: 'input[id="description"]',
	saveButtonCss: 'nb-card-footer.text-left > button[status="success"]',
	settingsButtonCss: 'nb-action.icons',
	deleteButtonCss: 'nb-card-footer.save-button > button[status="danger"]',
	settingsDropdownOptionCss: 'nb-menu.context-menu > ul.menu-items li',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyBaseCss: 'div.base > div > span.text',
	closeDeleteButtonCss: 'g[data-name="close"]',
	verifyCategortCss: 'div[class="base ng-star-inserted child"]',
	arrowButtonCss:'span.toggle-children',
	addArticleButtonCss: 'button[status="success"]',
	nameOfTheArticleInputCss: 'input[formcontrolname="name"]',
	descOfTheArticleInputCss: 'input[formcontrolname="desc"]',
	employeePlaceholderCss: 'ga-employee-multi-select nb-select',
	employeeDropdownCss: 'ul.option-list > nb-option',
	articleTextCss: 'div[id="cke_1_contents"] > iframe[class="cke_wysiwyg_frame cke_reset"]',
	articleSaveBtnCss: 'div.save-button > button[status="success"]'
};
