export const OrganizationEquipmentPage = {
	gridButtonCss: 'div.layout-switch > button',
	addButtonCss: 'button[status="success"]:has-text("Add")',
	nameInputCss: '[formcontrolname="name"]',
	typeInputCss: '[formcontrolname="type"]',
	serialNumberInputCss: '[formcontrolname="serialNumber"]',
	manufacturedYearInputCss: '[formcontrolname="manufacturedYear"]',
	initialCostInputCss: '[formcontrolname="initialCost"]',
	maxSharePeriodInputCss: '[formcontrolname="maxSharePeriod"]',
	selectEmployeeDropdownCss: 'ga-employee-multi-select nb-select',
	selectEmployeeDropdownOptionCss: '.option-list nb-option',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	saveButtonCss: 'nb-card-footer button[status="success"]',
	editEquipmentButtonCss: 'button.action.primary',
	deleteEquipmentButtonCss: 'button.action:has(nb-icon[icon="trash-2-outline"])',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	footerCss: 'nb-card-footer',
	equipmentSharingButtonCss: 'button.sharing[status="primary"]',
	selectEquipmentDropdownCss: '[formcontrolname="equipment"]',
	selectEquipmentDropdownOptionCss: '.option-list nb-option',
	selectPolicyDropdownCss: '[formcontrolname="equipmentSharingPolicyId"]',
	selectPolicyDropdownOptionCss: '.option-list nb-option',
	dateInputCss: '[formcontrolname="shareRequestDay"]',
	startDateInputCss: '[formcontrolname="shareStartDay"]',
	endDateInputCss: '[formcontrolname="shareEndDay"]',
	equipmentSharingPolicyButtonCss: 'button.action[status="primary"]',
	policyDescriptionInputCss: '[formcontrolname="description"]',
	backButtonCss: 'ngx-back-navigation button[status="primary"]',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyPolicyCss: 'tr.angular2-smart-row',
	verifySharingCss: 'angular2-smart-table',
	verifyEquipmentCss: 'ga-picture-name-tags',
	spinnerCss: 'nb-spinner'
};
