const ACTIONS_BAR_CSS = 'ngx-gauzy-button-action';
export const OrganizationProjectsPage = {
	gridButtonCss: 'div.layout-switch > button',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	tagsSelectCss: '#addTags .ng-input input',
	tagsSelectOptionCss: '.ng-dropdown-panel [type="checkbox"]',
	closeTagsMultiSelectDropdownCss: '.ng-select-container > .ng-arrow-wrapper',
	ownerDropdownCss: '[formControlName="owner"] button',
	ownerDropdownOptionCss: '.option-list nb-option',
	clientsDropdownCss: '[formControlName="organizationContact"] .ng-input input',
	clientsDropdownOptionCss: 'ng-dropdown-panel .ng-option',
	selectEmployeeMultiSelectCss: 'nb-select[ng-reflect-placeholder="Add or Remove Employees"] button',
	selectEmployeeDropdownOptionCss: '.option-list nb-option',
	requestNewProjectButtonCss: 'button[status="success"]',
	projectNameInputCss: '#name',
	codeInputCss: '#code',
	budgetInputCss: '[formcontrolname="budget"]',
	projectDescriptionCss: '[formcontrolname="description"]',
	tabButtonCss: 'span.tab-text',
	saveProjectButtonCss: 'div.form-group > button[status="success"]',
	editProjectButtonCss: 'button[status="info"]',
	deleteProjectButtonCss: `${ACTIONS_BAR_CSS} .actions.ng-star-inserted button:last-of-type`,
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	colorInputCss: '[formcontrolname="color"]',
	footerCss: 'ga-project-mutation nb-card-body div.form-group.action-buttons',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyProjectCss: 'ga-project-list tr td:first-of-type',
	// testing library
	tabSetCss: 'nb-card nb-tabset',
	actionsBarCss: ACTIONS_BAR_CSS,
	editButtonName: 'Edit',
	saveButtonName: 'Save'
};
