export const OrganizationInventoryPage = {
	gridButtonCss: 'div.layout-switch > button',
	addButtonCss: 'div.mb-3 > button[status="success"]',
	languageDropdownCss: 'div[class="form-group mb-3"] > ngx-language-selector > ng-select',
	dropdownOptionCss: '.option-list nb-option',
	nameInputCss: 'input[id="nameInput"]',
	codeInputCss: 'input[id="codeInput"]',
	productTypeDropdownCss: 'div[class="col-sm-6 mb-4"] > nb-select[id="productTypeId"]',
	productCategoryDropdownCss: 'div[class="col-sm-6 mb-4"] > nb-select[id="productCategoryId"]',
	descriptionInputCss: '#description',
	selectTableRowCss: 'table > tbody > tr.ng2-smart-row',
	saveButtonCss: 'nb-card-footer.text-right > button[status="success"]',
	editButtonCss: 'div.mb-3 > button[status="info"]',
	deleteButtonCss: 'div.mb-3 > button[status="danger"]',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	addCategoryOrTypeButtonCss: 'div.mb-3 > button[status="primary"]',
	backButtonCss: 'g[data-name="arrow-back"]',
	backFromInventoryButtonCss: 'div.navigate > button[status="primary"]',
	backFromCategoryButtonCss:
		'nb-card-header.d-flex div.navigate button[status="primary"]',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyTypeCss: 'div.ng-star-inserted',
	verifyCategorieCss: 'div.ng-star-inserted',
	verifyInventoryCss: 'ng-component > div > div.d-block'
};
