export const OrganizationTagsPage = {
	addTagButtonCss: 'button[status="success"]:has(nb-icon[icon="plus-outline"])',
	closeDialogButtonCss: 'nb-card-header span.cancel i.fa-times',
	tagNameInputCss: '#inputName',
	tagColorInputCss: '#inputColor',
	tagTenantCheckboxCss: 'span.custom-checkbox',
	tagDescriptionCss: '#inputDescription',
	cancelButtonCss: 'nb-card-footer.text-left > button[status="basic"]',
	saveButtonCss: '.text-left [status="success"]',
	gridButtonCss: 'div.layout-switch > button',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	editTagButtonCss: 'button.action.primary',
	deleteTagButtonCss: 'button.action:has(nb-icon[icon="trash-2-outline"])',
	confirmDeleteTagButtonCss: 'nb-card-footer > button[status="danger"]',
	cancelDeleteTagButtonCss: 'nb-card-footer > button[status="basic"]',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyTagCss: 'ngx-tags-color > div > nb-badge',
	filterNameInputCss: '[placeholder="Name"]',
	firstTableCellTagCss: 'tbody > tr.angular2-smart-row:first-of-type > td:first-of-type'
};
