export const OrganizationInventoryPage = {
	gridButtonCss: 'div.layout-switch > button',
	addButtonCss: 'div.mb-3 > button[status="success"]',
	languageDropdownCss: '#lang',
	dropdownOptionCss: '.option-list nb-option',
	nameInputCss: '#nameInput',
	codeInputCss: '#codeInput',
	productTypeDropdownCss: '#productTypeId',
	productCategoryDropdownCss: '#productCategoryId',
	descriptionInputCss: '#description',
	selectTableRowCss: 'table > tbody > tr.ng2-smart-row',
	saveButtonCss: 'nb-card-footer.text-right > button[status="success"]',
	editButtonCss: 'div.mb-3 > button[status="info"]',
	deleteButtonCss: 'div.mb-3 > button[status="danger"]',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	addCategoryOrTypeButtonCss: 'div.mb-3 > button[status="primary"]',
	backButtonCss: 'g[data-name="arrow-back"]',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyTypeCss: 'div.ng-star-inserted',
	verifyCategorieCss: 'div.ng-star-inserted',
	verifyInventoryCss: 'ga-picture-name-tags > div > div.d-block'
};
