export const OrganizationProjectsPage = {
	gridButtonCss: 'div.layout-switch > button',
	selectTableRowCss: 'table > tbody > tr.ng2-smart-row',
	tagsSelectCss: '#addTags',
	tagsSelectOptionCss: '[type="checkbox"]',
	closeTagsMultyselectDropdownCss: '.ng-select-container > .ng-arrow-wrapper',
	selectEmloyeeMultyselectCss: 'button[class="select-button placeholder"]',
	selectEmployeeDropdownOptionCss: '.option-list nb-option',
	requestNewProjectButtonCss: 'div.mb-3 > button[status="success"]',
	projectNameInputCss: '#name',
	codeInputCss: '#code',
	budgetInputCss: '[formcontrolname="budget"]',
	projectDescriptionCss: '[formcontrolname="description"]',
	tabButtonCss: 'a.tab-link',
	saveProjectButtonCss: 'div.form-group > button[status="success"]',
	editProjectButtonCss: 'div.mb-3 > button[status="info"]',
	deleteProjectButtonCss: 'div.mb-3 > button[status="danger"]',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	colorInputCss: '[formcontrolname="color"]',
	footerCss: 'nb-card-body > div.form-group',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyProjectCss: 'ga-picture-name-tags > div > div.d-block'
};
