export const PaymentsPage = {
	gridButtonCss: 'div.layout-switch > button',
	addPaymentButtonCss: 'div.mb-3 > button[status="success"]',
	dateInputCss: '[formcontrolname="paymentDate"]',
	vendorInputCss: '[formcontrolname="vendor"]',
	projectDropdownCss: '[formcontrolname="project"]',
	projectDropdownOptionCss: 'div.ng-option',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	paymentMethodDropdownCss: '[formcontrolname="paymentMethod"]',
	paymentMethodDropdownOptionCss: '.option-list nb-option',
	amountInputCss: '#inputAmount',
	noteInputCss: '#inputNote',
	saveExpenseButtonCss: 'nb-card-footer > button[status="success"]',
	selectTableRowCss: 'table > tbody > tr.ng2-smart-row',
	editPaymentButtonCss: 'div.mb-3 > button[status="info"]',
	deletePaymentButtonCss: 'div.mb-3 > button[status="danger"]',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	cardBodyCss: 'nb-card-footer.text-right'
};
