export const PipelinesPage = {
	gridButtonCss: 'div.layout-switch > button',
	addPipelineButtonCss: '.actions-container button[status="success"]',
	pipelineNameInputCss: 'nb-dialog-container [formcontrolname="name"]',
	descriptionInputCss: '[formcontrolname="description"]',
	createPipelineButtonCss: 'nb-card-footer > button[status="primary"]',
	selectTableRowCss: 'table > tbody > tr.angular2-smart-row',
	editPipelineButtonCss: '.actions-container .actions.ng-star-inserted button[status="basic"]:nth-child(2)',
	updateButtonCss: 'nb-card-footer > button[status="info"]',
	deletePipelineButtonCss: '.actions-container .actions.ng-star-inserted button[status="basic"]:nth-child(3)',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyPipelineCss: 'div.ng-star-inserted',
	stageButtonCss: 'nb-card-header > button',
	namePlaceholderCss: 'input[placeholder="Name"]',
	detailsButtonCss: 'div.mb-3 > button[status="basic"]',
	titleInputCss: 'input[placeholder="Title"]',
	createDealButtonCss: 'nb-card-footer > button[ng-reflect-status="primary"]',
	addDealPipelineButtonCss: 'div.mb-3 > div > button[status="success"]',
	probabilityInputCss: 'nb-select[formcontrolname="probability"]',
	dropdownOptionCss: 'ul.option-list > nb-option',
	backButtonCss: 'ngx-back-navigation > div.main > button'
};
