export const SalesEstimatesPage = {
	gridButtonCss: 'div.layout-switch > button',
	addButtonCss: 'div.actions-container button[status="success"]',
	editButtonCss: 'div.btn-group.actions button.action.primary',
	convertToInvoiceButton: 'div.btn-group.actions button[status="info"]',
	viewButtonCss: 'div.btn-group.actions button.action.secondary',
	popoverButtonCss: 'div.popover-container-action button',
	deleteButtonCss: 'div.popover-container-action button.danger',
	addTagsDropdownCss: '#addTags',
	tagsDropdownOption: 'div.ng-option',
	discountInputCss: '#inputDiscountValue',
	discountTypeDropdownCss: '[formcontrolname="discountType"]',
	dropdownOptionCss: '.option-list nb-option',
	organizationContactDropdownCss: 'ga-contact-select ng-select',
	contactOptionCss: 'div.ng-option',
	taxInputCss: '#inputTax',
	taxTypeDropdownCss: '[formcontrolname="taxType"]',
	invoiceTypeDropdownCss: '[formcontrolname="invoiceType"]',
	generateItemsButtonCss: 'div.buttons > button.gen',
	selectEmployeeCss: 'div.form-group ga-employee-multi-select nb-select',
	saveAsDraftButtonCss: 'nb-card-footer > button[status="primary"]',
	emailInputCss: '#email',
	tableRowCss: 'angular2-smart-table tbody tr',
	moreButtonCss: 'div.btn-group.actions button:has(nb-icon[icon="more-vertical-outline"])',
	toastrMessageCss: 'nb-toast.ng-trigger',
	cardBodyCss: 'nb-card-header.d-flex',
	backButtonCss: 'ngx-back-navigation button',
	deleteItemCss: 'i.nb-trash',
	confirmButtonCss: 'nb-card-footer.text-left > button[status="success"]',
	confirmDeleteButtonCss: 'nb-card-footer > button[status="danger"]',
	verifyEstimateCss: 'div.ng-star-inserted',
	draftBadgeCss: 'div.badge-warning',
	successBadgeCss: 'div.badge-success',
	emailCardCss: 'nb-card-body.invoice-email-body'
};
