export const TimeTrackingWithPausePage = {
	headerTextCss: 'nb-card-header h4',
	topCardHeaderTextCss: 'div.header-widget > div.title',
	bottomCardHeaderTextCss: 'ga-window-layout nb-card-header',
	recentActivitiesEmployeeCss: 'div.hour-lable > ngx-avatar > div.row > div.col > div.ng-star-inserted',
	projectsCss: 'nb-list > nb-lit-item > div.w-100 > div.row > div[class="col text-left"]',
	membersInfoCss: 'div.col > ngx-avatar > div[class="row align-items-center"] > div.col > div.ng-star-inserted',
	badgeCss: 'div.activity-percentage > badge[class="status-danger position-top position-right"]',
	timerCss: 'nb-action.timer-action',
	timerBtnCss: 'nb-action.timer-action nb-icon[icon="clock-outline"]',
	startTimerBtnCss: 'div.actions div.toggle button[status="success"]',
	stopTimerBtnCss: 'div.actions div.toggle button[status="danger"]',
	clientSelectCss: 'ga-contact-selector ng-select',
	projectSelectCss: 'ga-project-selector ng-select',
	taskSelectCss: 'ga-task-selector ng-select',
	descriptionInputCss: 'textarea[name="description"]',
	dropdownOptionCss: 'div.ng-option',
	closeBtnCss: 'button.btn-close',
	viewTimesheetBtnCss: 'div.view-log-button a[href="#/pages/employees/timesheets"]',
	manualBtnCss: 'button.switch:has(nb-icon[icon="menu-outline"])',
	dateInputCss: 'input[name="date"]',
	startTimeSelectCss: 'ga-timer-picker[name="start_time"]',
	endTimeSelectCss: 'ga-timer-picker[name="end_time"]',
	addTimeBtnCss: 'div.time-manual > button[status="success"]',
	todaySessionCss: 'div.time-count > span.today-time',
	tabBtnCss: 'li.route-tab > a.tab-link',
	verifyWorkCss: 'ga-window-layout div.project-name',
	verifyTimeCss: 'ga-widget-layout nb-card-body > div.h1',
	toastrMessageCss: 'nb-toast.ng-trigger',
	verifyManualTimeCss: 'div[class="row border-bottom py-3 align-items-center ng-star-inserted"] > div.col',
    verifyTrackedTimeCss: 'div[class="row border-bottom py-3 align-items-center ng-star-inserted"] > div.col',
	deleteTimeBtnCss: 'ngx-screenshots-item button[status="danger"]:has(nb-icon[icon="trash-2-outline"])',
	confirmDialogBtnCss: 'ngx-confirm nb-card-footer button[status="primary"]',
	headerImgCss: 'div.header-container'

};
