---
kind: Service
apiVersion: v1
metadata:
    name: gauzy-prod
spec:
    selector:
        app: gauzy-prod-webapp
    ports:
        - name: web
          protocol: TCP
          port: 4200
          targetPort: 4200
---
kind: Service
apiVersion: v1
metadata:
    name: gauzy-prod-api
spec:
    selector:
        app: gauzy-prod-api
    ports:
        - name: web
          protocol: TCP
          port: 3000
          targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gauzy-prod-api
spec:
    replicas: 16
    selector:
        matchLabels:
            app: gauzy-prod-api
    template:
        metadata:
            labels:
                app: gauzy-prod-api
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                          - matchExpressions:
                              - key: topology.kubernetes.io/region
                                operator: In
                                values:
                                  - ORD1
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      - podAffinityTerm:
                            labelSelector:
                                matchExpressions:
                                  - key: app
                                    operator: In
                                    values:
                                      - gauzy-prode-api
                            topologyKey: kubernetes.io/hostname
                        weight: 1
            imagePullSecrets:
              - name: ever-registry-docker-registry-credentials
            containers:
                - name: gauzy-prod-api
                  image: ever-registry.tenant-acb888-ever.ord1.ingress.coreweave.cloud/ever-co/gauzy-api:latest
                  env:
                      - name: API_HOST
                        value: 0.0.0.0
                      - name: DEMO
                        value: 'false'
                      - name: NODE_ENV
                        value: 'production'
                      - name: ADMIN_PASSWORD_RESET
                        value: 'true'
                      - name: LOG_LEVEL
                        value: 'info'
                      - name: SENTRY_DSN
                        value: '$SENTRY_DSN'
                      - name: SENTRY_HTTP_TRACING_ENABLED
                        value: 'false'
                      - name: SENTRY_POSTGRES_TRACKING_ENABLED
                        value: 'false'
                      - name: API_BASE_URL
                        value: 'https://apicw.gauzy.co'
                      - name: CLIENT_BASE_URL
                        value: 'https://appcw.gauzy.co'
                      - name: DB_URI
                        value: '$DB_URI'
                      - name: DB_HOST
                        value: '$DB_HOST'
                      - name: DB_SSL_MODE
                        value: '$DB_SSL_MODE'
                      - name: DB_CA_CERT
                        value: '$DB_CA_CERT'
                      - name: DB_USER
                        value: '$DB_USER'
                      - name: DB_PASS
                        value: '$DB_PASS'
                      - name: DB_TYPE
                        value: '$DB_TYPE'
                      - name: DB_NAME
                        value: '$DB_NAME'
                      - name: DB_PORT
                        value: '$DB_PORT'
                      - name: AWS_ACCESS_KEY_ID
                        value: '$AWS_ACCESS_KEY_ID'
                      - name: AWS_SECRET_ACCESS_KEY
                        value: '$AWS_SECRET_ACCESS_KEY'
                      - name: AWS_REGION
                        value: '$AWS_REGION'
                      - name: AWS_S3_BUCKET
                        value: '$AWS_S3_BUCKET'
                      - name: WASABI_ACCESS_KEY_ID
                        value: '$WASABI_ACCESS_KEY_ID'
                      - name: WASABI_SECRET_ACCESS_KEY
                        value: '$WASABI_SECRET_ACCESS_KEY'
                      - name: WASABI_REGION
                        value: '$WASABI_REGION'
                      - name: WASABI_SERVICE_URL
                        value: '$WASABI_SERVICE_URL'
                      - name: WASABI_S3_BUCKET
                        value: '$WASABI_S3_BUCKET'
                      - name: EXPRESS_SESSION_SECRET
                        value: '$EXPRESS_SESSION_SECRET'
                      - name: JWT_SECRET
                        value: '$JWT_SECRET'
                      - name: JWT_REFRESH_TOKEN_SECRET
                        value: '$JWT_REFRESH_TOKEN_SECRET'
                      - name: JWT_REFRESH_TOKEN_EXPIRATION_TIME
                        value: '$JWT_REFRESH_TOKEN_EXPIRATION_TIME'
                      - name: CLOUDINARY_API_KEY
                        value: '$CLOUDINARY_API_KEY'
                      - name: CLOUDINARY_API_SECRET
                        value: '$CLOUDINARY_API_SECRET'
                      - name: CLOUDINARY_CLOUD_NAME
                        value: '$CLOUDINARY_CLOUD_NAME'
                      - name: DEFAULT_CURRENCY
                        value: 'USD'
                      - name: MAIL_FROM_ADDRESS
                        value: '$MAIL_FROM_ADDRESS'
                      - name: MAIL_HOST
                        value: '$MAIL_HOST'
                      - name: MAIL_PORT
                        value: '$MAIL_PORT'
                      - name: MAIL_USERNAME
                        value: '$MAIL_USERNAME'
                      - name: MAIL_PASSWORD
                        value: '$MAIL_PASSWORD'
                      - name: ALLOW_SUPER_ADMIN_ROLE
                        value: '$ALLOW_SUPER_ADMIN_ROLE'
                      - name: GOOGLE_CLIENT_ID
                        value: '$GOOGLE_CLIENT_ID'
                      - name: GOOGLE_CLIENT_SECRET
                        value: '$GOOGLE_CLIENT_SECRET'
                      - name: GOOGLE_CALLBACK_URL
                        value: '$GOOGLE_CALLBACK_URL'
                      - name: FACEBOOK_CLIENT_ID
                        value: '$FACEBOOK_CLIENT_ID'
                      - name: FACEBOOK_CLIENT_SECRET
                        value: '$FACEBOOK_CLIENT_SECRET'
                      - name: FACEBOOK_GRAPH_VERSION
                        value: '$FACEBOOK_GRAPH_VERSION'
                      - name: FACEBOOK_CALLBACK_URL
                        value: '$FACEBOOK_CALLBACK_URL'
                      - name: INTEGRATED_USER_DEFAULT_PASS
                        value: '$INTEGRATED_USER_DEFAULT_PASS'
                      - name: UPWORK_CALLBACK_URL
                        value: '$UPWORK_CALLBACK_URL'
                      - name: FILE_PROVIDER
                        value: '$FILE_PROVIDER'
                      - name: GAUZY_AI_GRAPHQL_ENDPOINT
                        value: '$GAUZY_AI_GRAPHQL_ENDPOINT'
                      - name: GAUZY_AI_REST_ENDPOINT
                        value: '$GAUZY_AI_REST_ENDPOINT'
                      - name: UNLEASH_APP_NAME
                        value: '$UNLEASH_APP_NAME'
                      - name: UNLEASH_API_URL
                        value: '$UNLEASH_API_URL'
                      - name: UNLEASH_INSTANCE_ID
                        value: '$UNLEASH_INSTANCE_ID'
                      - name: UNLEASH_REFRESH_INTERVAL
                        value: '$UNLEASH_REFRESH_INTERVAL'
                      - name: UNLEASH_METRICS_INTERVAL
                        value: '$UNLEASH_METRICS_INTERVAL'
                      - name: UNLEASH_API_KEY
                        value: '$UNLEASH_API_KEY'
                      - name: PM2_PUBLIC_KEY
                        value: '$PM2_PUBLIC_KEY'
                      - name: PM2_SECRET_KEY
                        value: '$PM2_SECRET_KEY'
                      - name: PM2_MACHINE_NAME
                        value: '$PM2_MACHINE_NAME'

                  ports:
                      - containerPort: 3000
                        protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gauzy-prod-webapp
spec:
    replicas: 8
    selector:
        matchLabels:
            app: gauzy-prod-webapp
    template:
        metadata:
            labels:
                app: gauzy-prod-webapp
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                          - matchExpressions:
                              - key: topology.kubernetes.io/region
                                operator: In
                                values:
                                  - ORD1
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      - podAffinityTerm:
                            labelSelector:
                                matchExpressions:
                                  - key: app
                                    operator: In
                                    values:
                                      - gauzy-prod-webapp
                            topologyKey: kubernetes.io/hostname
                        weight: 1
            imagePullSecrets:
              - name: ever-registry-docker-registry-credentials
            containers:
                - name: gauzy-prod-webapp
                  image: ever-registry.tenant-acb888-ever.ord1.ingress.coreweave.cloud/ever-co/gauzy-webapp:latest
                  env:
                      - name: DEMO
                        value: 'false'
                      - name: API_BASE_URL
                        value: 'https://apicw.gauzy.co'
                      - name: CLIENT_BASE_URL
                        value: 'https://appcw.gauzy.co'
                      - name: SENTRY_DSN
                        value: 'https://7cd381188b6f446ca0e69185227b9031@o51327.ingest.sentry.io/4397292'
                      - name: CHATWOOT_SDK_TOKEN
                        value: 'fPgSSzSQoAWRuDqYyNXmpGLM'
                      - name: CLOUDINARY_API_KEY
                        value: '256868982483961'
                      - name: CLOUDINARY_CLOUD_NAME
                        value: 'dv6ezkfxg'
                      - name: GOOGLE_MAPS_API_KEY
                        value: 'AIzaSyCJmnKzgTSq5Pc93HXar5bZrdmANTwtSIo'
                      - name: GOOGLE_PLACE_AUTOCOMPLETE
                        value: 'true'
                      - name: DEFAULT_LATITUDE
                        value: '42.6459136'
                      - name: DEFAULT_LONGITUDE
                        value: '23.3332736'
                      - name: DEFAULT_CURRENCY
                        value: 'USD'
                  ports:
                      - containerPort: 4200
                        protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
spec:
  redirectScheme:
    permanent: true
    scheme: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gauzy-stage
  annotations:
    kubernetes.io/ingress.class: traefik-everco
    traefik.ingress.kubernetes.io/router.middlewares: tenant-acb888-ever-https-redirect@kubernetescrd
spec:
    rules:
      - host: appcw.gauzy.co
        http:
            paths:
              - backend:
                    service:
                        name: gauzy-prod
                        port:
                            number: 4200
                path: /
                pathType: Prefix
    tls:
      - hosts:
          - appcw.gauzy.co
        secretName: appcw.gauzy.co-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: gauzy-stage-api
    annotations:
        kubernetes.io/ingress.class: traefik-everco
        traefik.ingress.kubernetes.io/router.middlewares: tenant-acb888-ever-https-redirect@kubernetescrd
spec:
    rules:
      - host: apicw.gauzy.co
        http:
            paths:
              - backend:
                    service:
                        name: gauzy-prod-api
                        port:
                            number: 3000
                path: /
                pathType: Prefix
    tls:
      - hosts:
          - apicw.gauzy.co
        secretName: apicw.gauzy.co-tls
