import {
    tablerActivity,
    tablerAdjustmentsHorizontal,
    tablerAlertCircle,
    tablerAlertTriangle,
    tablerArchive,
    tablerArrowBackUp,
    tablerArrowDown,
    tablerArrowForwardUp,
    tablerArrowLeft,
    tablerArrowRight,
    tablerArrowUp,
    tablerArrowUpCircle,
    tablerArrowUpRight,
    tablerArrowsExchange,
    tablerArrowsMinimize,
    tablerArrowsMove,
    tablerArrowsShuffle,
    tablerAt,
    tablerAward,
    tablerBell,
    tablerBolt,
    tablerBook,
    tablerBookmark,
    tablerBrandFacebook,
    tablerBrandGithub,
    tablerBrandGoogle,
    tablerBrandLinkedin,
    tablerBrandNpm,
    tablerBrandWindows,
    tablerBrandX,
    tablerBriefcase,
    tablerBrowser,
    tablerBrush,
    tablerBug,
    tablerBulb,
    tablerCalendar,
    tablerCamera,
    tablerCar,
    tablerCash,
    tablerCast,
    tablerChartBar,
    tablerChartPie,
    tablerCheck,
    tablerChecks,
    tablerChevronDown,
    tablerChevronLeft,
    tablerChevronRight,
    tablerChevronUp,
    tablerCircle,
    tablerCircleCheck,
    tablerCircleDot,
    tablerCircleMinus,
    tablerCirclePlus,
    tablerCircleX,
    tablerClock,
    tablerClipboard,
    tablerCloudDownload,
    tablerCloudUpload,
    tablerCode,
    tablerCompass,
    tablerCopy,
    tablerCornerDownRight,
    tablerCpu,
    tablerCreditCard,
    tablerCube,
    tablerDeviceAnalytics,
    tablerDeviceCctv,
    tablerDeviceDesktop,
    tablerDeviceFloppy,
    tablerDeviceMobile,
    tablerDeviceTv,
    tablerDots,
    tablerDotsVertical,
    tablerDownload,
    tablerDroplet,
    tablerEdit,
    tablerExternalLink,
    tablerEye,
    tablerEyeOff,
    tablerFile,
    tablerFilePlus,
    tablerFileText,
    tablerFilter,
    tablerFlag,
    tablerFolder,
    tablerFolderPlus,
    tablerGauge,
    tablerGift,
    tablerGitBranch,
    tablerGitCommit,
    tablerGlobe,
    tablerGridDots,
    tablerHash,
    tablerHeart,
    tablerHelp,
    tablerHome,
    tablerHourglass,
    tablerInbox,
    tablerInfoCircle,
    tablerKeyboard,
    tablerLayout,
    tablerLink,
    tablerList,
    tablerLoader,
    tablerLock,
    tablerLockOpen,
    tablerLogin,
    tablerLogout,
    tablerMail,
    tablerMap,
    tablerMaximize,
    tablerMenu2,
    tablerMenuOrder,
    tablerMessage,
    tablerMessageCircle,
    tablerMicrophone,
    tablerMinus,
    tablerMoodSmile,
    tablerMoon,
    tablerMovie,
    tablerNavigation,
    tablerPalette,
    tablerPaperclip,
    tablerPercentage,
    tablerPhone,
    tablerPhoneCall,
    tablerPhoto,
    tablerPhotoOff,
    tablerPin,
    tablerPlayerPause,
    tablerPlayerPlay,
    tablerPlayerSkipBack,
    tablerPlayerSkipForward,
    tablerPlayerStop,
    tablerPlus,
    tablerPower,
    tablerPrinter,
    tablerPuzzle,
    tablerRefresh,
    tablerRepeat,
    tablerRefreshDot,
    tablerRotate2,
    tablerScissors,
    tablerSearch,
    tablerSend,
    tablerServer,
    tablerSettings,
    tablerShare,
    tablerShield,
    tablerShieldCheck,
    tablerShieldOff,
    tablerShoppingBag,
    tablerShoppingCart,
    tablerSlash,
    tablerSquare,
    tablerSquareCheck,
    tablerSquareMinus,
    tablerSquarePlus,
    tablerSquareX,
    tablerStack2,
    tablerStar,
    tablerStopwatch,
    tablerSun,
    tablerTags,
    tablerTextCaption,
    tablerThermometer,
    tablerThumbDown,
    tablerThumbUp,
    tablerTrash,
    tablerTrendingDown,
    tablerTrendingUp,
    tablerUmbrella,
    tablerUpload,
    tablerUser,
    tablerUserCheck,
    tablerUserMinus,
    tablerUserPlus,
    tablerUserX,
    tablerUsers,
    tablerVideo,
    tablerVolume,
    tablerVolume2,
    tablerVolume3,
    tablerVolumeOff,
    tablerWifi,
    tablerX
} from '@ng-icons/tabler-icons';

import {
    tablerAlertCircleFill,
    tablerAlertTriangleFill,
    tablerArchiveFill,
    tablerArrowUpCircleFill,
    tablerAwardFill,
    tablerBellFill,
    tablerBoltFill,
    tablerBookFill,
    tablerBrandFacebookFill,
    tablerBrandGithubFill,
    tablerHourglassFill,
    tablerBrandGoogleFill,
    tablerBrandLinkedinFill,
    tablerBrandWindowsFill,
    tablerBrandXFill,
    tablerBriefcaseFill,
    tablerBulbFill,
    tablerCalendarFill,
    tablerCameraFill,
    tablerCarFill,
    tablerChartPieFill,
    tablerCircleCheckFill,
    tablerCircleDotFill,
    tablerCircleFill,
    tablerCirclePlusFill,
    tablerCircleXFill,
    tablerClockFill,
    tablerCompassFill,
    tablerCreditCardFill,
    tablerDeviceCctvFill,
    tablerDeviceDesktopFill,
    tablerDeviceMobileFill,
    tablerDeviceTvFill,
    tablerEyeFill,
    tablerFileFill,
    tablerFileTextFill,
    tablerFilterFill,
    tablerFlagFill,
    tablerFolderFill,
    tablerGiftFill,
    tablerGlobeFill,
    tablerHeartFill,
    tablerHomeFill,
    tablerInfoCircleFill,
    tablerKeyboardFill,
    tablerLayoutFill,
    tablerLockFill,
    tablerMailFill,
    tablerMessageCircleFill,
    tablerMessageFill,
    tablerMicrophoneFill,
    tablerMoodSmileFill,
    tablerMoonFill,
    tablerNavigationFill,
    tablerPaletteFill,
    tablerPhoneFill,
    tablerPhotoFill,
    tablerPinFill,
    tablerPlayerPauseFill,
    tablerPlayerPlayFill,
    tablerPlayerSkipBackFill,
    tablerPlayerSkipForwardFill,
    tablerPlayerStopFill,
    tablerPuzzleFill,
    tablerSettingsFill,
    tablerShieldCheckFill,
    tablerShieldFill,
    tablerShoppingCartFill,
    tablerSquareCheckFill,
    tablerSquareFill,
    tablerSquareMinusFill,
    tablerSquareXFill,
    tablerStack2Fill,
    tablerStarFill,
    tablerSunFill,
    tablerTagsFill,
    tablerThumbDownFill,
    tablerThumbUpFill,
    tablerTrashFill,
    tablerUmbrellaFill,
    tablerUserFill,
    tablerVideoFill
} from '@ng-icons/tabler-icons/fill';

export const evaToTablerIcons = {
    activity: tablerActivity,
    'activity-outline': tablerActivity,
    'alert-circle': tablerAlertCircleFill,
    'alert-circle-outline': tablerAlertCircle,
    'alert-triangle': tablerAlertTriangleFill,
    'alert-triangle-outline': tablerAlertTriangle,
    'analytics-outline': tablerDeviceAnalytics,
    'angle-left': tablerChevronLeft,
    'angle-right': tablerChevronRight,
    archive: tablerArchiveFill,
    'archive-outline': tablerArchive,
    'arrow-back': tablerArrowLeft,
    'arrow-back-outline': tablerArrowLeft,
    'arrow-circle-up': tablerArrowUpCircleFill,
    'arrow-circle-up-outline': tablerArrowUpCircle,
    'arrow-up-outline': tablerArrowUp,
    'arrow-downward-outline': tablerArrowDown,
    'arrow-forward-outline': tablerArrowRight,
    'arrow-ios-back': tablerChevronLeft,
    'arrow-ios-back-outline': tablerChevronLeft,
    'arrow-ios-downward': tablerChevronDown,
    'arrow-ios-downward-outline': tablerChevronDown,
    'arrow-ios-forward': tablerChevronRight,
    'arrow-ios-forward-outline': tablerChevronRight,
    'arrow-left': tablerArrowLeft,
    'arrow-left-outline': tablerArrowLeft,
    'arrow-right': tablerArrowRight,
    'arrow-right-outline': tablerArrowRight,
    'arrow-upward-outline': tablerArrowUp,
    'arrowhead-down-outline': tablerChevronDown,
    'arrowhead-left-outline': tablerChevronLeft,
    'arrowhead-right-outline': tablerChevronRight,
    'at-outline': tablerAt,
    'attach-2': tablerPaperclip,
    'attach-2-outline': tablerPaperclip,
    'attach-outline': tablerPaperclip,
    award: tablerAwardFill,
    'award-outline': tablerAward,
    'bar-chart-2-outline': tablerChartBar,
    'bar-chart-outline': tablerChartBar,
    bell: tablerBellFill,
    'bell-outline': tablerBell,
    book: tablerBookFill,
    'book-open': tablerBookFill,
    'book-open-outline': tablerBook,
    'book-outline': tablerBook,
    'bookmark-outline': tablerBookmark,
    briefcase: tablerBriefcaseFill,
    'briefcase-outline': tablerBriefcase,
    'brush-outline': tablerBrush,
    'bug-outline': tablerBug,
    'business-outline': tablerBriefcase,
    'browser-outline': tablerBrowser,
    bulb: tablerBulbFill,
    'bulb-outline': tablerBulb,
    calendar: tablerCalendarFill,
    'calendar-outline': tablerCalendar,
    camera: tablerCameraFill,
    'camera-outline': tablerCamera,
    car: tablerCarFill,
    'car-outline': tablerCar,
    card: tablerCreditCardFill,
    'card-outline': tablerCreditCard,
    'cash-outline': tablerCash,
    'cast-outline': tablerCast,
    'check-circle': tablerCircleCheckFill,
    'checkmark-circle': tablerCircleCheckFill,
    'checkmark-circle-2': tablerCircleCheckFill,
    'checkmark-circle-2-outline': tablerCircleCheck,
    'checkmark-circle-outline': tablerCircleCheck,
    'checkmark-outline': tablerCheck,
    'checkmark-square': tablerSquareCheckFill,
    'checkmark-square-2': tablerSquareCheckFill,
    'checkmark-square-2-outline': tablerSquareCheck,
    'checkmark-square-outline': tablerSquareCheck,
    'chevron-down': tablerChevronDown,
    'chevron-down-outline': tablerChevronDown,
    'chevron-left': tablerChevronLeft,
    'chevron-left-outline': tablerChevronLeft,
    'chevron-right': tablerChevronRight,
    'chevron-right-outline': tablerChevronRight,
    'chevron-up': tablerChevronUp,
    'chevron-up-outline': tablerChevronUp,
    clock: tablerClockFill,
    'clipboard-outline': tablerClipboard,
    'clock-outline': tablerClock,
    close: tablerX,
    'close-circle': tablerCircleXFill,
    'close-circle-outline': tablerCircleX,
    'close-outline': tablerX,
    'close-square': tablerSquareXFill,
    'close-square-outline': tablerSquareX,
    'cloud-download-outline': tablerCloudDownload,
    'cloud-upload-outline': tablerCloudUpload,
    'code-outline': tablerCode,
    cog: tablerSettingsFill,
    'cog-outline': tablerSettings,
    'collapse-outline': tablerArrowsMinimize,
    'color-palette': tablerPaletteFill,
    'color-palette-outline': tablerPalette,
    compass: tablerCompassFill,
    'compass-outline': tablerCompass,
    copy: tablerCopy,
    'copy-outline': tablerCopy,
    'corner-down-right-outline': tablerCornerDownRight,
    'cpu-outline': tablerCpu,
    'credit-card': tablerCreditCardFill,
    'credit-card-outline': tablerCreditCard,
    'cube-outline': tablerCube,
    'diagonal-arrow-right-up-outline': tablerArrowUpRight,
    'done-all-outline': tablerChecks,
    'droplet-outline': tablerDroplet,
    download: tablerDownload,
    'download-outline': tablerDownload,
    edit: tablerEdit,
    'edit-2': tablerEdit,
    'edit-2-outline': tablerEdit,
    'edit-outline': tablerEdit,
    email: tablerMailFill,
    'email-outline': tablerMail,
    'expand-outline': tablerMaximize,
    'exit-outline': tablerLogout,
    'external-link-outline': tablerExternalLink,
    eye: tablerEyeFill,
    'eye-off': tablerEyeOff,
    'eye-off-2-outline': tablerEyeOff,
    'eye-off-outline': tablerEyeOff,
    'eye-outline': tablerEye,
    facebook: tablerBrandFacebookFill,
    'facebook-outline': tablerBrandFacebook,
    file: tablerFileFill,
    'file-add-outline': tablerFilePlus,
    'file-outline': tablerFile,
    'file-text': tablerFileTextFill,
    'file-text-outline': tablerFileText,
    'film-outline': tablerMovie,
    flag: tablerFlagFill,
    'flag-outline': tablerFlag,
    flash: tablerBoltFill,
    'flash-outline': tablerBolt,
    'flip-outline': tablerRotate2,
    'flip-2-outline': tablerRotate2,
    folder: tablerFolderFill,
    'folder-add-outline': tablerFolderPlus,
    'folder-outline': tablerFolder,
    funnel: tablerFilterFill,
    'funnel-outline': tablerFilter,
    gift: tablerGiftFill,
    'gift-outline': tablerGift,
    'git-branch-outline': tablerGitBranch,
    'git-commit-outline': tablerGitCommit,
    github: tablerBrandGithubFill,
    'github-outline': tablerBrandGithub,
    globe: tablerGlobeFill,
    'globe-2': tablerGlobeFill,
    'globe-2-outline': tablerGlobe,
    'globe-outline': tablerGlobe,
    google: tablerBrandGoogleFill,
    'google-outline': tablerBrandGoogle,
    grid: tablerGridDots,
    'grid-outline': tablerGridDots,
    'grid-view': tablerGridDots,
    'hand-left-outline': tablerPin,
    'hard-drive-outline': tablerServer,
    'hardware-chip-outline': tablerCpu,
    'hash-outline': tablerHash,
    heart: tablerHeartFill,
    'heart-outline': tablerHeart,
    'help-circle-outline': tablerHelp,
    home: tablerHomeFill,
    'home-outline': tablerHome,
    hourglass: tablerHourglassFill,
    'hourglass-outline': tablerHourglass,
    image: tablerPhotoFill,
    'image-off-outline': tablerPhotoOff,
    'image-outline': tablerPhoto,
    'inbox-outline': tablerInbox,
    info: tablerInfoCircleFill,
    'info-circle': tablerInfoCircleFill,
    'info-circle-outline': tablerInfoCircle,
    'info-outline': tablerInfoCircle,
    keypad: tablerKeyboardFill,
    'keypad-outline': tablerKeyboard,
    layers: tablerStack2Fill,
    'layers-outline': tablerStack2,
    layout: tablerLayoutFill,
    'layout-outline': tablerLayout,
    'link-2-outline': tablerLink,
    'link-outline': tablerLink,
    linkedin: tablerBrandLinkedinFill,
    'linkedin-outline': tablerBrandLinkedin,
    list: tablerList,
    'list-outline': tablerList,
    'loader-outline': tablerLoader,
    lock: tablerLockFill,
    'lock-closed-outline': tablerLock,
    'lock-outline': tablerLock,
    'log-in': tablerLogin,
    'log-in-outline': tablerLogin,
    'log-out-outline': tablerLogout,
    'map-outline': tablerMap,
    'menu-2-outline': tablerMenu2,
    'menu-arrow-outline': tablerMenuOrder,
    'menu-outline': tablerMenu2,
    'message-circle': tablerMessageCircleFill,
    'message-circle-outline': tablerMessageCircle,
    'message-square': tablerMessageFill,
    'message-square-outline': tablerMessage,
    mic: tablerMicrophoneFill,
    'mic-outline': tablerMicrophone,
    microsoft: tablerBrandWindowsFill,
    'microsoft-outline': tablerBrandWindows,
    minus: tablerMinus,
    'minus-circle': tablerCircleMinus,
    'minus-circle-outline': tablerCircleMinus,
    'minus-outline': tablerMinus,
    'minus-square': tablerSquareMinusFill,
    'minus-square-outline': tablerSquareMinus,
    monitor: tablerDeviceDesktopFill,
    'monitor-outline': tablerDeviceDesktop,
    moon: tablerMoonFill,
    'moon-outline': tablerMoon,
    'more-horizontal-outline': tablerDots,
    'more-vertical-outline': tablerDotsVertical,
    'move-outline': tablerArrowsMove,
    'navigation-2': tablerNavigationFill,
    'navigation-2-outline': tablerNavigation,
    npm: tablerBrandNpm,
    'npm-outline': tablerBrandNpm,
    'options-2-outline': tablerAdjustmentsHorizontal,
    'options-outline': tablerAdjustmentsHorizontal,
    pantone: tablerPaletteFill,
    'pantone-outline': tablerPalette,
    'paper-plane-outline': tablerSend,
    pause: tablerPlayerPauseFill,
    'pause-circle': tablerPlayerPauseFill,
    'pause-circle-outline': tablerPlayerPause,
    'people-outline': tablerUsers,
    percent: tablerPercentage,
    'percent-outline': tablerPercentage,
    person: tablerUserFill,
    'person-add-outline': tablerUserPlus,
    'person-delete-outline': tablerUserX,
    'person-done-outline': tablerUserCheck,
    'person-outline': tablerUser,
    'person-remove-outline': tablerUserMinus,
    phone: tablerPhoneFill,
    'phone-call-outline': tablerPhoneCall,
    'phone-outline': tablerPhone,
    'pie-chart': tablerChartPieFill,
    'pie-chart-outline': tablerChartPie,
    pin: tablerPinFill,
    'pin-outline': tablerPin,
    play: tablerPlayerPlayFill,
    'play-circle': tablerPlayerPlayFill,
    'play-circle-outline': tablerPlayerPlay,
    plus: tablerPlus,
    'plus-circle': tablerCirclePlusFill,
    'plus-circle-outline': tablerCirclePlus,
    'plus-outline': tablerPlus,
    'plus-square-outline': tablerSquarePlus,
    'power-outline': tablerPower,
    pricetags: tablerTagsFill,
    'pricetags-outline': tablerTags,
    'printer-outline': tablerPrinter,
    puzzle: tablerPuzzleFill,
    'puzzle-outline': tablerPuzzle,
    'question-mark-circle-outline': tablerHelp,
    'radio-button-off': tablerCircleFill,
    'radio-button-off-outline': tablerCircle,
    'radio-button-on': tablerCircleDotFill,
    'radio-button-on-outline': tablerCircleDot,
    recording: tablerDeviceCctvFill,
    'recording-outline': tablerDeviceCctv,
    'redo-alt': tablerArrowForwardUp,
    'repeat-outline': tablerRepeat,
    'refresh-outline': tablerRefresh,
    save: tablerDeviceFloppy,
    'save-outline': tablerDeviceFloppy,
    'scissors-outline': tablerScissors,
    search: tablerSearch,
    'search-outline': tablerSearch,
    settings: tablerSettingsFill,
    'settings-2': tablerSettingsFill,
    'settings-2-outline': tablerSettings,
    'settings-outline': tablerSettings,
    'share-outline': tablerShare,
    shield: tablerShieldFill,
    'shield-checkmark': tablerShieldCheckFill,
    'shield-checkmark-outline': tablerShieldCheck,
    'shield-off-outline': tablerShieldOff,
    'shield-outline': tablerShield,
    'shopping-bag-outline': tablerShoppingBag,
    'shopping-cart': tablerShoppingCartFill,
    'shopping-cart-outline': tablerShoppingCart,
    'shuffle-2-outline': tablerArrowsShuffle,
    'skip-back': tablerPlayerSkipBackFill,
    'skip-back-outline': tablerPlayerSkipBack,
    'skip-forward': tablerPlayerSkipForwardFill,
    'skip-forward-outline': tablerPlayerSkipForward,
    'slash-outline': tablerSlash,
    smartphone: tablerDeviceMobileFill,
    'smartphone-outline': tablerDeviceMobile,
    'smiling-face': tablerMoodSmileFill,
    'smiling-face-outline': tablerMoodSmile,
    'speaker-outline': tablerVolume,
    square: tablerSquareFill,
    'speedometer-outline': tablerGauge,
    'square-outline': tablerSquare,
    star: tablerStarFill,
    'star-outline': tablerStar,
    'stop-circle': tablerPlayerStopFill,
    'stop-circle-outline': tablerPlayerStop,
    stopwatch: tablerStopwatch,
    sun: tablerSunFill,
    'sun-outline': tablerSun,
    swap: tablerArrowsExchange,
    'swap-outline': tablerArrowsExchange,
    'sync-alt': tablerRefreshDot,
    'sync-outline': tablerRefresh,
    'text-outline': tablerTextCaption,
    'thermometer-outline': tablerThermometer,
    'thumbs-down': tablerThumbDownFill,
    'thumbs-down-outline': tablerThumbDown,
    'thumbs-up': tablerThumbUpFill,
    'thumbs-up-outline': tablerThumbUp,
    time: tablerClockFill,
    'time-outline': tablerClock,
    trash: tablerTrashFill,
    'trash-2': tablerTrashFill,
    'trash-2-outline': tablerTrash,
    'trash-outline': tablerTrash,
    'trending-down-outline': tablerTrendingDown,
    'trending-up-outline': tablerTrendingUp,
    tv: tablerDeviceTvFill,
    'tv-outline': tablerDeviceTv,
    twitter: tablerBrandXFill,
    'twitter-outline': tablerBrandX,
    umbrella: tablerUmbrellaFill,
    'umbrella-outline': tablerUmbrella,
    'undo-outline': tablerArrowBackUp,
    'unlock-outline': tablerLockOpen,
    'upload-outline': tablerUpload,
    video: tablerVideoFill,
    'video-outline': tablerVideo,
    'volume-down-outline': tablerVolume2,
    'volume-mute-outline': tablerVolume3,
    'volume-off-outline': tablerVolumeOff,
    'volume-up-outline': tablerVolume,
    'warning-outline': tablerAlertTriangle,
    'wifi-outline': tablerWifi
};
