import { IBasePerTenantEntityModel, ID } from './base-entity.model';
import { IRole } from './role.model';

export type IRolePermissions = IRolePermission[];

export interface IRolePermissionMigrateInput extends IBasePerTenantEntityModel {
	permission: string;
	role: string;
	isImporting: boolean;
	sourceId: string;
	description: string;
}

export interface IRolePermission extends IBasePerTenantEntityModel {
	role: IRole;
	roleId: ID;
	permission: string;
	enabled: boolean;
	description: string;
}

export interface IRolePermissionCreateInput extends IBasePerTenantEntityModel {
	role?: IRole;
	roleId: ID;
	permission: string;
	enabled: boolean;
}

export interface IRolePermissionFindInput extends IBasePerTenantEntityModel {
	roleId?: ID;
	permission?: string;
	enabled?: boolean;
}

export interface IRolePermissionUpdateInput extends IRolePermissionCreateInput {
	enabled: boolean;
}

export enum PermissionsEnum {
	ADMIN_DASHBOARD_VIEW = 'ADMIN_DASHBOARD_VIEW',
	TEAM_DASHBOARD = 'TEAM_DASHBOARD',
	PROJECT_MANAGEMENT_DASHBOARD = 'PROJECT_MANAGEMENT_DASHBOARD',
	TIME_TRACKING_DASHBOARD = 'TIME_TRACKING_DASHBOARD',
	ACCOUNTING_DASHBOARD = 'ACCOUNTING_DASHBOARD',
	HUMAN_RESOURCE_DASHBOARD = 'HUMAN_RESOURCE_DASHBOARD',
	ORG_PAYMENT_VIEW = 'ORG_PAYMENT_VIEW',
	ORG_PAYMENT_ADD_EDIT = 'ORG_PAYMENT_ADD_EDIT',
	ORG_INCOMES_VIEW = 'ORG_INCOMES_VIEW',
	ORG_INCOMES_EDIT = 'ORG_INCOMES_EDIT',
	/** Payroll Permissions */
	ORG_PAYROLL_VIEW = 'ORG_PAYROLL_VIEW',
	ORG_PAYROLL_EDIT = 'ORG_PAYROLL_EDIT',
	ORG_PAYROLL_APPROVE = 'ORG_PAYROLL_APPROVE',
	ORG_EXPENSES_VIEW = 'ORG_EXPENSES_VIEW',
	ORG_EXPENSES_EDIT = 'ORG_EXPENSES_EDIT',
	PROFILE_EDIT = 'PROFILE_EDIT',
	EMPLOYEE_EXPENSES_VIEW = 'EMPLOYEE_EXPENSES_VIEW',
	EMPLOYEE_EXPENSES_EDIT = 'EMPLOYEE_EXPENSES_EDIT',
	ORG_PROPOSALS_VIEW = 'ORG_PROPOSALS_VIEW',
	ORG_PROPOSALS_EDIT = 'ORG_PROPOSALS_EDIT',
	ORG_PROPOSAL_TEMPLATES_VIEW = 'ORG_PROPOSAL_TEMPLATES_VIEW',
	ORG_PROPOSAL_TEMPLATES_EDIT = 'ORG_PROPOSAL_TEMPLATES_EDIT',
	// Task CRUD Permission
	ORG_TASK_ADD = 'ORG_TASK_ADD',
	ORG_TASK_VIEW = 'ORG_TASK_VIEW',
	ORG_TASK_EDIT = 'ORG_TASK_EDIT',
	ORG_TASK_DELETE = 'ORG_TASK_DELETE',
	// Employee CRUD Permissions
	ORG_EMPLOYEES_ADD = 'ORG_EMPLOYEES_ADD',
	ORG_EMPLOYEES_VIEW = 'ORG_EMPLOYEES_VIEW',
	ORG_EMPLOYEES_EDIT = 'ORG_EMPLOYEES_EDIT',
	ORG_EMPLOYEES_DELETE = 'ORG_EMPLOYEES_DELETE',
	// Member View Permissions
	ORG_MEMBERS_VIEW = 'ORG_MEMBERS_VIEW',
	ORG_CANDIDATES_VIEW = 'ORG_CANDIDATES_VIEW',
	ORG_CANDIDATES_EDIT = 'ORG_CANDIDATES_EDIT',
	ORG_CANDIDATES_INTERVIEW_EDIT = 'ORG_CANDIDATES_INTERVIEW_EDIT',
	ORG_CANDIDATES_INTERVIEW_VIEW = 'ORG_CANDIDATES_INTERVIEW_VIEW',
	ORG_CANDIDATES_DOCUMENTS_VIEW = 'ORG_CANDIDATES_DOCUMENTS_VIEW',
	ORG_CANDIDATES_TASK_EDIT = 'ORG_CANDIDATES_TASK_EDIT',
	ORG_CANDIDATES_FEEDBACK_EDIT = 'ORG_CANDIDATES_FEEDBACK_EDIT',
	ORG_INVENTORY_PRODUCT_EDIT = 'ORG_INVENTORY_PRODUCT_EDIT',
	ORG_INVENTORY_VIEW = 'ORG_INVENTORY_VIEW',
	/** Tags CRUD Permissions */
	ORG_TAGS_ADD = 'ORG_TAGS_ADD',
	ORG_TAGS_VIEW = 'ORG_TAGS_VIEW',
	ORG_TAGS_EDIT = 'ORG_TAGS_EDIT',
	ORG_TAGS_DELETE = 'ORG_TAGS_DELETE',
	/** Tag Types CRUD Permissions */
	ORG_TAG_TYPES_ADD = 'ORG_TAG_TYPES_ADD',
	ORG_TAG_TYPES_VIEW = 'ORG_TAG_TYPES_VIEW',
	ORG_TAG_TYPES_EDIT = 'ORG_TAG_TYPES_EDIT',
	ORG_TAG_TYPES_DELETE = 'ORG_TAG_TYPES_DELETE',
	ORG_USERS_VIEW = 'ORG_USERS_VIEW',
	ORG_USERS_EDIT = 'ORG_USERS_EDIT',
	ORG_INVITE_VIEW = 'ORG_INVITE_VIEW',
	ORG_INVITE_EDIT = 'ORG_INVITE_EDIT',
	ALL_ORG_VIEW = 'ALL_ORG_VIEW',
	ALL_ORG_EDIT = 'ALL_ORG_EDIT',
	/** Time Off Policy CRUD Permissions */
	TIME_OFF_POLICY_ADD = 'TIME_OFF_POLICY_ADD',
	TIME_OFF_POLICY_VIEW = 'TIME_OFF_POLICY_VIEW',
	TIME_OFF_POLICY_EDIT = 'TIME_OFF_POLICY_EDIT',
	TIME_OFF_POLICY_DELETE = 'TIME_OFF_POLICY_DELETE',
	/** Time Off CRUD Permissions */
	TIME_OFF_ADD = 'TIME_OFF_ADD',
	TIME_OFF_VIEW = 'TIME_OFF_VIEW',
	TIME_OFF_EDIT = 'TIME_OFF_EDIT',
	TIME_OFF_DELETE = 'TIME_OFF_DELETE',
	REQUEST_APPROVAL_VIEW = 'REQUEST_APPROVAL_VIEW',
	REQUEST_APPROVAL_EDIT = 'REQUEST_APPROVAL_EDIT',
	APPROVAL_POLICY_VIEW = 'APPROVALS_POLICY_VIEW',
	APPROVAL_POLICY_EDIT = 'APPROVALS_POLICY_EDIT',
	SELECT_EMPLOYEE = 'SELECT_EMPLOYEE',
	CHANGE_SELECTED_EMPLOYEE = 'CHANGE_SELECTED_EMPLOYEE',
	CHANGE_SELECTED_CANDIDATE = 'CHANGE_SELECTED_CANDIDATE',
	CHANGE_SELECTED_ORGANIZATION = 'CHANGE_SELECTED_ORGANIZATION',
	CHANGE_ROLES_PERMISSIONS = 'CHANGE_ROLES_PERMISSIONS',
	ACCESS_PRIVATE_PROJECTS = 'ACCESS_PRIVATE_PROJECTS',
	TIMESHEET_EDIT_TIME = 'TIMESHEET_EDIT_TIME',
	SUPER_ADMIN_EDIT = 'SUPER_ADMIN_EDIT',
	PUBLIC_PAGE_EDIT = 'PUBLIC_PAGE_EDIT',
	INVOICES_VIEW = 'INVOICES_VIEW',
	INVOICES_EDIT = 'INVOICES_EDIT',
	ESTIMATES_VIEW = 'ESTIMATES_VIEW',
	ESTIMATES_EDIT = 'ESTIMATES_EDIT',
	ORG_CANDIDATES_INTERVIEWERS_EDIT = 'ORG_CANDIDATES_INTERVIEWERS_EDIT',
	ORG_CANDIDATES_INTERVIEWERS_VIEW = 'ORG_CANDIDATES_INTERVIEWERS_VIEW',
	VIEW_ALL_EMAILS = 'VIEW_ALL_EMAILS',
	VIEW_ALL_EMAIL_TEMPLATES = 'VIEW_ALL_EMAIL_TEMPLATES',
	ORG_HELP_CENTER_EDIT = 'ORG_HELP_CENTER_EDIT',
	VIEW_SALES_PIPELINES = 'VIEW_SALES_PIPELINES',
	EDIT_SALES_PIPELINES = 'EDIT_SALES_PIPELINES',
	CAN_APPROVE_TIMESHEET = 'CAN_APPROVE_TIMESHEET',
	ORG_SPRINT_ADD = 'ORG_SPRINT_ADD',
	ORG_SPRINT_VIEW = 'ORG_SPRINT_VIEW',
	ORG_SPRINT_EDIT = 'ORG_SPRINT_EDIT',
	ORG_SPRINT_DELETE = 'ORG_SPRINT_DELETE',
	ORG_CONTACT_EDIT = 'ORG_CONTACT_EDIT',
	ORG_CONTACT_VIEW = 'ORG_CONTACT_VIEW',
	ORG_PROJECT_ADD = 'ORG_PROJECT_ADD',
	ORG_PROJECT_VIEW = 'ORG_PROJECT_VIEW',
	ORG_PROJECT_EDIT = 'ORG_PROJECT_EDIT',
	ORG_PROJECT_DELETE = 'ORG_PROJECT_DELETE',
	/** Organization Team */
	ORG_TEAM_ADD = 'ORG_TEAM_ADD',
	ORG_TEAM_VIEW = 'ORG_TEAM_VIEW',
	ORG_TEAM_EDIT = 'ORG_TEAM_EDIT',
	ORG_TEAM_EDIT_ACTIVE_TASK = 'ORG_TEAM_EDIT_ACTIVE_TASK',
	ORG_TEAM_DELETE = 'ORG_TEAM_DELETE',
	ORG_TEAM_REMOVE_ACCOUNT_AS_MEMBER = 'ORG_TEAM_REMOVE_ACCOUNT_AS_MEMBER',
	/** Organization Team Join Request Permissions */
	ORG_TEAM_JOIN_REQUEST_VIEW = 'ORG_TEAM_JOIN_REQUEST_VIEW',
	ORG_TEAM_JOIN_REQUEST_EDIT = 'ORG_TEAM_JOIN_REQUEST_EDIT',
	/** Organization Task Setting */
	ORG_TASK_SETTING = 'ORG_TASK_SETTING',
	ORG_CONTRACT_EDIT = 'ORG_CONTRACT_EDIT',
	EVENT_TYPES_VIEW = 'EVENT_TYPES_VIEW',
	TIME_TRACKER = 'TIME_TRACKER',
	TENANT_ADD_EXISTING_USER = 'TENANT_ADD_EXISTING_USER',
	/** Integration CRUD Permissions Start */
	INTEGRATION_ADD = 'INTEGRATION_ADD',
	INTEGRATION_VIEW = 'INTEGRATION_VIEW',
	INTEGRATION_EDIT = 'INTEGRATION_EDIT',
	INTEGRATION_DELETE = 'INTEGRATION_DELETE',
	/** Integration CRUD Permissions End */
	FILE_STORAGE_VIEW = 'FILE_STORAGE_VIEW',
	PAYMENT_GATEWAY_VIEW = 'PAYMENT_GATEWAY_VIEW',
	SMS_GATEWAY_VIEW = 'SMS_GATEWAY_VIEW',
	CUSTOM_SMTP_VIEW = 'CUSTOM_SMTP_VIEW',
	IMPORT_ADD = 'IMPORT_ADD',
	EXPORT_ADD = 'EXPORT_ADD',
	MIGRATE_GAUZY_CLOUD = 'MIGRATE_GAUZY_CLOUD',
	/** Jobs Permissions Start */
	ORG_JOB_SEARCH = 'ORG_JOB_SEARCH',
	ORG_JOB_APPLY = 'ORG_JOB_APPLY',
	ORG_JOB_EDIT = 'ORG_JOB_EDIT',
	ORG_JOB_EMPLOYEE_VIEW = 'ORG_JOB_EMPLOYEE_VIEW',
	ORG_JOB_MATCHING_VIEW = 'ORG_JOB_MATCHING_VIEW',
	/** Jobs Permissions End */
	INVENTORY_GALLERY_ADD = 'INVENTORY_GALLERY_ADD',
	INVENTORY_GALLERY_VIEW = 'INVENTORY_GALLERY_VIEW',
	INVENTORY_GALLERY_EDIT = 'INVENTORY_GALLERY_EDIT',
	INVENTORY_GALLERY_DELETE = 'INVENTORY_GALLERY_DELETE',
	MEDIA_GALLERY_ADD = 'MEDIA_GALLERY_ADD',
	MEDIA_GALLERY_VIEW = 'MEDIA_GALLERY_VIEW',
	MEDIA_GALLERY_EDIT = 'MEDIA_GALLERY_EDIT',
	MEDIA_GALLERY_DELETE = 'MEDIA_GALLERY_DELETE',
	ORG_EQUIPMENT_VIEW = 'ORG_EQUIPMENT_VIEW',
	ORG_EQUIPMENT_EDIT = 'ORG_EQUIPMENT_EDIT',
	ORG_EQUIPMENT_SHARING_VIEW = 'ORG_EQUIPMENT_SHARING_VIEW',
	ORG_EQUIPMENT_SHARING_EDIT = 'ORG_EQUIPMENT_SHARING_EDIT',
	EQUIPMENT_MAKE_REQUEST = 'EQUIPMENT_MAKE_REQUEST',
	EQUIPMENT_APPROVE_REQUEST = 'EQUIPMENT_APPROVE_REQUEST',
	/** Equipment Sharing Policy CRUD Permissions Start */
	EQUIPMENT_SHARING_POLICY_ADD = 'EQUIPMENT_SHARING_POLICY_ADD',
	EQUIPMENT_SHARING_POLICY_VIEW = 'EQUIPMENT_SHARING_POLICY_VIEW',
	EQUIPMENT_SHARING_POLICY_EDIT = 'EQUIPMENT_SHARING_POLICY_EDIT',
	EQUIPMENT_SHARING_POLICY_DELETE = 'EQUIPMENT_SHARING_POLICY_DELETE',
	/** Equipment Sharing Policy CRUD Permissions End */
	ORG_PRODUCT_TYPES_VIEW = 'ORG_PRODUCT_TYPES_VIEW',
	ORG_PRODUCT_TYPES_EDIT = 'ORG_PRODUCT_TYPES_EDIT',
	ORG_PRODUCT_CATEGORIES_VIEW = 'ORG_PRODUCT_CATEGORIES_VIEW',
	ORG_PRODUCT_CATEGORIES_EDIT = 'ORG_PRODUCT_CATEGORIES_EDIT',
	VIEW_ALL_ACCOUNTING_TEMPLATES = 'VIEW_ALL_ACCOUNTING_TEMPLATES',
	ACCESS_DELETE_ACCOUNT = 'ACCESS_DELETE_ACCOUNT',
	ACCESS_DELETE_ALL_DATA = 'ACCESS_DELETE_ALL_DATA',
	TENANT_SETTING = 'TENANT_SETTING', //allow user to access tenant setting
	GLOBAL_SETTING = 'GLOBAL_SETTING', //allow user to access global settings (tenantId = NULL)
	ALLOW_DELETE_TIME = 'ALLOW_DELETE_TIME',
	ALLOW_MODIFY_TIME = 'ALLOW_MODIFY_TIME',
	ALLOW_MANUAL_TIME = 'ALLOW_MANUAL_TIME',
	DELETE_SCREENSHOTS = 'DELETE_SCREENSHOTS',
	ORG_MEMBER_LAST_LOG_VIEW = 'ORG_MEMBER_LAST_LOG_VIEW',
	/** Daily Plan */
	DAILY_PLAN_CREATE = 'DAILY_PLAN_CREATE',
	DAILY_PLAN_READ = 'DAILY_PLAN_READ',
	DAILY_PLAN_UPDATE = 'DAILY_PLAN_UPDATE',
	DAILY_PLAN_DELETE = 'DAILY_PLAN_DELETE',
	/** Project Module */
	PROJECT_MODULE_CREATE = 'PROJECT_MODULE_CREATE',
	PROJECT_MODULE_READ = 'PROJECT_MODULE_READ',
	PROJECT_MODULE_UPDATE = 'PROJECT_MODULE_UPDATE',
	PROJECT_MODULE_DELETE = 'PROJECT_MODULE_DELETE',
	/** API Call Log */
	API_CALL_LOG_READ = 'API_CALL_LOG_READ',
	API_CALL_LOG_DELETE = 'API_CALL_LOG_DELETE',
	/** Dashboard */
	DASHBOARD_CREATE = 'DASHBOARD_CREATE',
	DASHBOARD_READ = 'DASHBOARD_READ',
	DASHBOARD_UPDATE = 'DASHBOARD_UPDATE',
	DASHBOARD_DELETE = 'DASHBOARD_DELETE',
	/** Tenant API Key */
	TENANT_API_KEY_CREATE = 'TENANT_API_KEY_CREATE',
	TENANT_API_KEY_VIEW = 'TENANT_API_KEY_VIEW',
	TENANT_API_KEY_DELETE = 'TENANT_API_KEY_DELETE',
	/** OAuth App Client Registry (multi-app OAuth provider) */
	OAUTH_CLIENT_VIEW = 'OAUTH_CLIENT_VIEW',
	OAUTH_CLIENT_EDIT = 'OAUTH_CLIENT_EDIT',
	/** Employee Availability CRUD Permissions Start */
	EMPLOYEE_AVAILABILITY_CREATE = 'EMPLOYEE_AVAILABILITY_CREATE',
	EMPLOYEE_AVAILABILITY_READ = 'EMPLOYEE_AVAILABILITY_READ',
	EMPLOYEE_AVAILABILITY_UPDATE = 'EMPLOYEE_AVAILABILITY_UPDATE',
	EMPLOYEE_AVAILABILITY_DELETE = 'EMPLOYEE_AVAILABILITY_DELETE',
	/** Broadcast Permissions Start */
	BROADCAST_CREATE = 'BROADCAST_CREATE',
	BROADCAST_READ = 'BROADCAST_READ',
	BROADCAST_UPDATE = 'BROADCAST_UPDATE',
	BROADCAST_DELETE = 'BROADCAST_DELETE',
	/** Broadcast Permissions End */
	/** Organization Strategic Initiative Permissions Start */
	ORG_STRATEGIC_INITIATIVE_CREATE = 'ORG_STRATEGIC_INITIATIVE_CREATE',
	ORG_STRATEGIC_INITIATIVE_READ = 'ORG_STRATEGIC_INITIATIVE_READ',
	ORG_STRATEGIC_INITIATIVE_UPDATE = 'ORG_STRATEGIC_INITIATIVE_UPDATE',
	ORG_STRATEGIC_INITIATIVE_DELETE = 'ORG_STRATEGIC_INITIATIVE_DELETE',
	/** Organization Strategic Initiative Permissions End */
	/** AI Chat Permissions Start */
	AI_CHAT_ACCESS = 'AI_CHAT_ACCESS',
	AI_CHAT_SETTINGS = 'AI_CHAT_SETTINGS',
	/** AI Chat Permissions End */
	/** Documents Permissions Start */
	DOCS_READ = 'DOCS_READ',
	DOCS_CREATE = 'DOCS_CREATE',
	DOCS_UPDATE = 'DOCS_UPDATE',
	DOCS_DELETE = 'DOCS_DELETE',
	DOCS_MANAGE = 'DOCS_MANAGE',
	DOCS_REVIEW = 'DOCS_REVIEW',
	DOCS_AI_IMPORT = 'DOCS_AI_IMPORT',
	/** Documents Permissions End */
	/**
	 * Plugin Permissions
	 */

	// Viewing & Discovery
	PLUGIN_VIEW = 'PLUGIN_VIEW',
	PLUGIN_DISCOVER = 'PLUGIN_DISCOVER',

	// Lifecycle Management
	PLUGIN_INSTALL = 'PLUGIN_INSTALL',
	PLUGIN_UNINSTALL = 'PLUGIN_UNINSTALL',
	PLUGIN_UPDATE = 'PLUGIN_UPDATE',
	PLUGIN_ENABLE = 'PLUGIN_ENABLE',
	PLUGIN_DISABLE = 'PLUGIN_DISABLE',

	// Configuration & Security
	PLUGIN_CONFIGURE = 'PLUGIN_CONFIGURE',
	PLUGIN_PUBLISH = 'PLUGIN_PUBLISH',
	PLUGIN_RESTRICT = 'PLUGIN_RESTRICT',
	PLUGIN_ASSIGN_ACCESS = 'PLUGIN_ASSIGN_ACCESS',
	PLUGIN_DELETE = 'PLUGIN_DELETE',
	PLUGIN_DELETE_FOREVER = 'PLUGIN_DELETE_FOREVER',

	// Commerce permissions.
	//
	// A plugin declares its own catalogue - the value, its label, the group it belongs to and what it
	// authorises - and that declaration is what provisions a role. The values themselves live here, in
	// the one enum the permission decorator is typed against, so what a route requires is checked by
	// the compiler rather than discovered when the route is first called.
	CARTS_VIEW = 'CARTS_VIEW',
	CARTS_EDIT = 'CARTS_EDIT',
	CARTS_DELETE = 'CARTS_DELETE',
	CARTS_CHECKOUT = 'CARTS_CHECKOUT',
	ORDERS_VIEW = 'ORDERS_VIEW',
	ORDERS_CREATE = 'ORDERS_CREATE',
	ORDERS_EDIT = 'ORDERS_EDIT',
	ORDERS_CANCEL = 'ORDERS_CANCEL',
	ORDERS_APPROVE = 'ORDERS_APPROVE',
	FULFILLMENTS_VIEW = 'FULFILLMENTS_VIEW',
	FULFILLMENTS_CREATE = 'FULFILLMENTS_CREATE',
	FULFILLMENTS_EDIT = 'FULFILLMENTS_EDIT',
	SHIPPING_OPTIONS_VIEW = 'SHIPPING_OPTIONS_VIEW',
	SHIPPING_OPTIONS_CREATE = 'SHIPPING_OPTIONS_CREATE',
	SHIPPING_OPTIONS_EDIT = 'SHIPPING_OPTIONS_EDIT',
	SHIPPING_OPTIONS_DELETE = 'SHIPPING_OPTIONS_DELETE',
	RETURNS_VIEW = 'RETURNS_VIEW',
	RETURNS_CREATE = 'RETURNS_CREATE',
	RETURNS_APPROVE = 'RETURNS_APPROVE',
	RETURNS_REJECT = 'RETURNS_REJECT',
	RETURNS_RECEIVE = 'RETURNS_RECEIVE',
	CLAIMS_VIEW = 'CLAIMS_VIEW',
	CLAIMS_CREATE = 'CLAIMS_CREATE',
	CLAIMS_RESOLVE = 'CLAIMS_RESOLVE',
	EXCHANGES_VIEW = 'EXCHANGES_VIEW',
	EXCHANGES_CREATE = 'EXCHANGES_CREATE',
	EXCHANGES_RESOLVE = 'EXCHANGES_RESOLVE',
	PRICE_LISTS_VIEW = 'PRICE_LISTS_VIEW',
	PRICE_LISTS_CREATE = 'PRICE_LISTS_CREATE',
	PRICE_LISTS_EDIT = 'PRICE_LISTS_EDIT',
	PRICE_LISTS_DELETE = 'PRICE_LISTS_DELETE',
	PRICE_LISTS_SIMULATE = 'PRICE_LISTS_SIMULATE',
	PRODUCT_PRICES_VIEW = 'PRODUCT_PRICES_VIEW',
	PRODUCT_PRICES_EDIT = 'PRODUCT_PRICES_EDIT',
	PRODUCT_PRICES_BULK_EDIT = 'PRODUCT_PRICES_BULK_EDIT',
	EXCHANGE_RATES_VIEW = 'EXCHANGE_RATES_VIEW',
	EXCHANGE_RATES_EDIT = 'EXCHANGE_RATES_EDIT',
	SELLERS_VIEW = 'SELLERS_VIEW',
	SELLERS_CREATE = 'SELLERS_CREATE',
	SELLERS_EDIT = 'SELLERS_EDIT',
	SELLERS_DELETE = 'SELLERS_DELETE',
	SELLER_OFFERINGS_VIEW = 'SELLER_OFFERINGS_VIEW',
	SELLER_OFFERINGS_EDIT = 'SELLER_OFFERINGS_EDIT',
	SELLER_COMMISSIONS_VIEW = 'SELLER_COMMISSIONS_VIEW',
	SELLER_COMMISSIONS_EDIT = 'SELLER_COMMISSIONS_EDIT',
	SELLER_TRANSACTIONS_VIEW = 'SELLER_TRANSACTIONS_VIEW',
	SELLER_TRANSACTIONS_SETTLE = 'SELLER_TRANSACTIONS_SETTLE',
	SELLER_SETTLEMENTS_VIEW = 'SELLER_SETTLEMENTS_VIEW',
	SELLER_SETTLEMENTS_EDIT = 'SELLER_SETTLEMENTS_EDIT',
	SELLER_PAYOUTS_VIEW = 'SELLER_PAYOUTS_VIEW',
	SELLER_PAYOUTS_CREATE = 'SELLER_PAYOUTS_CREATE',
	SELLER_PAYOUTS_APPROVE = 'SELLER_PAYOUTS_APPROVE',
	SELLER_PAYOUTS_CANCEL = 'SELLER_PAYOUTS_CANCEL',
	SEARCH_VIEW = 'SEARCH_VIEW',
	SEARCH_REINDEX = 'SEARCH_REINDEX',
	SEARCH_INDEX_DEFINITIONS_VIEW = 'SEARCH_INDEX_DEFINITIONS_VIEW',
	SEARCH_INDEX_DEFINITIONS_EDIT = 'SEARCH_INDEX_DEFINITIONS_EDIT',
	// Commerce permissions continued.
	//
	// The same reasoning as the block above, applied to the rest of the catalogue: a value a
	// route asks for has to be a member of this enum before the permission reload can grant it,
	// because `RolePermissionUtils` reads the catalogue from `Object.values(PermissionsEnum)`
	// and from nothing else. A value only a plugin catalogue declares is never inserted, so its
	// route answers 403 to every role, including the owner of the tenant.
	/** Platform: channels, regions, rules, numbering, operations, outbox, idempotency */
	CHANNELS_VIEW = 'CHANNELS_VIEW',
	CHANNELS_CREATE = 'CHANNELS_CREATE',
	CHANNELS_EDIT = 'CHANNELS_EDIT',
	CHANNELS_DELETE = 'CHANNELS_DELETE',
	REGIONS_VIEW = 'REGIONS_VIEW',
	REGIONS_CREATE = 'REGIONS_CREATE',
	REGIONS_EDIT = 'REGIONS_EDIT',
	REGIONS_DELETE = 'REGIONS_DELETE',
	RULES_VIEW = 'RULES_VIEW',
	RULES_EDIT = 'RULES_EDIT',
	SEQUENCES_VIEW = 'SEQUENCES_VIEW',
	SEQUENCES_EDIT = 'SEQUENCES_EDIT',
	OPERATIONS_VIEW = 'OPERATIONS_VIEW',
	OPERATIONS_CANCEL = 'OPERATIONS_CANCEL',
	EVENT_OUTBOX_VIEW = 'EVENT_OUTBOX_VIEW',
	EVENT_OUTBOX_RETRY = 'EVENT_OUTBOX_RETRY',
	IDEMPOTENCY_KEYS_VIEW = 'IDEMPOTENCY_KEYS_VIEW',
	IDEMPOTENCY_KEYS_DELETE = 'IDEMPOTENCY_KEYS_DELETE',
	PROVIDERS_VIEW = 'PROVIDERS_VIEW',
	UNITS_VIEW = 'UNITS_VIEW',
	UNITS_EDIT = 'UNITS_EDIT',
	PAYMENT_TERMS_VIEW = 'PAYMENT_TERMS_VIEW',
	PAYMENT_TERMS_EDIT = 'PAYMENT_TERMS_EDIT',
	/** Catalog */
	PRODUCTS_VIEW = 'PRODUCTS_VIEW',
	PRODUCTS_EDIT = 'PRODUCTS_EDIT',
	PRODUCTS_DELETE = 'PRODUCTS_DELETE',
	PRODUCTS_BULK_IMPORT = 'PRODUCTS_BULK_IMPORT',
	COLLECTIONS_VIEW = 'COLLECTIONS_VIEW',
	COLLECTIONS_CREATE = 'COLLECTIONS_CREATE',
	COLLECTIONS_EDIT = 'COLLECTIONS_EDIT',
	COLLECTIONS_DELETE = 'COLLECTIONS_DELETE',
	/** Tax */
	TAX_CATEGORIES_VIEW = 'TAX_CATEGORIES_VIEW',
	TAX_CATEGORIES_EDIT = 'TAX_CATEGORIES_EDIT',
	TAX_RATES_VIEW = 'TAX_RATES_VIEW',
	TAX_RATES_EDIT = 'TAX_RATES_EDIT',
	TAX_REGIMES_VIEW = 'TAX_REGIMES_VIEW',
	TAX_REGIMES_EDIT = 'TAX_REGIMES_EDIT',
	/** Contacts, groups, credentials and credit */
	CONTACT_GROUPS_VIEW = 'CONTACT_GROUPS_VIEW',
	CONTACT_GROUPS_CREATE = 'CONTACT_GROUPS_CREATE',
	CONTACT_GROUPS_EDIT = 'CONTACT_GROUPS_EDIT',
	CONTACT_GROUPS_DELETE = 'CONTACT_GROUPS_DELETE',
	CONTACT_CREDENTIALS_VIEW = 'CONTACT_CREDENTIALS_VIEW',
	CONTACT_CREDENTIALS_MANAGE = 'CONTACT_CREDENTIALS_MANAGE',
	CONTACT_CREDITS_EDIT = 'CONTACT_CREDITS_EDIT',
	CONTACT_TAX_IDENTITY_EDIT = 'CONTACT_TAX_IDENTITY_EDIT',
	/** Stock */
	STOCK_VIEW = 'STOCK_VIEW',
	STOCK_EDIT = 'STOCK_EDIT',
	STOCK_RECONCILE = 'STOCK_RECONCILE',
	STOCK_TRANSFER_VIEW = 'STOCK_TRANSFER_VIEW',
	STOCK_TRANSFER_CREATE = 'STOCK_TRANSFER_CREATE',
	STOCK_TRANSFER_APPROVE = 'STOCK_TRANSFER_APPROVE',
	STOCK_TRANSFER_SHIP = 'STOCK_TRANSFER_SHIP',
	STOCK_TRANSFER_RECEIVE = 'STOCK_TRANSFER_RECEIVE',
	STOCK_TRANSFER_CANCEL = 'STOCK_TRANSFER_CANCEL',
	/** Warehouse */
	WAREHOUSE_ZONES_VIEW = 'WAREHOUSE_ZONES_VIEW',
	WAREHOUSE_ZONES_CREATE = 'WAREHOUSE_ZONES_CREATE',
	WAREHOUSE_ZONES_EDIT = 'WAREHOUSE_ZONES_EDIT',
	WAREHOUSE_ZONES_DELETE = 'WAREHOUSE_ZONES_DELETE',
	WAREHOUSE_BINS_VIEW = 'WAREHOUSE_BINS_VIEW',
	WAREHOUSE_BINS_CREATE = 'WAREHOUSE_BINS_CREATE',
	WAREHOUSE_BINS_EDIT = 'WAREHOUSE_BINS_EDIT',
	WAREHOUSE_BINS_DELETE = 'WAREHOUSE_BINS_DELETE',
	PICK_LISTS_VIEW = 'PICK_LISTS_VIEW',
	PICK_LISTS_EDIT = 'PICK_LISTS_EDIT',
	PICK_LISTS_PICK = 'PICK_LISTS_PICK',
	PICK_LISTS_CANCEL = 'PICK_LISTS_CANCEL',
	/** Promotions, coupons and gift cards */
	PROMOTIONS_VIEW = 'PROMOTIONS_VIEW',
	PROMOTIONS_CREATE = 'PROMOTIONS_CREATE',
	PROMOTIONS_EDIT = 'PROMOTIONS_EDIT',
	PROMOTIONS_DELETE = 'PROMOTIONS_DELETE',
	PROMOTIONS_SIMULATE = 'PROMOTIONS_SIMULATE',
	COUPONS_VIEW = 'COUPONS_VIEW',
	COUPONS_CREATE = 'COUPONS_CREATE',
	COUPONS_EDIT = 'COUPONS_EDIT',
	COUPONS_DELETE = 'COUPONS_DELETE',
	GIFT_CARDS_VIEW = 'GIFT_CARDS_VIEW',
	GIFT_CARDS_ISSUE = 'GIFT_CARDS_ISSUE',
	GIFT_CARDS_EDIT = 'GIFT_CARDS_EDIT',
	/** Payments, refunds and provider callbacks */
	PAYMENT_PROVIDERS_VIEW = 'PAYMENT_PROVIDERS_VIEW',
	PAYMENT_PROVIDERS_CREATE = 'PAYMENT_PROVIDERS_CREATE',
	PAYMENT_PROVIDERS_EDIT = 'PAYMENT_PROVIDERS_EDIT',
	PAYMENT_PROVIDERS_DELETE = 'PAYMENT_PROVIDERS_DELETE',
	PAYMENT_SESSIONS_VIEW = 'PAYMENT_SESSIONS_VIEW',
	PAYMENT_SESSIONS_AUTHORIZE = 'PAYMENT_SESSIONS_AUTHORIZE',
	PAYMENT_SESSIONS_CAPTURE = 'PAYMENT_SESSIONS_CAPTURE',
	PAYMENT_SESSIONS_CANCEL = 'PAYMENT_SESSIONS_CANCEL',
	REFUNDS_VIEW = 'REFUNDS_VIEW',
	REFUNDS_CREATE = 'REFUNDS_CREATE',
	REFUNDS_APPROVE = 'REFUNDS_APPROVE',
	PAYMENT_CALLBACKS_VIEW = 'PAYMENT_CALLBACKS_VIEW',
	PAYMENT_CALLBACKS_REPROCESS = 'PAYMENT_CALLBACKS_REPROCESS',
	PAYMENT_ACCOUNT_HOLDERS_VIEW = 'PAYMENT_ACCOUNT_HOLDERS_VIEW',
	PAYMENT_ACCOUNT_HOLDERS_EDIT = 'PAYMENT_ACCOUNT_HOLDERS_EDIT',
	PAYMENT_METHOD_TOKENS_VIEW = 'PAYMENT_METHOD_TOKENS_VIEW',
	PAYMENT_METHOD_TOKENS_EDIT = 'PAYMENT_METHOD_TOKENS_EDIT',
	PAYMENT_METHOD_TOKENS_CHARGE = 'PAYMENT_METHOD_TOKENS_CHARGE',
	/** Subscriptions */
	SUBSCRIPTIONS_VIEW = 'SUBSCRIPTIONS_VIEW',
	SUBSCRIPTIONS_CREATE = 'SUBSCRIPTIONS_CREATE',
	SUBSCRIPTIONS_EDIT = 'SUBSCRIPTIONS_EDIT',
	SUBSCRIPTIONS_BILL = 'SUBSCRIPTIONS_BILL',
	/** Purchasing */
	PURCHASE_ORDERS_VIEW = 'PURCHASE_ORDERS_VIEW',
	PURCHASE_ORDERS_CREATE = 'PURCHASE_ORDERS_CREATE',
	PURCHASE_ORDERS_EDIT = 'PURCHASE_ORDERS_EDIT',
	PURCHASE_ORDERS_APPROVE = 'PURCHASE_ORDERS_APPROVE',
	PURCHASE_ORDERS_SEND = 'PURCHASE_ORDERS_SEND',
	GOODS_RECEIPTS_VIEW = 'GOODS_RECEIPTS_VIEW',
	GOODS_RECEIPTS_CREATE = 'GOODS_RECEIPTS_CREATE',
	VENDOR_TERMS_VIEW = 'VENDOR_TERMS_VIEW',
	VENDOR_TERMS_EDIT = 'VENDOR_TERMS_EDIT',
	/** Entitlements */
	ENTITLEMENTS_VIEW = 'ENTITLEMENTS_VIEW',
	ENTITLEMENTS_GRANT = 'ENTITLEMENTS_GRANT',
	ENTITLEMENTS_EDIT = 'ENTITLEMENTS_EDIT',
	/** Webhooks */
	WEBHOOKS_VIEW = 'WEBHOOKS_VIEW',
	WEBHOOKS_CREATE = 'WEBHOOKS_CREATE',
	WEBHOOKS_EDIT = 'WEBHOOKS_EDIT',
	WEBHOOKS_DELETE = 'WEBHOOKS_DELETE',
	WEBHOOK_DELIVERIES_RETRY = 'WEBHOOK_DELIVERIES_RETRY'
}

export const PermissionGroups = {
	//Permissions which can be given to any role
	GENERAL: [
		PermissionsEnum.ADMIN_DASHBOARD_VIEW,
		PermissionsEnum.TEAM_DASHBOARD,
		PermissionsEnum.PROJECT_MANAGEMENT_DASHBOARD,
		PermissionsEnum.TIME_TRACKING_DASHBOARD,
		PermissionsEnum.ACCOUNTING_DASHBOARD,
		PermissionsEnum.HUMAN_RESOURCE_DASHBOARD,
		PermissionsEnum.SELECT_EMPLOYEE,
		PermissionsEnum.CHANGE_SELECTED_EMPLOYEE,
		PermissionsEnum.CHANGE_SELECTED_CANDIDATE,
		PermissionsEnum.CHANGE_SELECTED_ORGANIZATION,
		/** Integration CRUD Permissions Start */
		PermissionsEnum.INTEGRATION_ADD,
		PermissionsEnum.INTEGRATION_VIEW,
		PermissionsEnum.INTEGRATION_EDIT,
		PermissionsEnum.INTEGRATION_DELETE,
		/** Integration CRUD Permissions End */
		/** AI Chat Permissions Start */
		PermissionsEnum.AI_CHAT_ACCESS,
		PermissionsEnum.AI_CHAT_SETTINGS,
		/** AI Chat Permissions End */
		/** Jobs Permissions Start */
		PermissionsEnum.ORG_JOB_APPLY,
		PermissionsEnum.ORG_JOB_SEARCH,
		PermissionsEnum.ORG_JOB_EDIT,
		PermissionsEnum.ORG_JOB_EMPLOYEE_VIEW,
		PermissionsEnum.ORG_JOB_MATCHING_VIEW,
		/** Jobs Permissions End */
		PermissionsEnum.PUBLIC_PAGE_EDIT,
		PermissionsEnum.ORG_PAYMENT_VIEW,
		PermissionsEnum.ORG_PAYMENT_ADD_EDIT,
		PermissionsEnum.ORG_PAYROLL_VIEW,
		PermissionsEnum.ORG_PAYROLL_EDIT,
		PermissionsEnum.ORG_PAYROLL_APPROVE,
		PermissionsEnum.ORG_EXPENSES_VIEW,
		PermissionsEnum.ORG_EXPENSES_EDIT,
		PermissionsEnum.EMPLOYEE_EXPENSES_VIEW,
		PermissionsEnum.EMPLOYEE_EXPENSES_EDIT,
		PermissionsEnum.ORG_INCOMES_EDIT,
		PermissionsEnum.ORG_INCOMES_VIEW,
		PermissionsEnum.ORG_PROPOSALS_EDIT,
		PermissionsEnum.ORG_PROPOSALS_VIEW,
		PermissionsEnum.ORG_PROPOSAL_TEMPLATES_VIEW,
		PermissionsEnum.ORG_PROPOSAL_TEMPLATES_EDIT,
		/** Employee CRUD Permissions Start */
		PermissionsEnum.ORG_EMPLOYEES_ADD,
		PermissionsEnum.ORG_EMPLOYEES_VIEW,
		PermissionsEnum.ORG_EMPLOYEES_DELETE,
		/** Employee CRUD Permissions End */
		/** Task CRUD Permissions Start */
		PermissionsEnum.ORG_TASK_ADD,
		PermissionsEnum.ORG_TASK_VIEW,
		PermissionsEnum.ORG_TASK_EDIT,
		PermissionsEnum.ORG_TASK_DELETE,
		/** Task CRUD Permissions End */
		PermissionsEnum.ORG_INVITE_VIEW,
		PermissionsEnum.ORG_INVITE_EDIT,
		/** Time Off Policy CRUD Permissions Start */
		PermissionsEnum.TIME_OFF_POLICY_ADD,
		PermissionsEnum.TIME_OFF_POLICY_VIEW,
		PermissionsEnum.TIME_OFF_POLICY_EDIT,
		PermissionsEnum.TIME_OFF_POLICY_DELETE,
		/** Time Off Policy CRUD Permissions End */
		/** Time Off Permissions Start */
		PermissionsEnum.TIME_OFF_ADD,
		PermissionsEnum.TIME_OFF_VIEW,
		PermissionsEnum.TIME_OFF_EDIT,
		PermissionsEnum.TIME_OFF_DELETE,
		/** Time Off Permissions End */
		PermissionsEnum.APPROVAL_POLICY_EDIT,
		PermissionsEnum.APPROVAL_POLICY_VIEW,
		PermissionsEnum.REQUEST_APPROVAL_EDIT,
		PermissionsEnum.REQUEST_APPROVAL_VIEW,
		PermissionsEnum.ACCESS_PRIVATE_PROJECTS,
		PermissionsEnum.TIMESHEET_EDIT_TIME,
		PermissionsEnum.INVOICES_VIEW,
		PermissionsEnum.INVOICES_EDIT,
		PermissionsEnum.ESTIMATES_VIEW,
		PermissionsEnum.ESTIMATES_EDIT,
		PermissionsEnum.ORG_CANDIDATES_DOCUMENTS_VIEW,
		PermissionsEnum.ORG_CANDIDATES_TASK_EDIT,
		PermissionsEnum.ORG_CANDIDATES_INTERVIEW_EDIT,
		PermissionsEnum.ORG_CANDIDATES_INTERVIEW_VIEW,
		PermissionsEnum.ORG_CANDIDATES_INTERVIEWERS_EDIT,
		PermissionsEnum.ORG_CANDIDATES_INTERVIEWERS_VIEW,
		PermissionsEnum.ORG_CANDIDATES_FEEDBACK_EDIT,
		PermissionsEnum.ORG_INVENTORY_VIEW,
		PermissionsEnum.ORG_INVENTORY_PRODUCT_EDIT,
		PermissionsEnum.ORG_TAGS_EDIT,
		PermissionsEnum.VIEW_ALL_EMAILS,
		PermissionsEnum.VIEW_ALL_EMAIL_TEMPLATES,
		PermissionsEnum.ORG_HELP_CENTER_EDIT,
		PermissionsEnum.VIEW_SALES_PIPELINES,
		PermissionsEnum.EDIT_SALES_PIPELINES,
		PermissionsEnum.CAN_APPROVE_TIMESHEET,
		PermissionsEnum.ORG_SPRINT_ADD,
		PermissionsEnum.ORG_SPRINT_EDIT,
		PermissionsEnum.ORG_SPRINT_VIEW,
		PermissionsEnum.ORG_SPRINT_DELETE,
		PermissionsEnum.ORG_PROJECT_ADD,
		PermissionsEnum.ORG_PROJECT_VIEW,
		PermissionsEnum.ORG_PROJECT_EDIT,
		PermissionsEnum.ORG_PROJECT_DELETE,
		PermissionsEnum.ORG_CONTACT_EDIT,
		PermissionsEnum.ORG_CONTACT_VIEW,
		/** Daily Plan Permissions Start */
		PermissionsEnum.DAILY_PLAN_CREATE,
		PermissionsEnum.DAILY_PLAN_READ,
		PermissionsEnum.DAILY_PLAN_UPDATE,
		PermissionsEnum.DAILY_PLAN_DELETE,
		/** Daily Plan Permissions End */
		/** Project Module Permissions start */
		PermissionsEnum.PROJECT_MODULE_CREATE,
		PermissionsEnum.PROJECT_MODULE_READ,
		PermissionsEnum.PROJECT_MODULE_UPDATE,
		PermissionsEnum.PROJECT_MODULE_DELETE,
		/** Project Module Permissions end */
		/** Dashboard Permissions Start */
		PermissionsEnum.DASHBOARD_CREATE,
		PermissionsEnum.DASHBOARD_READ,
		PermissionsEnum.DASHBOARD_UPDATE,
		PermissionsEnum.DASHBOARD_DELETE,
		/** Dashboard Permissions End */
		/** Organization Team Permissions Start */
		PermissionsEnum.ORG_TEAM_ADD,
		PermissionsEnum.ORG_TEAM_VIEW,
		PermissionsEnum.ORG_TEAM_EDIT,
		PermissionsEnum.ORG_TEAM_DELETE,
		PermissionsEnum.ORG_TEAM_EDIT_ACTIVE_TASK,
		PermissionsEnum.ORG_TEAM_REMOVE_ACCOUNT_AS_MEMBER,
		PermissionsEnum.ORG_TEAM_JOIN_REQUEST_VIEW,
		PermissionsEnum.ORG_TEAM_JOIN_REQUEST_EDIT,
		/** Organization Team Permissions End */
		PermissionsEnum.ORG_TASK_SETTING,
		PermissionsEnum.ORG_CONTRACT_EDIT,
		PermissionsEnum.EVENT_TYPES_VIEW,
		PermissionsEnum.TIME_TRACKER,
		PermissionsEnum.INVENTORY_GALLERY_VIEW,
		PermissionsEnum.INVENTORY_GALLERY_EDIT,
		PermissionsEnum.MEDIA_GALLERY_ADD,
		PermissionsEnum.MEDIA_GALLERY_VIEW,
		PermissionsEnum.MEDIA_GALLERY_EDIT,
		PermissionsEnum.MEDIA_GALLERY_DELETE,
		PermissionsEnum.ORG_EQUIPMENT_VIEW,
		PermissionsEnum.ORG_EQUIPMENT_EDIT,
		PermissionsEnum.ORG_EQUIPMENT_SHARING_VIEW,
		PermissionsEnum.ORG_EQUIPMENT_SHARING_EDIT,
		PermissionsEnum.EQUIPMENT_MAKE_REQUEST,
		PermissionsEnum.EQUIPMENT_APPROVE_REQUEST,
		/**Equipment Sharing Policy Permissions Start */
		PermissionsEnum.EQUIPMENT_SHARING_POLICY_ADD,
		PermissionsEnum.EQUIPMENT_SHARING_POLICY_VIEW,
		PermissionsEnum.EQUIPMENT_SHARING_POLICY_EDIT,
		PermissionsEnum.EQUIPMENT_SHARING_POLICY_DELETE,
		/** Equipment Sharing Policy Permissions End */
		/**Tag Permissions Start */
		PermissionsEnum.ORG_TAGS_ADD,
		PermissionsEnum.ORG_TAGS_VIEW,
		PermissionsEnum.ORG_TAGS_EDIT,
		PermissionsEnum.ORG_TAGS_DELETE,
		/** Tag Permissions End */
		/** Tag Type Permissions Start */
		PermissionsEnum.ORG_TAG_TYPES_ADD,
		PermissionsEnum.ORG_TAG_TYPES_VIEW,
		PermissionsEnum.ORG_TAG_TYPES_EDIT,
		PermissionsEnum.ORG_TAG_TYPES_DELETE,
		/** Tag Type Permissions End */
		PermissionsEnum.ORG_PRODUCT_TYPES_VIEW,
		PermissionsEnum.ORG_PRODUCT_CATEGORIES_VIEW,
		PermissionsEnum.ORG_PRODUCT_CATEGORIES_EDIT,
		PermissionsEnum.VIEW_ALL_ACCOUNTING_TEMPLATES,
		PermissionsEnum.ALLOW_DELETE_TIME,
		PermissionsEnum.ALLOW_MODIFY_TIME,
		PermissionsEnum.ALLOW_MANUAL_TIME,
		PermissionsEnum.DELETE_SCREENSHOTS,
		PermissionsEnum.ACCESS_DELETE_ACCOUNT,
		PermissionsEnum.ORG_MEMBER_LAST_LOG_VIEW,
		/** Employee Availability CRUD Permissions Start */
		PermissionsEnum.EMPLOYEE_AVAILABILITY_CREATE,
		PermissionsEnum.EMPLOYEE_AVAILABILITY_READ,
		PermissionsEnum.EMPLOYEE_AVAILABILITY_UPDATE,
		PermissionsEnum.EMPLOYEE_AVAILABILITY_DELETE,
		/** Broadcast Permissions Start */
		PermissionsEnum.BROADCAST_CREATE,
		PermissionsEnum.BROADCAST_READ,
		PermissionsEnum.BROADCAST_UPDATE,
		PermissionsEnum.BROADCAST_DELETE,
		/** Broadcast Permissions End */
		/** Organization Strategic Initiative Permissions Start */
		PermissionsEnum.ORG_STRATEGIC_INITIATIVE_READ,
		/** Organization Strategic Initiative Permissions End */
		/** Documents Permissions Start */
		PermissionsEnum.DOCS_READ,
		PermissionsEnum.DOCS_CREATE,
		PermissionsEnum.DOCS_UPDATE
		/** Documents Permissions End */,
		/** Commerce Permissions Start */
		/** Platform: channels, regions, rules, numbering, operations, outbox, idempotency */
		PermissionsEnum.CHANNELS_VIEW,
		PermissionsEnum.REGIONS_VIEW,
		PermissionsEnum.RULES_VIEW,
		PermissionsEnum.SEQUENCES_VIEW,
		PermissionsEnum.OPERATIONS_VIEW,
		PermissionsEnum.EVENT_OUTBOX_VIEW,
		PermissionsEnum.IDEMPOTENCY_KEYS_VIEW,
		PermissionsEnum.PROVIDERS_VIEW,
		PermissionsEnum.UNITS_VIEW,
		PermissionsEnum.PAYMENT_TERMS_VIEW,
		/** Catalog */
		PermissionsEnum.PRODUCTS_VIEW,
		PermissionsEnum.PRODUCTS_EDIT,
		PermissionsEnum.PRODUCTS_DELETE,
		PermissionsEnum.COLLECTIONS_VIEW,
		PermissionsEnum.COLLECTIONS_CREATE,
		PermissionsEnum.COLLECTIONS_EDIT,
		PermissionsEnum.COLLECTIONS_DELETE,
		/** Pricing and currency */
		PermissionsEnum.PRICE_LISTS_VIEW,
		PermissionsEnum.PRICE_LISTS_CREATE,
		PermissionsEnum.PRICE_LISTS_EDIT,
		PermissionsEnum.PRICE_LISTS_DELETE,
		PermissionsEnum.PRICE_LISTS_SIMULATE,
		PermissionsEnum.PRODUCT_PRICES_VIEW,
		PermissionsEnum.PRODUCT_PRICES_EDIT,
		PermissionsEnum.EXCHANGE_RATES_VIEW,
		/** Tax */
		PermissionsEnum.TAX_CATEGORIES_VIEW,
		PermissionsEnum.TAX_CATEGORIES_EDIT,
		PermissionsEnum.TAX_RATES_VIEW,
		PermissionsEnum.TAX_RATES_EDIT,
		PermissionsEnum.TAX_REGIMES_VIEW,
		/** Contacts, groups, credentials and credit */
		PermissionsEnum.CONTACT_GROUPS_VIEW,
		PermissionsEnum.CONTACT_GROUPS_CREATE,
		PermissionsEnum.CONTACT_GROUPS_EDIT,
		PermissionsEnum.CONTACT_GROUPS_DELETE,
		PermissionsEnum.CONTACT_CREDENTIALS_VIEW,
		/** Stock */
		PermissionsEnum.STOCK_VIEW,
		PermissionsEnum.STOCK_EDIT,
		PermissionsEnum.STOCK_TRANSFER_VIEW,
		PermissionsEnum.STOCK_TRANSFER_CREATE,
		PermissionsEnum.STOCK_TRANSFER_APPROVE,
		PermissionsEnum.STOCK_TRANSFER_SHIP,
		PermissionsEnum.STOCK_TRANSFER_RECEIVE,
		PermissionsEnum.STOCK_TRANSFER_CANCEL,
		/** Warehouse */
		PermissionsEnum.WAREHOUSE_ZONES_VIEW,
		PermissionsEnum.WAREHOUSE_ZONES_CREATE,
		PermissionsEnum.WAREHOUSE_ZONES_EDIT,
		PermissionsEnum.WAREHOUSE_ZONES_DELETE,
		PermissionsEnum.WAREHOUSE_BINS_VIEW,
		PermissionsEnum.WAREHOUSE_BINS_CREATE,
		PermissionsEnum.WAREHOUSE_BINS_EDIT,
		PermissionsEnum.WAREHOUSE_BINS_DELETE,
		PermissionsEnum.PICK_LISTS_VIEW,
		PermissionsEnum.PICK_LISTS_EDIT,
		PermissionsEnum.PICK_LISTS_PICK,
		PermissionsEnum.PICK_LISTS_CANCEL,
		/** Fulfilment and shipping */
		PermissionsEnum.FULFILLMENTS_VIEW,
		PermissionsEnum.FULFILLMENTS_CREATE,
		PermissionsEnum.FULFILLMENTS_EDIT,
		PermissionsEnum.SHIPPING_OPTIONS_VIEW,
		PermissionsEnum.SHIPPING_OPTIONS_CREATE,
		PermissionsEnum.SHIPPING_OPTIONS_EDIT,
		PermissionsEnum.SHIPPING_OPTIONS_DELETE,
		/** Returns, claims and exchanges */
		PermissionsEnum.RETURNS_VIEW,
		PermissionsEnum.RETURNS_CREATE,
		PermissionsEnum.RETURNS_APPROVE,
		PermissionsEnum.RETURNS_REJECT,
		PermissionsEnum.RETURNS_RECEIVE,
		PermissionsEnum.CLAIMS_VIEW,
		PermissionsEnum.CLAIMS_CREATE,
		PermissionsEnum.CLAIMS_RESOLVE,
		PermissionsEnum.EXCHANGES_VIEW,
		PermissionsEnum.EXCHANGES_CREATE,
		PermissionsEnum.EXCHANGES_RESOLVE,
		/** Orders */
		PermissionsEnum.ORDERS_VIEW,
		PermissionsEnum.ORDERS_CREATE,
		PermissionsEnum.ORDERS_EDIT,
		PermissionsEnum.ORDERS_CANCEL,
		PermissionsEnum.ORDERS_APPROVE,
		/** Carts and checkout */
		PermissionsEnum.CARTS_VIEW,
		PermissionsEnum.CARTS_EDIT,
		PermissionsEnum.CARTS_DELETE,
		PermissionsEnum.CARTS_CHECKOUT,
		/** Promotions, coupons and gift cards */
		PermissionsEnum.PROMOTIONS_VIEW,
		PermissionsEnum.PROMOTIONS_CREATE,
		PermissionsEnum.PROMOTIONS_EDIT,
		PermissionsEnum.PROMOTIONS_DELETE,
		PermissionsEnum.PROMOTIONS_SIMULATE,
		PermissionsEnum.COUPONS_VIEW,
		PermissionsEnum.COUPONS_CREATE,
		PermissionsEnum.COUPONS_EDIT,
		PermissionsEnum.COUPONS_DELETE,
		PermissionsEnum.GIFT_CARDS_VIEW,
		PermissionsEnum.GIFT_CARDS_ISSUE,
		PermissionsEnum.GIFT_CARDS_EDIT,
		/** Payments, refunds and provider callbacks */
		PermissionsEnum.PAYMENT_PROVIDERS_VIEW,
		PermissionsEnum.PAYMENT_SESSIONS_VIEW,
		PermissionsEnum.PAYMENT_SESSIONS_AUTHORIZE,
		PermissionsEnum.PAYMENT_SESSIONS_CANCEL,
		PermissionsEnum.REFUNDS_VIEW,
		PermissionsEnum.REFUNDS_CREATE,
		PermissionsEnum.PAYMENT_CALLBACKS_VIEW,
		PermissionsEnum.PAYMENT_CALLBACKS_REPROCESS,
		PermissionsEnum.PAYMENT_ACCOUNT_HOLDERS_VIEW,
		PermissionsEnum.PAYMENT_METHOD_TOKENS_VIEW,
		PermissionsEnum.PAYMENT_METHOD_TOKENS_EDIT,
		/** Subscriptions */
		PermissionsEnum.SUBSCRIPTIONS_VIEW,
		PermissionsEnum.SUBSCRIPTIONS_CREATE,
		PermissionsEnum.SUBSCRIPTIONS_EDIT,
		PermissionsEnum.SUBSCRIPTIONS_BILL,
		/** Purchasing */
		PermissionsEnum.PURCHASE_ORDERS_VIEW,
		PermissionsEnum.PURCHASE_ORDERS_CREATE,
		PermissionsEnum.PURCHASE_ORDERS_EDIT,
		PermissionsEnum.PURCHASE_ORDERS_APPROVE,
		PermissionsEnum.PURCHASE_ORDERS_SEND,
		PermissionsEnum.GOODS_RECEIPTS_VIEW,
		PermissionsEnum.GOODS_RECEIPTS_CREATE,
		PermissionsEnum.VENDOR_TERMS_VIEW,
		PermissionsEnum.VENDOR_TERMS_EDIT,
		/** Entitlements */
		PermissionsEnum.ENTITLEMENTS_VIEW,
		PermissionsEnum.ENTITLEMENTS_GRANT,
		PermissionsEnum.ENTITLEMENTS_EDIT,
		/** Marketplace */
		PermissionsEnum.SELLERS_VIEW,
		PermissionsEnum.SELLERS_CREATE,
		PermissionsEnum.SELLERS_EDIT,
		PermissionsEnum.SELLERS_DELETE,
		PermissionsEnum.SELLER_PAYOUTS_VIEW,
		PermissionsEnum.SELLER_PAYOUTS_CREATE,
		PermissionsEnum.SELLER_PAYOUTS_CANCEL,
		/** Search */
		PermissionsEnum.SEARCH_VIEW,
		/** Webhooks */
		PermissionsEnum.WEBHOOKS_VIEW,
		PermissionsEnum.WEBHOOKS_CREATE,
		PermissionsEnum.WEBHOOKS_EDIT,
		PermissionsEnum.WEBHOOK_DELIVERIES_RETRY,
		/** Sub-capabilities the plugin catalogues declare on top of the pairs above */
		PermissionsEnum.SELLER_OFFERINGS_VIEW,
		PermissionsEnum.SELLER_OFFERINGS_EDIT,
		PermissionsEnum.SELLER_COMMISSIONS_VIEW,
		PermissionsEnum.SELLER_COMMISSIONS_EDIT,
		PermissionsEnum.SELLER_TRANSACTIONS_VIEW,
		PermissionsEnum.SELLER_TRANSACTIONS_SETTLE,
		PermissionsEnum.SELLER_SETTLEMENTS_VIEW,
		PermissionsEnum.SELLER_SETTLEMENTS_EDIT,
		PermissionsEnum.SEARCH_INDEX_DEFINITIONS_VIEW,
		PermissionsEnum.SEARCH_INDEX_DEFINITIONS_EDIT
		/** Commerce Permissions End */
	],

	//Readonly permissions, are only enabled for Super Admin/Admin role
	ADMINISTRATION: [
		PermissionsEnum.ORG_EMPLOYEES_EDIT,
		PermissionsEnum.ORG_CANDIDATES_VIEW,
		PermissionsEnum.ORG_CANDIDATES_EDIT,
		PermissionsEnum.ORG_USERS_VIEW,
		PermissionsEnum.ORG_USERS_EDIT,
		PermissionsEnum.ALL_ORG_VIEW,
		PermissionsEnum.ALL_ORG_EDIT,
		PermissionsEnum.CHANGE_ROLES_PERMISSIONS,
		PermissionsEnum.TENANT_ADD_EXISTING_USER,
		PermissionsEnum.FILE_STORAGE_VIEW,
		PermissionsEnum.PAYMENT_GATEWAY_VIEW,
		PermissionsEnum.SMS_GATEWAY_VIEW,
		PermissionsEnum.CUSTOM_SMTP_VIEW,
		PermissionsEnum.IMPORT_ADD,
		PermissionsEnum.EXPORT_ADD,
		PermissionsEnum.ACCESS_DELETE_ALL_DATA,
		PermissionsEnum.TENANT_SETTING,
		PermissionsEnum.API_CALL_LOG_READ,
		PermissionsEnum.API_CALL_LOG_DELETE,
		/** Tenant API Key */
		PermissionsEnum.TENANT_API_KEY_CREATE,
		PermissionsEnum.TENANT_API_KEY_VIEW,
		PermissionsEnum.TENANT_API_KEY_DELETE,
		/** OAuth App Client Registry */
		PermissionsEnum.OAUTH_CLIENT_VIEW,
		PermissionsEnum.OAUTH_CLIENT_EDIT,
		/** Documents Permissions Start */
		PermissionsEnum.DOCS_DELETE,
		PermissionsEnum.DOCS_MANAGE,
		PermissionsEnum.DOCS_REVIEW,
		PermissionsEnum.DOCS_AI_IMPORT
		/** Documents Permissions End */,
		/** Commerce Permissions Start */
		/** Platform: channels, regions, rules, numbering, operations, outbox, idempotency */
		PermissionsEnum.CHANNELS_CREATE,
		PermissionsEnum.CHANNELS_EDIT,
		PermissionsEnum.CHANNELS_DELETE,
		PermissionsEnum.REGIONS_CREATE,
		PermissionsEnum.REGIONS_EDIT,
		PermissionsEnum.REGIONS_DELETE,
		PermissionsEnum.RULES_EDIT,
		PermissionsEnum.SEQUENCES_EDIT,
		PermissionsEnum.OPERATIONS_CANCEL,
		PermissionsEnum.EVENT_OUTBOX_RETRY,
		PermissionsEnum.IDEMPOTENCY_KEYS_DELETE,
		PermissionsEnum.UNITS_EDIT,
		PermissionsEnum.PAYMENT_TERMS_EDIT,
		/** Catalog */
		PermissionsEnum.PRODUCTS_BULK_IMPORT,
		/** Pricing and currency */
		PermissionsEnum.PRODUCT_PRICES_BULK_EDIT,
		PermissionsEnum.EXCHANGE_RATES_EDIT,
		/** Tax */
		PermissionsEnum.TAX_REGIMES_EDIT,
		/** Contacts, groups, credentials and credit */
		PermissionsEnum.CONTACT_CREDENTIALS_MANAGE,
		PermissionsEnum.CONTACT_CREDITS_EDIT,
		PermissionsEnum.CONTACT_TAX_IDENTITY_EDIT,
		/** Stock */
		PermissionsEnum.STOCK_RECONCILE,
		/** Payments, refunds and provider callbacks */
		PermissionsEnum.PAYMENT_PROVIDERS_CREATE,
		PermissionsEnum.PAYMENT_PROVIDERS_EDIT,
		PermissionsEnum.PAYMENT_PROVIDERS_DELETE,
		PermissionsEnum.PAYMENT_SESSIONS_CAPTURE,
		PermissionsEnum.REFUNDS_APPROVE,
		PermissionsEnum.PAYMENT_ACCOUNT_HOLDERS_EDIT,
		PermissionsEnum.PAYMENT_METHOD_TOKENS_CHARGE,
		/** Marketplace */
		PermissionsEnum.SELLER_PAYOUTS_APPROVE,
		/** Search */
		PermissionsEnum.SEARCH_REINDEX,
		/** Webhooks */
		PermissionsEnum.WEBHOOKS_DELETE
		/** Commerce Permissions End */
	]
};
