/**
 * `@gauzy/ui-core/i18n` is a barrel over the whole app i18n module; the cards view only needs
 * `TranslationBaseComponent` to exist so the class can be constructed directly (no `TestBed`,
 * no Angular module graph) — same reason as `components/filter-bar/content-search-min.spec.ts`.
 */
/**
 * `@gauzy/ui-core/core` is a barrel over the whole app core. `DocsCardsComponent` reaches it
 * through `DocsRowActionsService`, and loading it for real drags unrelated services (and their
 * untranspiled ESM dependencies) into the CommonJS test runtime — which fails the suite at LOAD
 * time, so it reads as "no tests here" rather than "coverage is zero". Same stub-the-injected-
 * shapes approach as `components/actions/docs-row-actions.spec.ts`.
 */
jest.mock('@gauzy/ui-core/core', () => ({
	Store: class Store {},
	ToastrService: class ToastrService {},
	FavoriteStoreService: class FavoriteStoreService {},
	GenericFavoriteService: class GenericFavoriteService {}
}));

jest.mock('@gauzy/ui-core/i18n', () => ({
	TranslationBaseComponent: class {
		constructor(public readonly translateService: unknown) {}
		getTranslation(key: string): string {
			return key;
		}
	}
}));

import { readFileSync } from 'fs';
import { join } from 'path';
import { DocumentKindEnum, ID, IDocument } from '@gauzy/contracts';
import { DocsCardsComponent } from './docs-cards.component';

/**
 * Thumbnails on document cards (`thumbKey`/`thumbUrl`, generated by the P1 thumbnail job).
 *
 * Two properties, both easy to lose:
 *
 *  1. **The icon fallback is the normal case, not the error case.** `thumbUrl` is a virtual
 *     column the backend resolves from `storageProvider` + `thumbKey`, so it is absent on
 *     every folder, every page, and every file the job has not processed yet — and it can
 *     also *stop* resolving (an expired signed URL, a deleted object), which the browser only
 *     reports as an `error` event on the `<img>`.
 *  2. **The tile is reserved whether or not there is an image.** A thumbnail appears on a
 *     later processing poll, not on first render; a tile that materialised with the image
 *     would reflow the whole grid under the user's cursor.
 *
 * The URL is also attacker-influenced in principle (it is stored data rendered into
 * `<img [src]>`), so it goes through the app's scheme allowlist rather than Angular's
 * one-scheme denylist — `editor/read-only/safe-url.util.ts` carries the full argument.
 */

const CARDS_DIR = __dirname;

function documentRow(overrides: Partial<IDocument> = {}): IDocument {
	return {
		id: 'cccccccc-1111-4111-8111-111111111111' as ID,
		name: 'Quarterly report.pdf',
		kind: DocumentKindEnum.FILE,
		mimeType: 'application/pdf',
		...overrides
	} as IDocument;
}

describe('document card thumbnails', () => {
	const cards = () => new DocsCardsComponent({} as never);

	describe('the fallback to the kind icon', () => {
		it('renders no image when the document has no thumbnail yet', () => {
			const component = cards();

			expect(component.thumbnailUrl(documentRow())).toBeNull();
			// …and the tile still has something to show.
			expect(component.kindIcon(documentRow())).toBe('file-text-outline');
		});

		it('renders the thumbnail once the job has produced one', () => {
			const component = cards();
			const row = documentRow({ thumbUrl: 'https://cdn.example.com/thumbs/abc.png' } as Partial<IDocument>);

			expect(component.thumbnailUrl(row)).toBe('https://cdn.example.com/thumbs/abc.png');
		});

		it('falls back for the rest of the session once the image fails to load', () => {
			const component = cards();
			const row = documentRow({ thumbUrl: 'https://cdn.example.com/thumbs/expired.png' } as Partial<IDocument>);

			expect(component.thumbnailUrl(row)).not.toBeNull();

			component.onThumbnailError(row);

			expect(component.thumbnailUrl(row)).toBeNull();
			expect(component.kindIcon(row)).toBe('file-text-outline');
		});

		it('fails only the card that failed, never the whole grid', () => {
			const component = cards();
			const broken = documentRow({ thumbUrl: 'https://cdn.example.com/a.png' } as Partial<IDocument>);
			const healthy = documentRow({
				id: 'cccccccc-2222-4222-8222-222222222222' as ID,
				thumbUrl: 'https://cdn.example.com/b.png'
			} as Partial<IDocument>);

			component.onThumbnailError(broken);

			expect(component.thumbnailUrl(broken)).toBeNull();
			expect(component.thumbnailUrl(healthy)).toBe('https://cdn.example.com/b.png');
		});

		it.each([
			['javascript:alert(1)'],
			['data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg=='],
			['data:image/svg+xml,%3Csvg%20onload%3Dalert(1)%3E'],
			['vbscript:msgbox(1)']
		])('refuses %s and falls back to the icon rather than binding it', (thumbUrl) => {
			const component = cards();

			expect(component.thumbnailUrl(documentRow({ thumbUrl } as Partial<IDocument>))).toBeNull();
		});

		it('keeps the per-kind icons the fallback relies on', () => {
			const component = cards();

			expect(component.kindIcon(documentRow({ kind: DocumentKindEnum.PAGE }))).toBe('file-text-outline');
			expect(component.kindIcon(documentRow({ kind: DocumentKindEnum.FOLDER }))).toBe('folder-outline');
			expect(component.kindIcon(documentRow({ mimeType: 'image/png' }))).toBe('image-outline');
			expect(component.kindIcon(documentRow({ mimeType: undefined }))).toBe('file-outline');
		});
	});

	describe('layout stability', () => {
		const template = readFileSync(join(CARDS_DIR, 'docs-cards.component.html'), 'utf8');
		const styles = readFileSync(join(CARDS_DIR, 'docs-cards.component.scss'), 'utf8');

		it('renders the tile unconditionally — it is not created by the thumbnail arriving', () => {
			const tile = /<div\s+class="docs-card-thumb"[^>]*>/.exec(template);

			expect(tile).not.toBeNull();
			expect(tile?.[0]).not.toContain('*ngIf');
		});

		it('gives the tile a fixed height, so a late-loading image cannot resize the card', () => {
			const rule = /\.docs-card-thumb\s*\{([^}]*)\}/.exec(styles);

			expect(rule?.[1]).toMatch(/height:\s*[\d.]+rem/);
		});

		it('binds the image through the sanitizing accessor, never `thumbUrl` directly', () => {
			expect(template).toContain('thumbnailUrl(doc) as thumbnail');
			expect(template).not.toContain('[src]="doc.thumbUrl"');
		});

		it('degrades on the image `error` event instead of leaving a broken image', () => {
			expect(template).toContain('(error)="onThumbnailError(doc)"');
		});
	});
});
