name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - test-do-droplet

jobs:
  deploy:
    runs-on: buildjet-4vcpu-ubuntu-2204

    environment: demo

    steps:
      - name: checkout out test-do-droplet branch
        uses: actions/checkout@v4
        with:
          ref: test-do-droplet
      - name: Inject secrets into .env-template.compose
        # run: |
        #   envsubst < $GITHUB_WORKSPACE/.deploy/ssh/.env.template.compose > $GITHUB_WORKSPACE/.env.compose
        uses: danielr1996/envsubst-action@1.0.0
        env:
          CLOUD_PROVIDER: 'DO'
          DB_NAME: '${{ secrets.DB_NAME }}'
          SENTRY_DSN: '${{ secrets.SENTRY_DSN }}'
          SENTRY_TRACES_SAMPLE_RATE: '${{ secrets.SENTRY_TRACES_SAMPLE_RATE }}'
          SENTRY_PROFILE_SAMPLE_RATE: '${{ secrets.SENTRY_PROFILE_SAMPLE_RATE }}'
          SENTRY_HTTP_TRACING_ENABLED: '${{ secrets.SENTRY_HTTP_TRACING_ENABLED }}'
          SENTRY_POSTGRES_TRACKING_ENABLED: '${{ secrets.SENTRY_POSTGRES_TRACKING_ENABLED }}'
          SENTRY_PROFILING_ENABLED: '${{ secrets.SENTRY_PROFILING_ENABLED }}'
          OTEL_ENABLED: '${{ secrets.OTEL_ENABLED }}'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
        with:
          input: .deploy/ssh/.env.template.compose
          output: .env.compose

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.DO_DROPLET_HOST}}
          username: ${{secrets.DO_DROPLET_USERNAME}}
          key: ${{secrets.DO_DROPLET_KEY}}
          source: "docker-compose.api.yml,.env.compose"
          target: "."
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DO_DROPLET_HOST}}
          username: ${{secrets.DO_DROPLET_USERNAME}}
          key: ${{secrets.DO_DROPLET_KEY}}
          script: |        
            echo 'Deployment to digital ocean finished'
