name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - test-do-droplet

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Inject secrets into .env.template.compose
        run: |
          # Create a copy of .env.template.compose
          cp .deploy/ssh/.env.template.compose .env.compose

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DO_DROPLET_HOST}}
          username: ${{secrets.DO_DROPLET_USERNAME}}
          key: ${{secrets.DO_DROPLET_KEY}}
          script: |
            cp  .env.compose 
            cp  docker-compose.api.yaml
            echo 'Deployment to digital ocean finished'
            