name: Deploy to DigitalOcean Droplet Stage

on:
  push:
    branches:
      - test-do-droplet2

jobs:
  deploy:
    runs-on: buildjet-4vcpu-ubuntu-2204

    environment: stage

    steps:
      - name: checkout out code
        uses: actions/checkout@v4

      - name: Globalise Ingress certificate type env
        run: |
          echo "INGRESS_CERT_TYPE=${{ env.INGRESS_CERT_TYPE }}" >> $GITHUB_ENV
        env:
          INGRESS_CERT_TYPE: 'cloudflare'

      - name: Generate TLS Secrets for DO Droplet
        run: |
          rm -f $GITHUB_WORKSPACE/.deploy/ssh/ingress.api.crt $GITHUB_WORKSPACE/.deploy/ssh/ingress.api.key
          echo ${{ secrets.INGRESS_API_CERT }} | base64 --decode > $GITHUB_WORKSPACE/.deploy/ssh/ingress.api.crt
          echo ${{ secrets.INGRESS_API_CERT_KEY }} | base64 --decode > $GITHUB_WORKSPACE/.deploy/ssh/ingress.api.key

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.DO_DROPLET_STAGE_HOST}}
          username: ${{secrets.DO_DROPLET_USERNAME}}
          key: ${{secrets.DO_DROPLET_KEY}}
          source: '.deploy/ssh/docker-compose.api.stage.pre.yml,.deploy/ssh/docker-compose.api.stage.letsencrypt.pre.yml,.deploy/ssh/nginx.stage.pre.conf,.deploy/ssh/nginx.stage.pre.letsencrypt.conf,.deploy/ssh/ingress.api.crt,.deploy/ssh/ingress.api.key'
          target: '.'
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DO_DROPLET_STAGE_HOST}}
          username: ${{secrets.DO_DROPLET_USERNAME}}
          key: ${{secrets.DO_DROPLET_KEY}}
          script: |
            if [ "${{ env.INGRESS_CERT_TYPE }}" = "cloudflare" ]; then
                docker-compose -f .deploy/ssh/docker-compose.api.stage.pre.yml up -d
            elif [ "${{ env.INGRESS_CERT_TYPE }}" = "letsencrypt" ]; then
                docker-compose -f .deploy/ssh/docker-compose.api.stage.letsencrypt.pre.yml up -d
            else
                echo "Unknown INGRESS_CERT_TYPE: $INGRESS_CERT_TYPE"
                exit 1
            fi
