name: Build and Publish Docker Images Stage

on:
    push:
        branches: stage

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    gauzy-api:
        runs-on: ubuntu-latest-m
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Free disk space
              run: |
                  df -h /
                  sudo swapoff -a
                  sudo apt clean
                  docker image ls -aq
                  docker rmi $(docker image ls -aq)
                  find ~/work/_temp -name "cache.tgz" -exec rm -f {} \;
                  sudo rm -rf "/usr/local/share/boost"
                  sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                  df -h /

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./.deploy/api/Dockerfile
                  load: true
                  platforms: linux/amd64
                  tags: |
                      ghcr.io/ever-co/gauzy-api-stage:latest
                      everco/gauzy-api-stage:latest
                      registry.digitalocean.com/ever/gauzy-api-stage:latest
                      ${{ secrets.CW_DOCKER_REGISTRY }}/ever-co/gauzy-api-stage:latest
                  cache-from: type=registry,ref=everco/gauzy-api-stage:latest
                  cache-to: type=inline

            - name: Docker images list
              run: |
                  sudo docker image list

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Push to Docker Hub Registry
              run: |
                  docker push everco/gauzy-api-stage:latest

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 3600

            - name: Push to DigitalOcean Registry
              run: |
                  docker push registry.digitalocean.com/ever/gauzy-api-stage:latest

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GH_TOKEN }}

            - name: Push to Github Registry
              run: |
                  docker push ghcr.io/ever-co/gauzy-api-stage:latest

            - name: Login to CW Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ secrets.CW_DOCKER_REGISTRY }}
                  username: ${{ secrets.CW_DOCKER_USER }}
                  password: ${{ secrets.CW_DOCKER_USER_PASSWORD }}

            - name: Push to CW Registry
              run: |
                  docker push ${{ secrets.CW_DOCKER_REGISTRY }}/ever-co/gauzy-api-stage:latest

    gauzy-webapp:
        runs-on: ubuntu-latest-m
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Free disk space
              run: |
                  df -h /
                  sudo swapoff -a
                  sudo apt clean
                  docker image ls -aq
                  docker rmi $(docker image ls -aq)
                  find ~/work/_temp -name "cache.tgz" -exec rm -f {} \;
                  sudo rm -rf "/usr/local/share/boost"
                  sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                  df -h /

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./.deploy/webapp/Dockerfile
                  load: true
                  tags: |
                      ghcr.io/ever-co/gauzy-webapp-stage:latest
                      everco/gauzy-webapp-stage:latest
                      registry.digitalocean.com/ever/gauzy-webapp-stage:latest
                      ${{ secrets.CW_DOCKER_REGISTRY }}/ever-co/gauzy-webapp-stage:latest
                  cache-from: type=registry,ref=everco/gauzy-webapp-stage:latest
                  cache-to: type=inline

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Push to Docker Hub Registry
              run: |
                  docker push everco/gauzy-webapp-stage:latest

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 3600

            - name: Push to DigitalOcean Registry
              run: |
                  docker push registry.digitalocean.com/ever/gauzy-webapp-stage:latest

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GH_TOKEN }}

            - name: Push to Github Registry
              run: |
                  docker push ghcr.io/ever-co/gauzy-webapp-stage:latest

            - name: Login to CW Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ secrets.CW_DOCKER_REGISTRY }}
                  username: ${{ secrets.CW_DOCKER_USER }}
                  password: ${{ secrets.CW_DOCKER_USER_PASSWORD }}

            - name: Push to CW Registry
              run: |
                  docker push ${{ secrets.CW_DOCKER_REGISTRY }}/ever-co/gauzy-webapp-stage:latest
